#!/usr/bin/env bash
#
# qa1/sync-from-live.sh — Nightly (Monday-armed) live → qa1 database refresh with sanitize gate.
#
# WHAT IT DOES
#   Copies the LIVE production database (nexus_os, READ-ONLY via mysqldump --single-transaction)
#   into the DISPOSABLE qa1 database (corex_qa1), then SANITIZES the copy so qa1 can never reach
#   out to the real world, PROVES the sanitize with a hard gate, and only then resumes the qa1
#   site + worker. Live is never written. Staging / andre's qatesting2 / live workers are never touched.
#
# SAFETY MODEL (why each guard exists)
#   - Refuses unless target APP_ENV=qa and target DB != the live DB (never point at production).
#   - Refuses unless qa1 mail already routes to Mailpit (127.0.0.1:1025) and WAHA is disabled.
#   - qa1 is put into maintenance + its worker stopped BEFORE the load; both resume ONLY after the
#     proof gate passes. A failed gate leaves qa1 down on purpose — a half-sanitized box never serves.
#   - Live-intended queued jobs imported from live are PURGED before the worker can pick them up.
#
# USAGE
#   sudo scripts/qa1/sync-from-live.sh --confirm          # real supervised run
#   sudo scripts/qa1/sync-from-live.sh --dry-run          # guards + plan only, no changes
#
# CRON (Monday-armed; stays OFF until Johan's word — see scripts/qa1/README.md)
#   0 2 * * 1  root  /corex-qa1/scripts/qa1/sync-from-live.sh --confirm >> /var/log/qa1-sync.log 2>&1
#
set -euo pipefail

# ---- fixed topology (this host) -------------------------------------------------------------
LIVE_DB="nexus_os"
QA1_DB="corex_qa1"
QA1_PATH="/corex-qa1"
LIVE_STORAGE="/corex/storage/app"
QA1_STORAGE="/corex-qa1/storage/app"
QA1_WORKER="corex-qa1-queue.service"
MAILPIT_SMTP_PORT="1025"
MAILPIT_API="http://127.0.0.1:8025"
WORKDIR="/var/tmp/qa1-sync"
ARTISAN=(sudo -u www-data env HOME=/tmp XDG_CONFIG_HOME=/tmp php "$QA1_PATH/artisan")
STAMP="$(date +%Y%m%d-%H%M%S)"
DUMP_FILE="$WORKDIR/live-${LIVE_DB}-${STAMP}.sql.gz"
EVIDENCE="$WORKDIR/qa1-sync-evidence-${STAMP}.md"

MODE="${1:-}"
[ "$MODE" = "--confirm" ] || [ "$MODE" = "--dry-run" ] || {
  echo "usage: $0 --confirm | --dry-run" >&2; exit 2; }
DRY=false; [ "$MODE" = "--dry-run" ] && DRY=true

log()  { printf '\n\033[1;36m[%s]\033[0m %s\n' "$(date +%H:%M:%S)" "$*"; }
ok()   { printf '   \033[1;32m✓\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m✗ ABORT:\033[0m %s\n' "$*" >&2; exit 1; }

# accumulate evidence lines
EV=()
ev() { EV+=("$*"); }
write_evidence() {
  {
    echo "# QA1 sync + sanitize — evidence pack"
    echo "> Run: ${STAMP}  ·  host live=\`$LIVE_DB\` → qa1=\`$QA1_DB\`  ·  supervised (manual) run"
    echo "> Cron is OFF. The nightly copy arms **Monday** on Johan's word (see scripts/qa1/README.md)."
    echo
    for line in "${EV[@]}"; do echo "$line"; done
    echo
    echo "---"
    echo "_Generated by scripts/qa1/sync-from-live.sh. Live was read-only throughout (mysqldump --single-transaction); staging / qatesting2 / live workers untouched._"
  } > "$EVIDENCE"
}

# =============================================================================================
# PHASE 0 — PRECONDITIONS (any failure aborts before a single byte changes)
# =============================================================================================
log "PHASE 0 — preconditions"
[ "$(id -u)" -eq 0 ] || die "must run as root (mysql socket auth + systemctl + storage rsync)"

# target is qa, not production
QA1_ENV=$(grep -E '^APP_ENV=' "$QA1_PATH/.env" | head -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
[ "$QA1_ENV" = "qa" ] || die "target APP_ENV is '$QA1_ENV', expected 'qa' — refusing (never run against non-qa)"
ok "target env is qa ($QA1_PATH)"

# target DB is not the live DB
[ "$QA1_DB" != "$LIVE_DB" ] || die "QA1_DB == LIVE_DB ($QA1_DB) — refusing"
mysql -N -e "USE $LIVE_DB" 2>/dev/null || die "cannot see live DB $LIVE_DB"
mysql -N -e "USE $QA1_DB"  2>/dev/null || die "cannot see qa1 DB $QA1_DB"
ok "live=$LIVE_DB  qa1=$QA1_DB  (distinct, both reachable)"

# qa1 mail must already be Mailpit — refuse to sync onto a box that can send real mail
QA1_MAIL_HOST=$(grep -E '^MAIL_HOST=' "$QA1_PATH/.env" | head -1 | cut -d= -f2 | tr -d '"'"'")
QA1_MAIL_PORT=$(grep -E '^MAIL_PORT=' "$QA1_PATH/.env" | head -1 | cut -d= -f2 | tr -d '"'"'")
[ "$QA1_MAIL_HOST" = "127.0.0.1" ] || die "qa1 MAIL_HOST=$QA1_MAIL_HOST (not Mailpit) — refusing"
[ "$QA1_MAIL_PORT" = "$MAILPIT_SMTP_PORT" ] || die "qa1 MAIL_PORT=$QA1_MAIL_PORT (not Mailpit $MAILPIT_SMTP_PORT) — refusing"
ok "qa1 mail routes to Mailpit ($QA1_MAIL_HOST:$QA1_MAIL_PORT)"

# Mailpit must be up (it is the proof sink)
ss -ltn 2>/dev/null | grep -q "127.0.0.1:$MAILPIT_SMTP_PORT" || die "Mailpit not listening on $MAILPIT_SMTP_PORT"
curl -sf "$MAILPIT_API/api/v1/messages?limit=1" >/dev/null || die "Mailpit API $MAILPIT_API not responding"
ok "Mailpit up (smtp $MAILPIT_SMTP_PORT, api $MAILPIT_API)"

# qa1 WAHA must be disabled (empty base url)
QA1_WAHA=$(grep -E '^WAHA_BASE_URL=' "$QA1_PATH/.env" | head -1 | cut -d= -f2 | tr -d '"'"'")
[ -z "$QA1_WAHA" ] || die "qa1 WAHA_BASE_URL is set ($QA1_WAHA) — refusing (WA must be dead on qa1)"
ok "qa1 WAHA disabled (WAHA_BASE_URL empty)"

LIVE_JOBS_NOW=$(mysql -N -e "SELECT COUNT(*) FROM $LIVE_DB.jobs;")
ok "live pending jobs at snapshot time: $LIVE_JOBS_NOW"
ev "Preconditions: target=qa ✓ · live/qa1 DBs distinct ✓ · qa1 mail=Mailpit 127.0.0.1:1025 ✓ · qa1 WAHA empty ✓ · Mailpit up ✓"
ev "Live pending jobs at snapshot: **$LIVE_JOBS_NOW** (these do NOT cross into qa1 — purged in Phase 5)."

if $DRY; then
  log "DRY-RUN — all guards passed. No changes made."
  echo "Would: dump $LIVE_DB → $DUMP_FILE → load into $QA1_DB → sanitize → gate → resume."
  exit 0
fi

mkdir -p "$WORKDIR"

# =============================================================================================
# PHASE 1 — DUMP LIVE (read-only; qa1 keeps serving old data during the dump)
# =============================================================================================
log "PHASE 1 — dump live $LIVE_DB (read-only, single-transaction snapshot)"
mysqldump --single-transaction --quick --no-tablespaces --routines --triggers --events \
  --set-gtid-purged=OFF "$LIVE_DB" | gzip > "$DUMP_FILE"
DUMP_SZ=$(du -h "$DUMP_FILE" | cut -f1)
ok "dumped → $DUMP_FILE ($DUMP_SZ)"
ev "Live dump: \`$DUMP_FILE\` ($DUMP_SZ), mysqldump --single-transaction (live never locked, never written)."

# =============================================================================================
# PHASE 2 — QUIESCE qa1 (maintenance + stop worker) — downtime begins
# =============================================================================================
log "PHASE 2 — quiesce qa1 (maintenance ON, worker STOP)"
"${ARTISAN[@]}" down --retry=60 --secret="qa1-sync-${STAMP}" >/dev/null 2>&1 || "${ARTISAN[@]}" down >/dev/null 2>&1 || true
ok "qa1 in maintenance"
systemctl stop "$QA1_WORKER"
ok "qa1 worker stopped ($QA1_WORKER)"
ev "qa1 quiesced BEFORE load: maintenance ON + worker \`$QA1_WORKER\` stopped."

# ── PRESERVE user-maintained QA-only data across the restore (snapshot NOW, qa1 still holds it) ──
# These tables carry data that is NOT on live and is NOT re-seedable from config:
#   sessions                        → keep Johan + the rig logged in across the sync
#   agency_service_providers        → the attorney/supplier directory Johan curates
#   agency_service_provider_contacts → its contact persons
# (Deterministic QA config — pipeline templates, distribution rules, sync settings — is NOT
#  preserved here; it is RE-SEEDED in PHASE 5b via QaConfigSeeder. THE CLASS RULE: any feature
#  not yet live registers its QA seed in QaConfigSeeder, or adds its user-data table here.)
PRESERVE_TABLES="sessions agency_service_providers agency_service_provider_contacts"
PRESERVE_FILE="$WORKDIR/qa1-preserve-${STAMP}.sql.gz"
log "PHASE 2c — snapshot preserved QA-only tables (sessions + attorney directory)"
SESS_PRE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.sessions;" 2>/dev/null || echo 0)
FIRMS_PRE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.agency_service_providers;" 2>/dev/null || echo 0)
mysqldump --no-tablespaces --add-drop-table "$QA1_DB" $PRESERVE_TABLES | gzip > "$PRESERVE_FILE"
ok "preserved sessions=$SESS_PRE, attorney firms=$FIRMS_PRE → $PRESERVE_FILE"

# storage rsync in the background (reads live, writes qa1) while we load the DB
log "PHASE 2b — storage rsync live → qa1 (background; live is source, read-only)"
STORAGE_LOG="$WORKDIR/storage-rsync-${STAMP}.log"
( rsync -a --delete --stats "$LIVE_STORAGE/" "$QA1_STORAGE/" > "$STORAGE_LOG" 2>&1 ) &
RSYNC_PID=$!
ok "storage rsync started (pid $RSYNC_PID) → $STORAGE_LOG"

# =============================================================================================
# PHASE 2d — CLEAN SLATE (2026-07-13). mysqldump only DROPs the tables IT contains, so any qa1
# feature table NOT on live (proforma, region_aliases, deal_contacts, … — deployed to qa1 ahead
# of live) SURVIVES the load, while the migrations log is replaced by live's. PHASE 3b migrate
# then tries to CREATE a table that already exists → 1050 → run aborts, qa1 left down. Drop every
# qa1 table first so the load yields a PURE live copy and migrate-forward is conflict-free.
# Scoped to $QA1_DB ONLY (the SELECT filters table_schema=$QA1_DB); live is never in scope.
# =============================================================================================
log "PHASE 2d — drop all qa1 tables (clean slate for a pure-live load)"
mysql -N -e "SELECT CONCAT('DROP TABLE IF EXISTS \`', table_name, '\`;') FROM information_schema.tables WHERE table_schema='$QA1_DB';" \
  | mysql --init-command="SET FOREIGN_KEY_CHECKS=0" "$QA1_DB"
ok "dropped all $QA1_DB tables (nexus_os untouched)"

# =============================================================================================
# PHASE 3 — LOAD into qa1 (DESTRUCTIVE to qa1 ONLY)
# =============================================================================================
log "PHASE 3 — load dump into qa1 $QA1_DB (overwrites qa1)"
gunzip -c "$DUMP_FILE" | mysql "$QA1_DB"
ok "loaded live snapshot into $QA1_DB"
ev "Loaded live snapshot into \`$QA1_DB\` (qa1 tables overwritten; live untouched)."

# =============================================================================================
# PHASE 3b — MIGRATE qa1 FORWARD (2026-07-13). Live tracks main and is BEHIND qa1: the load
# brought live's schema, so qa1 is now missing every unreleased migration (payroll proration
# cut_date/pro_rates_on_partial, proforma, region, etc.). Re-apply them on the live data before
# sanitize/reseed/gate — else the reseed hits missing tables and the gate leaves qa1 down.
# set -o pipefail is on: a failed migrate aborts the run (qa1 stays quiesced) — the safe outcome.
# =============================================================================================
log "PHASE 3b — migrate qa1 forward (re-apply migrations ahead of live)"
MIG_BEFORE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.migrations;")
"${ARTISAN[@]}" migrate --force 2>&1 | tail -8
MIG_AFTER=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.migrations;")
ok "migrated qa1 forward: migrations $MIG_BEFORE → $MIG_AFTER (+$((MIG_AFTER - MIG_BEFORE)))"
ev "**Schema brought forward (PHASE 3b):** re-applied $((MIG_AFTER - MIG_BEFORE)) migrations ahead of live (qa1 carries unreleased features live lacks)."

# =============================================================================================
# PHASE 4/5 — SANITIZE qa1 (purge live-intended jobs; neuter WA/syndication; clear caches/sessions)
# =============================================================================================
log "PHASE 5 — sanitize qa1"
JOBS_BEFORE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.jobs;")
BATCHES_BEFORE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.job_batches;")
FAILED_BEFORE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.failed_jobs;")
WA_BEFORE=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.communication_wa_devices WHERE active=1;")

mysql "$QA1_DB" < "$(dirname "$0")/sanitize.sql"

JOBS_AFTER=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.jobs;")
BATCHES_AFTER=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.job_batches;")
FAILED_AFTER=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.failed_jobs;")
WA_AFTER=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.communication_wa_devices WHERE active=1;")
PP_CURSORS=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.pp_event_feed_settings WHERE \`key\` LIKE 'continuation_key%';")
ok "jobs $JOBS_BEFORE→$JOBS_AFTER  batches $BATCHES_BEFORE→$BATCHES_AFTER  failed $FAILED_BEFORE→$FAILED_AFTER  wa-active $WA_BEFORE→$WA_AFTER  pp-cursors→$PP_CURSORS"
ev "**Queue purge (live-intended jobs killed before the worker resumes):** jobs **$JOBS_BEFORE → $JOBS_AFTER**, job_batches $BATCHES_BEFORE → $BATCHES_AFTER, failed_jobs $FAILED_BEFORE → $FAILED_AFTER."
ev "**WhatsApp neutered:** active devices $WA_BEFORE → $WA_AFTER (session + token nulled)."
ev "**Syndication cursors cleared:** pp_event_feed_settings continuation keys remaining = $PP_CURSORS (qa1 never resumes a live PP feed cursor; PP already sandbox + P24 import disabled in qa1 .env)."

# clear caches so the fresh DB + qa1 .env are the runtime truth
"${ARTISAN[@]}" config:clear >/dev/null; "${ARTISAN[@]}" route:clear >/dev/null
"${ARTISAN[@]}" view:clear  >/dev/null; "${ARTISAN[@]}" cache:clear >/dev/null
ok "qa1 caches cleared (config/route/view/cache)"

# =============================================================================================
# PHASE 5b — RESTORE preserved QA data + RESEED deterministic QA config (before the gate/resume)
# =============================================================================================
log "PHASE 5b — restore preserved QA data + reseed QA config"
# (1) Restore the user-maintained tables snapshotted in PHASE 2c. sanitize.sql just TRUNCATEd
#     sessions (live sessions gone); this re-lays qa1's own sessions + attorney directory.
gunzip -c "$PRESERVE_FILE" | mysql "$QA1_DB"
SESS_POST=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.sessions;" 2>/dev/null || echo 0)
FIRMS_POST=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.agency_service_providers;" 2>/dev/null || echo 0)
ok "restored sessions $SESS_PRE→$SESS_POST, attorney firms $FIRMS_PRE→$FIRMS_POST"
ev "**Preserved across the restore:** sessions ($SESS_PRE→$SESS_POST — Johan + the rig stay logged in), attorney directory firms ($FIRMS_PRE→$FIRMS_POST)."
# (2) Reseed deterministic QA-only config wiped by the live load (DR2 pipeline templates,
#     distribution matrix, deal-property-sync settings). Idempotent; refuses on production.
RESEED_OUT=$("${ARTISAN[@]}" db:seed --class=QaConfigSeeder --force 2>&1 | grep -iE "reseeded|rule|template|error" | tail -3 || true)
TMPL_N=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.deal_pipeline_templates;" 2>/dev/null || echo 0)
RULE_N=$(mysql -N -e "SELECT COUNT(*) FROM $QA1_DB.deal_stage_document_rules;" 2>/dev/null || echo 0)
ok "reseeded QA config — pipeline templates=$TMPL_N, distribution rules=$RULE_N"
ev "**Reseeded QA config (QaConfigSeeder):** DR2 pipeline templates=$TMPL_N, distribution rules=$RULE_N, deal-property-sync settings pre-warmed per agency."

# wait for storage rsync, fix ownership
log "PHASE 6 — finalize storage"
wait "$RSYNC_PID" && ok "storage rsync complete" || die "storage rsync failed — see $STORAGE_LOG"
chown -R www-data:www-data "$QA1_STORAGE"
RSYNC_XFER=$(grep -E 'Number of .*files transferred|Total transferred file size' "$STORAGE_LOG" | tr '\n' ' ')
ev "**Storage strategy applied:** one-way \`rsync -a --delete\` live→qa1 (live = source, read-only; never a symlink into live). $RSYNC_XFER"

# =============================================================================================
# PHASE 7 — PROOF GATE (must fully pass or qa1 stays DOWN)
# =============================================================================================
log "PHASE 7 — PROOF GATE"
GATE_OK=true
gate() { if eval "$2"; then ok "GATE PASS — $1"; ev "- ✅ $1"; else printf '   \033[1;31m✗ GATE FAIL — %s\033[0m\n' "$1"; ev "- ❌ $1"; GATE_OK=false; fi; }

# (a) no live-intended jobs
gate "queued jobs purged (jobs table = 0)" "[ \"\$(mysql -N -e 'SELECT COUNT(*) FROM $QA1_DB.jobs;')\" -eq 0 ]"
# (a2) QA config whole — a sync that ate the QA-only config must NOT resume (fail-safe)
gate "QA config reseeded (DR2 pipeline templates present)" "[ \"\$(mysql -N -e 'SELECT COUNT(*) FROM $QA1_DB.deal_pipeline_templates;')\" -gt 0 ]"
gate "QA config reseeded (distribution rules present)" "[ \"\$(mysql -N -e 'SELECT COUNT(*) FROM $QA1_DB.deal_stage_document_rules;')\" -gt 0 ]"
gate "QA sessions preserved (rig stays logged in)" "[ \"\$(mysql -N -e 'SELECT COUNT(*) FROM $QA1_DB.sessions;')\" -ge 0 ]"
# (b) WA dead
gate "no active WhatsApp devices" "[ \"\$(mysql -N -e 'SELECT COUNT(*) FROM $QA1_DB.communication_wa_devices WHERE active=1;')\" -eq 0 ]"
# (c) WAHA still disabled in env
gate "qa1 WAHA base url empty" "[ -z \"\$(grep -E '^WAHA_BASE_URL=' $QA1_PATH/.env | cut -d= -f2 | tr -d '\"'\"'\"'\"')\" ]"
# (d) syndication sandboxed / import off
gate "P24 import disabled in qa1 .env" "grep -qE '^P24_IMPORT_ENABLED=false' $QA1_PATH/.env"
gate "PP in sandbox in qa1 .env" "grep -qE '^PP_SANDBOX=true' $QA1_PATH/.env"

# (e) MAIL PROOF — send through the qa1 app, assert it lands in Mailpit (i.e. NOT real SMTP)
PROOF_TOKEN="QA1SYNCPROOF-${STAMP}"
log "   sending mail-routing proof through qa1 app (token $PROOF_TOKEN)"
"${ARTISAN[@]}" tinker --execute="\\Illuminate\\Support\\Facades\\Mail::raw('Sanitize gate proof ${PROOF_TOKEN}', function(\$m){ \$m->to('proof@qa1.invalid')->subject('${PROOF_TOKEN}'); });" >/dev/null 2>&1 || true
sleep 2
gate "mailer delivers to Mailpit, not real SMTP (proof token found in Mailpit)" \
     "curl -sf '$MAILPIT_API/api/v1/search?query=${PROOF_TOKEN}' 2>/dev/null | grep -q '${PROOF_TOKEN}'"

if ! $GATE_OK; then
  ev ""
  ev "## RESULT: ❌ GATE FAILED — qa1 LEFT IN MAINTENANCE, worker STOPPED. No resume. Investigate before re-run."
  write_evidence
  die "PROOF GATE FAILED — qa1 intentionally left DOWN (maintenance on, worker stopped). Evidence: $EVIDENCE"
fi
ok "ALL GATES PASSED"

# =============================================================================================
# PHASE 8 — RESUME (only reached on full gate pass)
# =============================================================================================
log "PHASE 8 — resume qa1 (gate passed)"
systemctl start "$QA1_WORKER"; ok "worker started"
"${ARTISAN[@]}" up >/dev/null 2>&1; ok "maintenance lifted"
ev ""
ev "**Resume order honoured:** site + worker resumed ONLY after the gate passed (worker \`$QA1_WORKER\` start → \`artisan up\`)."
ev ""
ev "## RESULT: ✅ SUPERVISED SYNC + SANITIZE PASSED"

# =============================================================================================
# PHASE 9 — EVIDENCE PACK
# =============================================================================================
write_evidence
log "DONE — evidence pack: $EVIDENCE"
