{{-- AT-158 DR2 · WS4 — auto-generated COC-request document (dompdf).
     Kept deliberately dompdf-friendly: table-based layout, inline CSS, no
     web fonts / flexbox / grid. Every value is drawn from deal + property +
     contact data — never hand-filled. --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    * { font-family: DejaVu Sans, sans-serif; }
    body { color: #1a1a1a; font-size: 12px; line-height: 1.5; margin: 0; }
    .wrap { padding: 6px 4px; }
    h1 { font-size: 18px; margin: 0 0 2px; color: #0b2a4a; }
    .sub { font-size: 11px; color: #555; margin: 0 0 16px; }
    .meta { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    .meta td { padding: 2px 0; vertical-align: top; }
    .meta .k { color: #555; width: 32%; }
    .meta .v { color: #111; font-weight: bold; }
    .box { border: 1px solid #cbd5e1; border-radius: 6px; padding: 12px 14px; margin-bottom: 14px; }
    .box h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: #0b2a4a; margin: 0 0 8px; }
    table.data { width: 100%; border-collapse: collapse; }
    table.data td { padding: 3px 0; vertical-align: top; }
    table.data .k { color: #555; width: 34%; }
    .req { background: #f8fafc; border-left: 3px solid #0b2a4a; padding: 10px 12px; margin-bottom: 14px; }
    .sign { margin-top: 26px; }
    .line { border-bottom: 1px solid #94a3b8; height: 26px; width: 60%; }
    .foot { margin-top: 22px; font-size: 10px; color: #777; border-top: 1px solid #e2e8f0; padding-top: 8px; }
</style>
</head>
<body>
<div class="wrap">
    <h1>Request for Certificate of Compliance</h1>
    <p class="sub">{{ $specialtyLabel }}</p>

    <table class="meta">
        <tr><td class="k">Reference</td><td class="v">{{ $deal->reference }}</td></tr>
        <tr><td class="k">Date</td><td class="v">{{ $generatedAt->format('d F Y') }}</td></tr>
        <tr><td class="k">Requested by</td><td class="v">{{ $agencyName }}</td></tr>
    </table>

    <div class="box">
        <h2>Addressed to</h2>
        <table class="data">
            <tr><td class="k">Service provider</td><td>{{ $providerName ?: '—' }}</td></tr>
            @if($providerCompany)<tr><td class="k">Company</td><td>{{ $providerCompany }}</td></tr>@endif
            @if($providerEmail)<tr><td class="k">Email</td><td>{{ $providerEmail }}</td></tr>@endif
        </table>
    </div>

    <div class="box">
        <h2>Property</h2>
        <table class="data">
            <tr><td class="k">Address</td><td>{{ $property->address ?? '—' }}</td></tr>
            @if($property && $property->suburb)<tr><td class="k">Suburb</td><td>{{ $property->suburb }}</td></tr>@endif
            @if($property && $property->erf_number)<tr><td class="k">Erf number</td><td>{{ $property->erf_number }}</td></tr>@endif
            <tr><td class="k">Owner(s)</td><td>{{ $ownerNames ?: '—' }}</td></tr>
        </table>
    </div>

    <div class="req">
        <strong>Request.</strong> Kindly arrange to inspect the above property and issue a valid
        {{ $specialtyLabel }} in respect of the pending transfer. Please liaise with the agent below to
        arrange access, and return the certificate and your invoice to the agency at the contact details
        provided. This request forms part of deal {{ $deal->reference }}.
    </div>

    <div class="box">
        <h2>Requesting agent</h2>
        <table class="data">
            <tr><td class="k">Agent</td><td>{{ $agentName ?: '—' }}</td></tr>
            @if($agentDesignation)<tr><td class="k">Designation</td><td>{{ $agentDesignation }}</td></tr>@endif
            @if($agentFfc)<tr><td class="k">FFC number</td><td>{{ $agentFfc }}</td></tr>@endif
            @if($agentEmail)<tr><td class="k">Email</td><td>{{ $agentEmail }}</td></tr>@endif
            @if($agentPhone)<tr><td class="k">Telephone</td><td>{{ $agentPhone }}</td></tr>@endif
        </table>
    </div>

    <div class="sign">
        <table class="data">
            <tr><td class="k" style="width:40%">Provider signature</td><td><div class="line"></div></td></tr>
            <tr><td class="k">Date of inspection</td><td><div class="line"></div></td></tr>
            <tr><td class="k">Certificate number</td><td><div class="line"></div></td></tr>
        </table>
    </div>

    <p class="foot">
        Auto-generated by CoreX OS for {{ $agencyName }} on {{ $generatedAt->format('d F Y H:i') }}.
        This request was produced from the deal, property and contact records — no manual entry.
    </p>
</div>
</body>
</html>
