<?php

return [
    'crops' => [
        'macadamias' => [
            'label' => 'Macadamia Nuts',
            'lifespan_years' => 60,
            'years_to_first_crop' => 4,
            'years_to_peak' => 12,
            'peak_yield_tons_per_ha' => 3.5,
            'typical_trees_per_ha' => 312,
            'current_price_per_ton' => 6500000,
            'cost_per_ha' => 3500000,
            'yield_curve' => [1=>0,2=>0,3=>0,4=>5,5=>15,6=>25,7=>40,8=>55,9=>65,10=>75,11=>85,12=>95,13=>100,15=>100,40=>100,45=>90,50=>75,55=>60,60=>40],
            'questions' => ['How old are the trees?','What variety? (Beaumont, Nelmak 2, A4)','What spacing? (8x4m, 10x5m)','Current yield in tons per hectare?','Any young orchards not yet producing?','Irrigation system type and condition?','Any disease issues? (Phytophthora, stink bug)','Husk spot or kernel quality issues?'],
        ],
        'bananas' => [
            'label' => 'Bananas',
            'lifespan_years' => 25,
            'years_to_first_crop' => 1,
            'years_to_peak' => 3,
            'peak_yield_tons_per_ha' => 50,
            'typical_trees_per_ha' => 1800,
            'current_price_per_ton' => 550000,
            'cost_per_ha' => 8000000,
            'yield_curve' => [1=>40,2=>70,3=>100,5=>100,10=>95,15=>85,20=>70,25=>50],
            'questions' => ['What variety? (Williams, Grand Naine, Goldfinger)','When was the plantation last replanted?','Current bunch weight average?','Pack-out percentage?','Any Panama disease (TR4) risk in the area?','Irrigation system type and condition?','Nematode management programme?'],
        ],
        'sugar_cane' => [
            'label' => 'Sugar Cane',
            'lifespan_years' => 8,
            'years_to_first_crop' => 1,
            'years_to_peak' => 2,
            'peak_yield_tons_per_ha' => 80,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => 85000,
            'cost_per_ha' => 2500000,
            'yield_curve' => [1=>85,2=>100,3=>95,4=>90,5=>85,6=>75,7=>65,8=>55],
            'questions' => ['What ratoon cycle are the fields in?','Which mill does the cane go to?','What is the RV percentage?','Irrigated or dryland?','What varieties? (N12, N57, N41)','Any Eldana borer pressure?','Haulage distance to mill?','Registered quota with SASA?'],
        ],
        'litchis' => [
            'label' => 'Litchis',
            'lifespan_years' => 80,
            'years_to_first_crop' => 5,
            'years_to_peak' => 15,
            'peak_yield_tons_per_ha' => 10,
            'typical_trees_per_ha' => 200,
            'current_price_per_ton' => 2000000,
            'cost_per_ha' => 3000000,
            'yield_curve' => [5=>5,7=>20,10=>50,15=>100,20=>100,40=>100,60=>80,80=>50],
            'questions' => ['What variety? (Mauritius, McLean Red, Kwai Mai Pink)','How old are the trees?','Alternate bearing pattern?','Export or local market?','Pack-house on farm?'],
        ],
        'avocados' => [
            'label' => 'Avocados',
            'lifespan_years' => 50,
            'years_to_first_crop' => 4,
            'years_to_peak' => 10,
            'peak_yield_tons_per_ha' => 12,
            'typical_trees_per_ha' => 400,
            'current_price_per_ton' => 2500000,
            'cost_per_ha' => 4500000,
            'yield_curve' => [4=>10,5=>20,6=>35,7=>50,8=>70,9=>85,10=>100,30=>100,40=>85,50=>60],
            'questions' => ['What variety? (Hass, Fuerte, Ryan, Pinkerton)','How old are the trees?','Export-registered?','GLOBALG.A.P. certified?','Irrigation type and condition?'],
        ],
        'mangoes' => [
            'label' => 'Mangoes',
            'lifespan_years' => 40,
            'years_to_first_crop' => 4,
            'years_to_peak' => 10,
            'peak_yield_tons_per_ha' => 10,
            'typical_trees_per_ha' => 200,
            'current_price_per_ton' => 800000,
            'cost_per_ha' => 2500000,
            'yield_curve' => [4=>10,6=>30,8=>60,10=>100,20=>100,30=>85,40=>60],
            'questions' => ['What variety? (Tommy Atkins, Kent, Keitt)','How old are the trees?','Export or local market?','Fruit fly management programme?'],
        ],
        'citrus' => [
            'label' => 'Citrus',
            'lifespan_years' => 35,
            'years_to_first_crop' => 3,
            'years_to_peak' => 8,
            'peak_yield_tons_per_ha' => 40,
            'typical_trees_per_ha' => 500,
            'current_price_per_ton' => 600000,
            'cost_per_ha' => 5000000,
            'yield_curve' => [3=>10,4=>25,5=>40,6=>60,7=>80,8=>100,20=>100,25=>90,30=>75,35=>50],
            'questions' => ['What type? (Navel, Valencia, Lemon, Soft Citrus)','How old are the orchards?','Export-registered?','CBS status?','Packhouse on farm?','Irrigation type?'],
        ],
        'timber' => [
            'label' => 'Timber / Forestry',
            'lifespan_years' => 25,
            'years_to_first_crop' => 8,
            'years_to_peak' => 20,
            'peak_yield_tons_per_ha' => 250,
            'typical_trees_per_ha' => 1200,
            'current_price_per_ton' => 70000,
            'cost_per_ha' => 800000,
            'yield_curve' => [8=>10,12=>25,16=>50,20=>100],
            'questions' => ['Species? (Eucalyptus, Pine, Wattle)','Age of compartments?','Compartment schedule / felling plan?','FSC certified?','Contract with mill? (Sappi, Mondi)','Fire history and fire breaks?','Distance to nearest mill?'],
        ],
        'vegetables' => [
            'label' => 'Vegetables / Market Garden',
            'lifespan_years' => 1,
            'years_to_first_crop' => 0,
            'years_to_peak' => 0,
            'peak_yield_tons_per_ha' => null,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => null,
            'cost_per_ha' => 10000000,
            'yield_curve' => [],
            'questions' => ['What crops?','Tunnel/greenhouse or open field?','Number and size of tunnels?','Irrigation system?','Market channel? (fresh produce market, retail, informal)','Cold storage on farm?'],
        ],
        'other' => [
            'label' => 'Other Crop',
            'lifespan_years' => null,
            'years_to_first_crop' => null,
            'years_to_peak' => null,
            'peak_yield_tons_per_ha' => null,
            'typical_trees_per_ha' => null,
            'current_price_per_ton' => null,
            'cost_per_ha' => null,
            'yield_curve' => [],
            'questions' => [],
        ],
    ],
    'livestock' => [
        'cattle_beef' => [
            'label' => 'Beef Cattle',
            'value_per_head' => 1500000,
            'breeding_cow_value' => 2000000,
            'bull_value' => 4500000,
            'carrying_capacity_ha' => 4,
            'annual_revenue_per_head' => 800000,
            'annual_cost_per_head' => 350000,
            'questions' => ['What breed? (Nguni, Brahman, Bonsmara, Angus)','How many breeding cows?','How many bulls?','Calving percentage?','Weaning weight average?','Supplementary feeding programme?','Dipping and vaccination programme?','Carrying capacity of the land?'],
        ],
        'cattle_dairy' => [
            'label' => 'Dairy Cattle',
            'value_per_head' => 2500000,
            'breeding_cow_value' => 3000000,
            'annual_revenue_per_head' => 3500000,
            'annual_cost_per_head' => 2200000,
            'questions' => ['What breed? (Holstein, Jersey, Ayrshire)','Herd size — milking vs dry vs heifers?','Daily production per cow (litres)?','Milk buyer? (Clover, Parmalat, Woodlands)','Milking parlour type and condition?','Bulk tank capacity?','Feed programme — pasture vs TMR?'],
        ],
        'sheep' => [
            'label' => 'Sheep',
            'value_per_head' => 300000,
            'breeding_ewe_value' => 350000,
            'ram_value' => 1200000,
            'carrying_capacity_ha' => 1.5,
            'annual_revenue_per_head' => 250000,
            'annual_cost_per_head' => 120000,
            'questions' => ['What breed? (Merino, Dorper, Dohne Merino, Ile de France)','Wool or meat focus?','Lambing percentage?','Shearing schedule?','Predator pressure? (jackal, caracal)'],
        ],
        'goats' => [
            'label' => 'Goats',
            'value_per_head' => 250000,
            'annual_revenue_per_head' => 200000,
            'annual_cost_per_head' => 80000,
            'questions' => ['What breed? (Boer, Angora, Savanna, indigenous)','Meat or mohair focus?','Kidding percentage?'],
        ],
        'pigs' => [
            'label' => 'Pigs',
            'value_per_head' => 350000,
            'annual_revenue_per_head' => 500000,
            'annual_cost_per_head' => 300000,
            'questions' => ['What breed? (Large White, Landrace, Duroc)','How many sows?','Farrowing rate?','Indoor or outdoor?','Abattoir contract?'],
        ],
        'poultry_broilers' => [
            'label' => 'Poultry — Broilers',
            'value_per_head' => 5000,
            'annual_cycles' => 6,
            'questions' => ['How many houses?','Capacity per house?','Cycles per year?','Contract grower or independent?','If contract — who? (Rainbow, Astral, County Fair)','House age and condition?','Ventilation type? (tunnel, natural)'],
        ],
        'poultry_layers' => [
            'label' => 'Poultry — Layers',
            'value_per_head' => 12000,
            'questions' => ['How many hens in production?','Production percentage?','Cage, barn, or free range?','Egg buyer?','Grading facility on farm?'],
        ],
        'game' => [
            'label' => 'Game / Wildlife',
            'value_per_head' => null,
            'questions' => ['What species? (Impala, Kudu, Nyala, Buffalo, Sable)','Game count per species?','Fencing — game proof? (2.4m)','Hunting operation or breeding?','Eco-tourism / lodge component?','Exemption certificate?'],
        ],
        'horses' => [
            'label' => 'Horses',
            'value_per_head' => 5000000,
            'questions' => ['What breed? (Thoroughbred, Boerperd, Warmblood)','Stud or working horses?','Stabling capacity?','Arena or training facilities?'],
        ],
        'other' => [
            'label' => 'Other Livestock',
            'value_per_head' => null,
            'questions' => [],
        ],
    ],
];
