<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PPRA s25 Inspection Report — {{ $agency->trading_name ?? $agency->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #1e293b; line-height: 1.6; }
        .page { padding: 36px 44px; page-break-after: always; }
        .page:last-child { page-break-after: auto; }

        /* Cover page */
        .cover { display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100%; min-height: 700px; text-align: center; }
        .cover img.logo { max-height: 90px; margin-bottom: 24px; }
        .cover h1 { font-size: 26px; color: #0f172a; margin-bottom: 6px; }
        .cover h2 { font-size: 16px; font-weight: 500; color: #475569; margin-bottom: 32px; }
        .cover .agency-name { font-size: 20px; font-weight: 700; color: #0f172a; margin-bottom: 4px; }
        .cover .agency-legal { font-size: 13px; color: #64748b; margin-bottom: 28px; }
        .cover .ref-box { background: #f1f5f9; border-radius: 6px; padding: 16px 24px; font-size: 12px; color: #334155; text-align: left; display: inline-block; }
        .cover .ref-box div { margin-bottom: 4px; }
        .cover .contact-block { margin-top: 28px; font-size: 11px; color: #64748b; }

        h2.section-title { font-size: 18px; color: #0f172a; border-bottom: 2px solid #0d9488; padding-bottom: 8px; margin-bottom: 16px; }
        h3.item-title { font-size: 14px; color: #0f172a; margin: 20px 0 6px; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 11.5px; }
        th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        th { background: #f1f5f9; color: #334155; font-weight: 700; text-transform: uppercase; font-size: 10px; letter-spacing: 0.02em; }

        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10.5px; font-weight: 700; }
        .badge-green { background: #dcfce7; color: #15803d; }
        .badge-amber { background: #fef3c7; color: #92400e; }
        .badge-red { background: #fee2e2; color: #991b1b; }
        .badge-pending { background: #e2e8f0; color: #475569; }
        .badge-info { background: #e0f2fe; color: #0369a1; }

        .item-block { margin-bottom: 18px; padding-bottom: 14px; border-bottom: 1px solid #f1f5f9; }
        .requirement { color: #475569; font-style: italic; margin-bottom: 6px; }
        .evidence { color: #334155; margin-bottom: 4px; }
        .gap-detail { background: #fef2f2; border: 1px solid #fecaca; border-radius: 4px; padding: 8px 12px; margin-top: 6px; font-size: 11px; }
        .gap-detail strong { color: #991b1b; }

        .no-gaps { color: #15803d; font-weight: 600; padding: 12px 0; }

        .footer-note { font-size: 10px; color: #94a3b8; margin-top: 24px; }
    </style>
</head>
<body>

{{-- ═══════════ 1. COVER PAGE ═══════════ --}}
<div class="page cover">
    @if($agency->logo_path)
        <img class="logo" src="{{ public_path('storage/' . $agency->logo_path) }}" alt="Logo">
    @endif
    <h1>PPRA s25 Inspection Report</h1>
    <h2>Prepared for a Property Practitioners Regulatory Authority Inspection</h2>

    <div class="agency-name">{{ $agency->trading_name ?? $agency->name }}</div>
    @if($agency->trading_name && $agency->trading_name !== $agency->name)
        <div class="agency-legal">{{ $agency->name }}</div>
    @endif

    <div class="ref-box">
        <div><strong>Report reference:</strong> {{ $reportReference }}</div>
        <div><strong>Generated:</strong> {{ $generatedAt->format('d F Y, H:i') }}</div>
        <div><strong>Generated by:</strong> {{ $generatedBy->name }}</div>
        @if($agency->ffc_no)
            <div><strong>Agency FFC number:</strong> {{ $agency->ffc_no }}</div>
        @endif
        @if($agency->ppra_number ?? null)
            <div><strong>PPRA registration number:</strong> {{ $agency->ppra_number }}</div>
        @endif
    </div>

    <div class="contact-block">
        @if($agency->address){{ $agency->address }}<br>@endif
        @if($agency->phone){{ $agency->phone }} @endif
        @if($agency->email) &bull; {{ $agency->email }}@endif
        @if(isset($principals) && $principals->isNotEmpty())
            <br><strong>Principal practitioner{{ $principals->count() > 1 ? 's' : '' }}:</strong>
            {{ $principals->pluck('name')->implode(', ') }}
        @endif
    </div>
</div>

{{-- ═══════════ 2. TABLE OF CONTENTS ═══════════ --}}
<div class="page">
    <h2 class="section-title">Table of Contents</h2>
    <table>
        <thead>
            <tr><th style="width:5%;">Item</th><th>Description</th><th style="width:15%;">Status</th></tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr>
                <td>{{ $row->item }})</td>
                <td>{{ $row->label }}</td>
                <td>
                    @if($row->status === 'pending')
                        <span class="badge badge-pending">Not yet available</span>
                    @else
                        <span class="badge badge-{{ $row->status }}">{{ ucfirst($row->status) }}</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

{{-- ═══════════ 3. EXECUTIVE SUMMARY OF GAPS ═══════════ --}}
<div class="page">
    <h2 class="section-title">Executive Summary of Gaps</h2>
    @if($gaps->isEmpty())
        <p class="no-gaps">No outstanding items.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th style="width:5%;">Item</th>
                    <th>Description</th>
                    <th style="width:10%;">Status</th>
                    <th style="width:15%;">Remediation Due</th>
                    <th style="width:15%;">Assigned To</th>
                    <th>Note</th>
                </tr>
            </thead>
            <tbody>
                @foreach($gaps as $row)
                <tr>
                    <td>{{ $row->item }})</td>
                    <td>{{ $row->label }}</td>
                    <td><span class="badge badge-{{ $row->status }}">{{ ucfirst($row->status) }}</span></td>
                    <td>{{ $row->gap_note?->remediation_due_date?->format('d M Y') ?? 'No date set' }}</td>
                    <td>{{ $row->gap_note?->assignedTo?->name ?? '—' }}</td>
                    <td>{{ $row->gap_note?->note ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif
</div>

{{-- ═══════════ 4. PER-ITEM DETAIL SECTIONS ═══════════ --}}
<div class="page">
    <h2 class="section-title">Item Detail</h2>

    @foreach($rows as $row)
    <div class="item-block">
        <h3 class="item-title">{{ $row->item }}) {{ $row->label }}</h3>

        @if($row->status === 'pending')
            <p class="requirement">Not yet available — a later build phase.</p>
        @else
            @if($row->requirement)
                <p class="requirement">{{ $row->requirement }}</p>
            @endif

            <p>
                <span class="badge badge-{{ $row->status }}">{{ ucfirst($row->status) }}</span>
                {{ $row->why }}
            </p>

            @if($row->document)
                <p class="evidence">
                    <strong>Document on file:</strong> {{ $row->document->name }}
                    &mdash; uploaded {{ $row->document->uploaded_at->format('d M Y') }}
                    @if($row->document->expires_at) &mdash; expires {{ $row->document->expires_at->format('d M Y') }} @endif
                </p>
            @elseif($row->evidence)
                <p class="evidence"><strong>Evidence included:</strong> {{ $row->evidence }}</p>
            @endif

            @if(in_array($row->status, ['amber', 'red']) && $row->gap_note)
                <div class="gap-detail">
                    <strong>Remediation due:</strong> {{ $row->gap_note->remediation_due_date?->format('d M Y') ?? 'No date set' }}
                    @if($row->gap_note->assignedTo) &mdash; assigned to {{ $row->gap_note->assignedTo->name }} @endif
                    @if($row->gap_note->note)<br>{{ $row->gap_note->note }}@endif
                </div>
            @endif

            {{-- Practitioner FFC Table — lives inside item (f)'s own section, not a
                 separate appendix (spec §6.2 item 5): this is where a reader
                 expects the full roster once they've read "Practitioner List
                 & FFC Numbers". Item (c)'s own section shows the same shape,
                 filtered to the principal(s) only. --}}
            @if($row->item === 'f' && isset($roster) && $roster->isNotEmpty())
                <table>
                    <thead>
                        <tr><th>Name</th><th style="width:16%;">Role</th><th style="width:16%;">FFC Number</th><th style="width:12%;">Status</th><th style="width:14%;">Expiry</th></tr>
                    </thead>
                    <tbody>
                        @foreach($roster as $agent)
                        <tr>
                            <td>{{ $agent['name'] }}</td>
                            <td>{{ ucwords(str_replace('_', ' ', $agent['role'] ?? '')) }}</td>
                            <td>{{ $agent['ffc_number'] ?? '—' }}</td>
                            <td><span class="badge badge-{{ $agent['ffc']['status'] }}">{{ $agent['ffc']['label'] }}</span></td>
                            <td>{{ $agent['ffc']['expiry_date'] ? \Illuminate\Support\Carbon::parse($agent['ffc']['expiry_date'])->format('d M Y') : '—' }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif

            @if($row->item === 'c' && isset($principals))
                @if($principals->isNotEmpty())
                    <table>
                        <thead>
                            <tr><th>Name</th><th style="width:16%;">Role</th><th style="width:16%;">FFC Number</th><th style="width:12%;">Status</th><th style="width:14%;">Expiry</th></tr>
                        </thead>
                        <tbody>
                            @foreach($principals as $agent)
                            <tr>
                                <td>{{ $agent['name'] }}</td>
                                <td>{{ ucwords(str_replace('_', ' ', $agent['role'] ?? '')) }}</td>
                                <td>{{ $agent['ffc_number'] ?? '—' }}</td>
                                <td><span class="badge badge-{{ $agent['ffc']['status'] }}">{{ $agent['ffc']['label'] }}</span></td>
                                <td>{{ $agent['ffc']['expiry_date'] ? \Illuminate\Support\Carbon::parse($agent['ffc']['expiry_date'])->format('d M Y') : '—' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                @else
                    <p class="evidence">No user is flagged Principal Property Practitioner for this agency.</p>
                @endif
            @endif

            {{-- Item (i) — transformation initiatives: structured rows or a
                 reference to the uploaded document (§6.5). --}}
            @if($row->item === 'i' && isset($transformation) && $transformation)
                @if($transformation->entry_type === 'structured' && is_array($transformation->structured_data) && count($transformation->structured_data))
                    <table>
                        <thead>
                            <tr><th>Description</th><th style="width:14%;">Start</th><th style="width:14%;">End</th><th style="width:20%;">People Involved</th><th style="width:14%;">Spend (ZAR)</th></tr>
                        </thead>
                        <tbody>
                            @foreach($transformation->structured_data as $initiative)
                            <tr>
                                <td>{{ $initiative['description'] ?? '—' }}</td>
                                <td>{{ !empty($initiative['start_date']) ? \Illuminate\Support\Carbon::parse($initiative['start_date'])->format('d M Y') : '—' }}</td>
                                <td>{{ !empty($initiative['end_date']) ? \Illuminate\Support\Carbon::parse($initiative['end_date'])->format('d M Y') : '—' }}</td>
                                <td>{{ $initiative['people_involved'] ?? '—' }}</td>
                                <td>{{ isset($initiative['spend_amount']) && $initiative['spend_amount'] !== '' ? number_format((float) $initiative['spend_amount'], 2) : '—' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                @elseif($transformation->entry_type === 'document')
                    <p class="evidence"><strong>Uploaded statement:</strong> {{ $transformation->document_original_name }} &mdash; saved {{ $transformation->created_at->format('d M Y') }}.</p>
                @endif
            @endif

            {{-- Item (j) — sales/rentals FY list caveat (§6.7). --}}
            @if($row->item === 'j')
                <p class="evidence" style="font-style:italic;">
                    "Advertised" is derived from Property24/PrivateProperty activation and the agency's own website
                    syndication. P24/PrivateProperty carry only the most recent activation date, not a full on/off
                    history — a property advertised, pulled, and re-advertised within this financial year still
                    correctly counts as advertised, but multiple separate windows within the year cannot be
                    reconstructed from those two columns alone.
                </p>
            @endif

            {{-- Item (k) — sales file samples, per-file index (§6.2 item 5 / §6.8b, Phase G). --}}
            @if($row->item === 'k')
                @if(!isset($kSample) || count($kSample) === 0)
                    <p class="evidence">No sales files sampled for this pack.</p>
                @else
                    @foreach($kSample as $sample)
                        <p class="evidence"><strong>{{ $sample->reference }}</strong> &mdash; {{ $sample->deal->property_address ?? 'no address on file' }} &mdash; folder: <code>{{ $sample->folder }}</code></p>
                        <table>
                            <thead>
                                <tr><th>Category</th><th>File</th><th>Path in ZIP</th></tr>
                            </thead>
                            <tbody>
                                @foreach($sample->sections as $section)
                                    @forelse($section['files'] as $file)
                                        <tr>
                                            <td>{{ $section['category'] }}</td>
                                            <td>{{ $file->label }}{{ $file->note ? ' — ' . $file->note : '' }}</td>
                                            <td>{{ $file->dest_path }}</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td>{{ $section['category'] }}</td>
                                            <td colspan="2" style="color:#991b1b;">Nothing found for this category.</td>
                                        </tr>
                                    @endforelse
                                @endforeach
                            </tbody>
                        </table>
                        @if(count($sample->missing))
                            <p class="evidence" style="color:#991b1b;">
                                <strong>Missing:</strong>
                                @foreach($sample->missing as $m)
                                    {{ $m }}@if(!$loop->last)<br>@endif
                                @endforeach
                            </p>
                        @endif
                    @endforeach
                @endif
            @endif
        @endif
    </div>
    @endforeach

    <p class="footer-note">
        {{ $agency->trading_name ?? $agency->name }} &bull; {{ $reportReference }} &bull; generated {{ $generatedAt->format('d M Y H:i') }}
    </p>
</div>

</body>
</html>
