<?php

namespace App\Models;

use App\Models\CommandCenter\CalendarEvent;
use App\Models\CommandCenter\CalendarEventLink;
use App\Models\Concerns\BelongsToAgency;
use App\Models\Concerns\BelongsToBranch;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Property extends Model
{
    use SoftDeletes, BelongsToAgency, BelongsToBranch;

    /**
     * Transient (NOT persisted) flag set by bulk importers before save. When
     * true, the `created()` observer skips new-listing automation — the
     * document-chase chore tasks generated by AutoEventService::onPropertyCreated().
     *
     * Bulk-imported stock (P24 go-live onboarding especially) is existing
     * inventory, not a freshly captured mandate the agent must chase to
     * compliance — generating ~5 "Upload signed mandate / owner ID / proof of
     * ownership" tasks per imported listing floods the Tasks board (it grew an
     * 18k-row backlog on staging and OOM'd the page). Genuine new mandates
     * (manual capture, promoteToStock) leave this false and still get their
     * chase tasks. Declared (not dynamic) so it survives PHP 8.2 strictness.
     */
    public bool $skipNewListingAutomation = false;

    /**
     * Off-market / terminal listing statuses — the single source of truth for
     * "this listing is NOT live on the market". Everything else (for_sale, incl.
     * Reduced Price / Pending sub-labels, under_offer, on_show, on_auction,
     * to_let, the legacy 'active', …) is considered ON MARKET. Use
     * Property::OFF_MARKET_STATUSES / scopeOnMarket() everywhere instead of
     * re-listing these literals — see BUILD_STANDARD §6 (fix the class).
     *
     * NOTE: distinct from scopeTransactionLive()'s mandate-liveness check, which
     * is about mandate expiry, not on-market display.
     */
    public const OFF_MARKET_STATUSES = [
        'sold', 'transferred', 'withdrawn', 'expired',
        'cancelled', 'let_out', 'draft', 'archived', 'unavailable',
    ];

    /**
     * On-market listings = base status NOT in OFF_MARKET_STATUSES. This is the
     * canonical definition of "active"/live stock for dashboards and filters.
     */
    public function scopeOnMarket($query)
    {
        return $query->whereNotIn('status', self::OFF_MARKET_STATUSES);
    }

    /**
     * Instance mirror of scopeOnMarket() — true when this property is live on
     * the market. Same single source of truth (OFF_MARKET_STATUSES) so the
     * row-level check can never drift from the query scope. Used by the MIC
     * stock matcher: only on-market stock may carry an "IN STOCK" badge / be
     * suppressed from the prospectable pool (BUILD_STANDARD §6 — fix the class).
     */
    public function isOnMarket(): bool
    {
        return ! in_array((string) $this->status, self::OFF_MARKET_STATUSES, true);
    }

    /**
     * The one value of p24_syndication_status / pp_syndication_status that means
     * "the portal no longer carries this listing". Every other value — including
     * the terminal-but-still-listed 'sold' / 'rented' — means the listing may
     * still be visible, so a delist must be attempted.
     */
    public const PORTAL_OFF_STATUS = 'deactivated';

    /**
     * P24 statuses that are terminal on the market but leave the listing ON the
     * portal. Written by PropertyObserver's status auto-sync; recognised here so
     * the delist guards and the portal-link builder agree on what "still live"
     * means. See Property24ListingMapper::removesFromPortal().
     */
    public const P24_ON_PORTAL_TERMINAL_STATUSES = ['sold', 'rented'];

    /**
     * Statuses that CLAIM the portal is not carrying the listing. If P24 is in
     * fact still showing one of these, it is a stranded public advert — the
     * harmful direction of status drift, and the class that stranded #2142.
     *
     * This is the suspect set for p24:reconcile-portal-presence. It is deliberately
     * WIDER than PORTAL_OFF_STATUS alone: 'error' and 'rejected' equally read as
     * "not advertised" to a human looking at the panel, and they equally hide a
     * listing that is publicly live. Sweeping only 'deactivated' left 189 rows
     * (159 error + 30 rejected) that nothing ever checked.
     *
     * NOT included: 'submitted'/'pending'/'active' (the 15-min SyncProperty24Activations
     * job owns those) and 'sold'/'rented' (terminal but legitimately still ON the
     * portal — see P24_ON_PORTAL_TERMINAL_STATUSES).
     */
    public const P24_CLAIMS_OFF_PORTAL_STATUSES = [self::PORTAL_OFF_STATUS, 'error', 'rejected'];

    /**
     * True when P24 may still be showing this listing. The ONLY safe basis for a
     * delist guard: we hold a portal reference and nothing has told us the
     * listing left the portal. Anything else — 'sold', 'rented', 'pending',
     * 'error', 'submitting' — is a listing we must still try to withdraw.
     *
     * Deliberately NOT gated on p24_syndication_enabled: that flag is a "should
     * CoreX sync" switch, and a listing toggled off while live is exactly the
     * case that stranded property #2142 on the portal.
     */
    public function mayBeLiveOnP24(): bool
    {
        return ! empty($this->p24_ref)
            && $this->p24_syndication_status !== self::PORTAL_OFF_STATUS;
    }

    /** Private Property mirror of mayBeLiveOnP24(). */
    public function mayBeLiveOnPp(): bool
    {
        return ! empty($this->pp_ref)
            && $this->pp_syndication_status !== self::PORTAL_OFF_STATUS;
    }

    /**
     * True when this property is still an unpublished draft. A draft is never
     * ready to be pushed to any portal/website — it must be set Active first.
     * Case-insensitive so 'Draft'/'DRAFT' are caught alongside the canonical
     * lowercase 'draft'. The single source of truth for the syndication draft
     * guard (EnforcesMarketingReadiness::enforceListingNotDraft()).
     */
    public function isDraft(): bool
    {
        return strtolower(trim((string) $this->status)) === 'draft';
    }

    /**
     * AT-262 — has this listing EVER been advertised (website or a portal)?
     *
     * "Ever", not "now": these markers are set when a listing goes public and are
     * NOT cleared on withdrawal (a delisted P24 listing keeps its ref/activated_at),
     * so a withdrawn-back-to-draft listing still answers true. A listing with none
     * of them has genuinely never been public.
     */
    public function wasEverAdvertised(): bool
    {
        if ($this->published_at !== null) {
            return true;                                                    // HFC website publish flag
        }
        if ($this->p24_activated_at !== null || $this->pp_activated_at !== null) {
            return true;                                                    // portal activation
        }
        if ($this->p24_last_submitted_at !== null || $this->pp_last_submitted_at !== null) {
            return true;                                                    // portal submission
        }
        if (filled($this->p24_ref) || filled($this->pp_ref)) {
            return true;                                                    // a portal listing was created
        }

        // Own website (property_website_syndication) — ever enabled / submitted /
        // activated, INCLUDING rows soft-deleted when the site was later disabled.
        // DB::table sees soft-deleted rows, so this reads true history.
        return \Illuminate\Support\Facades\DB::table('property_website_syndication')
            ->where('property_id', $this->id)
            ->where(function ($q) {
                $q->where('enabled', true)
                  ->orWhereNotNull('activated_at')
                  ->orWhereNotNull('last_submitted_at');
            })
            ->exists();
    }

    /**
     * AT-262 (Johan's gate) — "Change listing type" is available ONLY for a draft
     * that has NEVER been advertised. It is the "I loaded a rental that should have
     * been a sale" fix, nothing more. Any advertised/active listing uses Duplicate
     * instead, so its live history is never archived out from under the portals.
     */
    public function canChangeType(): bool
    {
        return $this->isDraft() && ! $this->wasEverAdvertised();
    }

    /**
     * Whether this property type is a habitable dwelling that is normally
     * listed with bedroom/bathroom counts. Land, farms, commercial and
     * industrial stock are not — so readiness/completeness gates must not
     * demand Beds/Baths for them. Classification mirrors the same
     * normalised-token matching used by the P24 type resolver
     * (Property24ListingMapper::resolvePropertyTypeId) so the two never
     * disagree on what counts as "land/commercial".
     */
    public function requiresBedsBaths(): bool
    {
        $type = (string) $this->property_type;
        if ($type === '') {
            // Unknown type: assume a dwelling so we never silently drop the
            // Beds/Baths gate for a normal residential listing.
            return true;
        }

        // Normalise: lowercase, non-alphanum → single space, collapse, trim,
        // then pad so whole-token matching ("land" not "highland") works.
        $norm = trim(preg_replace('/\s+/', ' ', preg_replace('/[^a-z0-9]+/i', ' ', strtolower($type))));
        $padded = " {$norm} ";
        $contains = static function (string ...$needles) use ($padded): bool {
            foreach ($needles as $n) {
                if (str_contains($padded, " {$n} ")) {
                    return true;
                }
            }
            return false;
        };

        // Land / farm / commercial / industrial → no Beds/Baths expected.
        if ($contains('industrial')) return false;
        if ($contains('commercial', 'office', 'retail', 'hospitality')) return false;
        if ($contains('farm', 'smallholding', 'small holding', 'agricultural')) return false;
        if ($contains('vacant land', 'land', 'plot', 'stand', 'erf')) return false;

        return true;
    }

    /**
     * Derived public-website fields surfaced on every serialisation so the
     * listing's cosmetic slug and canonical public URL are available
     * everywhere CoreX shows the property. Both are computed (never stored),
     * so they can never go stale when the title changes.
     */
    protected $appends = ['slug', 'public_url'];

    protected $fillable = [
        'external_id',
        'p24_listing_number',
        'title',
        'excerpt',
        'description',
        'price',
        'price_on_application',
        'has_deposit',
        'lease_period',
        'price_per_day',
        'price_per_week',
        'price_per_year',
        'lease_type',
        'gross_price',
        'net_price',
        'yard_price',
        'primary_price_display',
        'rates_taxes',
        'levy',
        'special_levy',
        'rental_amount',
        'deposit_amount',
        'commission_percent',
        'admin_fee',
        'marketing_fee',
        'city',
        'suburb',
        'suburb_normalised',
        'address',
        'region',
        'district',
        'beds',
        'baths',
        'half_baths',
        'garages',
        'size_m2',
        'erf_size_m2',
        'property_number',
        'complex_name',
        'unit_number',
        'property_type',
        'title_type',
        'category',
        'condition_level_id',
        'mandate_type',
        'listing_type',
        'listing_type_pending',
        'status',
        'pre_deal_offer_status',
        'status_label',
        'features_json',
        'features_json_meta',
        'pet_friendly',
        'spaces_json',
        'images_json',
        'dawn_images_json',
        'noon_images_json',
        'dusk_images_json',
        'gallery_images_json',
        'gallery_categories_json',
        'gallery_custom_tags',
        'agent_id',
        'branch_id',
        // agency_id is the tenant key. It stays fillable so trusted non-auth ingress
        // (promoteToStock, sold-import, P24 jobs) can stamp it — but a request from
        // an AUTHENTICATED user can never spoof it: BelongsToAgency::creating()
        // force-overrides agency_id to the user's effective agency. See that trait.
        'agency_id',
        'is_demo',
        'published_at',
        'listed_date',
        'expiry_date',
        'lease_start_date',
        'lease_end_date',
        'headline',
        'street_name',
        'street_name_normalised',
        'street_number',
        'province',
        'town',
        'latitude',
        'longitude',
        'geo_source',
        'geo_confidence',
        'geo_resolved_at',
        'pp_suburb_id',
        'p24_suburb_id',
        'p24_city_id',
        'p24_province_id',
        'p24_suburb_mismatch',
        'pp_syndication_enabled',
        'pp_syndication_status',
        'pp_ref',
        'pp_listing_feed_ref',
        'pp_last_submitted_at',
        'pp_activated_at',
        'pp_exclusive_days',
        'pp_delay_until',
        'pp_last_error',
        'pp_images_last_synced_at',
        'pp_listing_last_synced_at',
        'floor_number',
        'unit_section_block',
        'stand_number',
        'zone_type',
        'address_internal_note',
        'pp_second_agent_id',
        'pp_agent_image_path',
        'pp_second_agent_image_path',
        'pp_hide_street_name',
        'pp_hide_street_number',
        'pp_hide_complex_name',
        'pp_hide_unit_number',
        'p24_hide_address',
        'youtube_video_id',
        'matterport_id',
        'virtual_tour_url',
        'rental_price_type',
        'p24_syndication_enabled',
        'p24_syndication_status',
        'p24_ref',
        'p24_last_submitted_at',
        'p24_activated_at',
        'p24_last_error',
        'p24_images_last_synced_at',
        'p24_listing_last_synced_at',
        'p24_image_signature',
        'compliance_snapshot_at',
        'compliance_snapshot_data',
        'compliance_evidence_flags',
        'first_marketed_at',
        'erf_number',
        'title_deed_number',
        'municipal_valuation',
        'municipal_valuation_year',
        'cma_gps_lat',
        'cma_gps_lng',
        'last_cma_at',
        'last_cma_presentation_id',
        'rental_images_json',
    ];

    protected $casts = [
        'images_json'         => 'array',
        'dawn_images_json'    => 'array',
        'noon_images_json'    => 'array',
        'dusk_images_json'    => 'array',
        'gallery_images_json' => 'array',
        'gallery_categories_json' => 'array',
        'gallery_custom_tags'     => 'array',
        'rental_images_json'      => 'array',
        'features_json'       => 'array',
        'features_json_meta'  => 'array',
        'pet_friendly'        => 'boolean',
        'spaces_json'         => 'array',
        'published_at'        => 'datetime',
        'price'               => 'integer',
        'price_on_application' => 'boolean',
        'has_deposit'         => 'boolean',
        'listing_type_pending' => 'boolean',
        // Money columns are decimal(12,2) in the schema (storage precision is
        // preserved there regardless of cast). They are cast to float — NOT
        // decimal:2 — on purpose: the decimal cast returns STRINGS, and every
        // consumer in this codebase (P24/PP mappers, website + mobile JSON APIs,
        // document merge fields) treats these as numbers. A string cast silently
        // changes API/serialization contracts ("8500.00" vs 8500). Keep float.
        'price_per_day'       => 'float',
        'price_per_week'      => 'float',
        'price_per_year'      => 'float',
        'gross_price'         => 'float',
        'net_price'           => 'float',
        'yard_price'          => 'float',
        'rates_taxes'         => 'integer',
        'levy'                => 'integer',
        'special_levy'        => 'integer',
        'listed_date'         => 'date',
        'expiry_date'         => 'date',
        'lease_start_date'    => 'date',
        'lease_end_date'      => 'date',
        'baths'               => 'decimal:1',
        'half_baths'          => 'integer',
        'rental_amount'       => 'float',
        'deposit_amount'      => 'float',
        'commission_percent'  => 'float',
        'admin_fee'           => 'float',
        'marketing_fee'       => 'float',
        'latitude'                => 'decimal:7',
        'longitude'               => 'decimal:7',
        'geo_resolved_at'         => 'datetime',
        'pp_suburb_id'            => 'integer',
        'p24_suburb_id'           => 'integer',
        'p24_city_id'             => 'integer',
        'p24_province_id'         => 'integer',
        'p24_suburb_mismatch'     => 'boolean',
        'pp_syndication_enabled'  => 'boolean',
        'pp_last_submitted_at'    => 'datetime',
        'pp_activated_at'         => 'datetime',
        'pp_exclusive_days'       => 'integer',
        'pp_delay_until'          => 'datetime',
        'pp_images_last_synced_at'  => 'datetime',
        'pp_listing_last_synced_at' => 'datetime',
        'pp_hide_street_name'       => 'boolean',
        'pp_hide_street_number'     => 'boolean',
        'pp_hide_complex_name'      => 'boolean',
        'pp_hide_unit_number'       => 'boolean',
        'p24_hide_address'          => 'boolean',
        'p24_syndication_enabled'     => 'boolean',
        'p24_last_submitted_at'       => 'datetime',
        'p24_activated_at'            => 'datetime',
        'p24_images_last_synced_at'   => 'datetime',
        'p24_listing_last_synced_at'  => 'datetime',
        'compliance_snapshot_at'      => 'datetime',
        'compliance_snapshot_data'    => 'array',
        'compliance_evidence_flags'   => 'array',
        'first_marketed_at'           => 'datetime',
        'municipal_valuation'         => 'decimal:2',
        'municipal_valuation_year'    => 'integer',
        'cma_gps_lat'                 => 'decimal:7',
        'cma_gps_lng'                 => 'decimal:7',
        'last_cma_at'                 => 'datetime',
        'last_cma_presentation_id'    => 'integer',
    ];

    protected static function boot(): void
    {
        parent::boot();

        static::creating(function (Property $property) {
            if (empty($property->external_id)) {
                $property->external_id = (string) Str::uuid();
            }
        });

        // Dedup foundation Q4 Phase B Step 2 — keep the normalised-address
        // cache in sync with the raw source columns on every save. The
        // cache lets cross-source dedup match this Property against TPs +
        // portal-scrape rows + LocationGrouper composites via the same
        // composite key shape they all share (see PropertyAddressKey).
        static::saving(function (Property $property) {
            if ($property->isDirty('suburb') || $property->suburb_normalised === null) {
                $property->suburb_normalised = \App\Models\Prospecting\TrackedPropertyAddress::normaliseSuburb($property->suburb);
            }
            if ($property->isDirty('street_name') || $property->street_name_normalised === null) {
                $property->street_name_normalised = \App\Models\Prospecting\TrackedPropertyAddress::normaliseStreet($property->street_name);
            }
        });
    }

    public function agent(): BelongsTo
    {
        return $this->belongsTo(User::class, 'agent_id');
    }

    /**
     * Co-listing agent. A listing may be worked by two agents — the secondary
     * is stored on `pp_second_agent_id` (originally added for P24/PrivateProperty
     * dual-agent syndication) and is surfaced to agency websites alongside the
     * primary so a co-listed property appears on BOTH agents' profiles.
     */
    public function secondAgent(): BelongsTo
    {
        return $this->belongsTo(User::class, 'pp_second_agent_id');
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    /** Build 3 — the property's recorded condition level (drives CMA
     *  Middle band adjustment). Nullable: a property without a recorded
     *  condition gets no adjustment, baseline valuation only. */
    public function conditionLevel(): BelongsTo
    {
        return $this->belongsTo(PropertySettingItem::class, 'condition_level_id');
    }

    public function showdays(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(PropertyShowday::class)->orderBy('start_date');
    }

    public function activeShowdays(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(PropertyShowday::class)->where('active', true)->where('end_date', '>=', now())->orderBy('start_date');
    }

    public function agency(): BelongsTo
    {
        return $this->belongsTo(Agency::class);
    }

    /**
     * Resolve the Property24 agency ID this listing should be submitted under.
     * Branch override wins; falls back to the agency default. Null when neither
     * is configured — callers must treat null as "not syndicatable".
     */
    public function resolveP24AgencyId(): ?string
    {
        if ($this->branch) {
            $resolved = $this->branch->resolveP24AgencyId();
            if ($resolved !== null) {
                return $resolved;
            }
        }
        $agencyId = $this->agency?->p24_agency_id;
        return $agencyId !== null && $agencyId !== '' ? (string) $agencyId : null;
    }

    public function notes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(PropertyNote::class)->latest();
    }

    /** @deprecated Use documents() instead. Kept for backward compat during transition. */
    public function files(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(PropertyFile::class)->latest();
    }

    /** Per-(property × website) syndication rows. Spec: agency-public-api.md §6.5.2. */
    public function websiteSyndication(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(\App\Models\PropertyWebsiteSyndication::class);
    }

    public function documents(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Document::class, 'document_properties')
            ->withTimestamps()
            ->latest('documents.created_at');
    }

    public function contacts(): BelongsToMany
    {
        return $this->belongsToMany(Contact::class, 'contact_property')
                    ->withPivot('role')
                    ->withTimestamps();
    }

    /**
     * AT-105 — the seller/owner-side contact for this property, used when the
     * PDF Splitter files contact-destined documents (FICA, ID, Proof of
     * Residence) and when pre-populating a wet-ink FICA verification.
     *
     * Priority: a contact whose pivot role is on the seller side
     * (seller/owner/landlord/lessor — canon from BackfillContactPropertyRoles).
     * Falls back to the sole linked contact when there is exactly one, so a
     * property whose single contact has a NULL/odd role still resolves. Returns
     * null when ambiguous (multiple contacts, none seller-side) — the caller
     * then files to the property only (no orphan, no wrong guess).
     */
    public function sellerOwnerContact(): ?Contact
    {
        $contacts = $this->contacts()->get();

        if ($contacts->isEmpty()) {
            return null;
        }

        $sellerSide = ['seller', 'owner', 'landlord', 'lessor'];
        $match = $contacts->first(function ($c) use ($sellerSide) {
            $role = strtolower(trim((string) ($c->pivot->role ?? '')));
            return in_array($role, $sellerSide, true);
        });

        if ($match) {
            return $match;
        }

        return $contacts->count() === 1 ? $contacts->first() : null;
    }

    /**
     * AT-105 enhancement — the canonical pivot-role SET a routing contact_role
     * resolves across. 'seller_owner' deliberately spans BOTH seller and owner
     * (esign auto-link writes 'owner' for sellers — investigation §3). Returns
     * [] for 'none' / unknown so callers skip contact resolution cleanly.
     *
     * @return string[]
     */
    public static function pivotRolesForContactRole(?string $contactRole): array
    {
        return [
            'seller_owner' => ['seller', 'owner'],
            'buyer'        => ['buyer'],
            'tenant'       => ['tenant'],
            'landlord'     => ['landlord'],
            'lessor'       => ['lessor'],
        ][$contactRole] ?? [];
    }

    /**
     * AT-105 enhancement — ALL contacts attached to this property in a given
     * routing role, in pivot order. Unlike sellerOwnerContact() this is
     * multi-valued (joint sellers / joint buyers) and never collapses to a
     * single guess. Case-/whitespace-insensitive on the stored pivot role.
     * Returns an empty collection for role 'none'/unknown or no matches.
     */
    public function contactsForRole(?string $contactRole): \Illuminate\Support\Collection
    {
        $set = self::pivotRolesForContactRole($contactRole);
        if (empty($set)) {
            return collect();
        }

        return $this->contacts()->get()->filter(function ($c) use ($set) {
            $role = strtolower(trim((string) ($c->pivot->role ?? '')));
            return in_array($role, $set, true);
        })->values();
    }

    /**
     * AT-238 — the physical filing-register entries for this property.
     *
     * A READ-THROUGH, deliberately: the property does NOT carry a copy of the file reference.
     * The register owns that fact, and a duplicated reference on the property would be one
     * more thing to drift the day a file is re-numbered. The property simply asks.
     *
     * A property can legitimately have SEVERAL (an OA and an EA are separate documents with
     * separate lifespans), so this is many.
     */
    public function filings(): HasMany
    {
        return $this->hasMany(\App\Models\DocumentFiling::class, 'property_id');
    }

    /**
     * AT-243 — the deal that actually BOUGHT this property, if any.
     *
     * The deal register is the one truth: the purchasing deal is the property's deal in
     * the committed lane (Granted or Registered), of which Wave 2 guarantees there is at
     * most one. Nothing is stored on the property — this is read from deal state, so the
     * whole lifecycle comes free:
     *
     *   grant        → a committed deal exists      → purchaser appears
     *   fall-through → it is declined, none commits → purchaser disappears by itself
     *   resale       → a new deal is granted        → the new purchaser is derived
     *
     * There is no flag to set, unset, or forget to unset.
     */
    public function purchasingDeal(): ?\App\Models\Deal
    {
        if (! $this->id) {
            return null;
        }

        return app(\App\Services\Deal\DealPropertyStatusService::class)
            ->committedDealOnProperty((int) $this->id);
    }

    /**
     * The contact ids of the actual purchaser(s) — the buyer party of the purchasing deal.
     * Joint buyers are normal, so this is a set. Empty when nothing has been granted, which
     * is the honest answer: an offer is not a purchase.
     *
     * Legacy deals captured before the deal↔party link existed carry no parties; they were
     * backfilled where the buyer was unambiguous, and where it genuinely was not, no
     * purchaser is claimed rather than one being guessed.
     *
     * @return array<int,int>
     */
    public function purchaserContactIds(): array
    {
        $deal = $this->purchasingDeal();
        if (! $deal) {
            return [];
        }

        return $deal->buyers()->pluck('contacts.id')->map(fn ($id) => (int) $id)->all();
    }

    // ── Presentations V2 ──

    public function presentations(): HasMany
    {
        return $this->hasMany(Presentation::class, 'property_id')->latest();
    }

    /** Phase 3j — SG documents referenced for this property. */
    public function sgDocuments(): HasMany
    {
        return $this->hasMany(\App\Models\PropertySgDocument::class, 'property_id')->latest();
    }

    public function latestPresentation(): ?Presentation
    {
        return $this->presentations()->first();
    }

    // ── Address Helpers ──

    /**
     * Build the best human-readable address from available fields.
     * Priority: structured parts (unit_number, complex_name, street_*)
     *           ↳ legacy `address` column only when NO structured parts
     *             produced anything
     *           ↳ title as last resort.
     *
     * Build 7 fix — the legacy `address` column on many older rows is a
     * stale pre-concatenation of complex_name + unit_number (e.g.
     * property 909: address="Brock Manor, 17", complex_name="Brock Manor",
     * unit_number="17"). The pre-fix elseif chain appended the legacy
     * `address` whenever street_* was missing, re-adding content the
     * structured branch already supplied. The new chain only falls
     * through to `address` when NO structured part landed in $parts.
     * Adjacent-duplicate guard at the bottom is belt-and-braces for any
     * other overlap pattern (case-insensitive, trimmed).
     */
    public function buildDisplayAddress(): string
    {
        $parts = [];

        if (!empty($this->unit_number)) {
            $parts[] = 'Unit ' . $this->unit_number;
        } elseif (!empty($this->unit_section_block)) {
            // Blank-unit fallback (old-import safety): show the section/block, then
            // floor, so two units in the same complex are less ambiguous when the
            // unit number was never captured. Real stock carries unit_number.
            $parts[] = $this->unit_section_block;
        } elseif (!empty($this->floor_number)) {
            $parts[] = 'Floor ' . $this->floor_number;
        }
        if (!empty($this->complex_name)) {
            $parts[] = $this->complex_name;
        }

        $usedStructuredStreet = false;
        // AT-266 — guarded street line: never prepend the number a second time
        // when street_name already opens with it ("21" + "21 Crown Road" is
        // "21 Crown Road", not "21 21 Crown Road"). Shared with
        // composeAddressFromParts() so every Property address composer agrees.
        if (!empty($this->street_name)) {
            $parts[] = $this->composeStreetLine();
            $usedStructuredStreet = true;
        }

        // Legacy `address` fallback fires ONLY when nothing structural
        // landed in $parts. Unit/complex/street are all considered
        // structural — once any one of them populated $parts, the
        // legacy column would just re-add overlapping content.
        if (empty($parts) && !empty($this->address)) {
            $parts[] = $this->address;
        }

        if (!empty($this->suburb)) {
            $parts[] = $this->suburb;
        }

        if (!empty($this->city) && strtolower($this->city) !== strtolower($this->suburb ?? '')) {
            $parts[] = $this->city;
        }

        if (empty($parts)) {
            return $this->title ?? 'Unknown Property';
        }

        // Belt-and-braces — collapse adjacent duplicates after trimming
        // + case-folding. Guards against any future pattern that lands
        // two equivalent parts side-by-side.
        $cleaned = [];
        foreach ($parts as $piece) {
            $piece = trim((string) $piece);
            if ($piece === '') continue;
            if (!empty($cleaned) && mb_strtolower(end($cleaned)) === mb_strtolower($piece)) {
                continue;
            }
            $cleaned[] = $piece;
        }

        return implode(', ', $cleaned);
    }

    /**
     * AT-266 — the ONE truth for `properties.address`.
     *
     * `address` is a DERIVED display string, composed from the structured address
     * columns. It is not an independent fact and must never be edited on its own.
     *
     * Before this, `address` and the structured columns were two free-floating
     * copies of the same fact with nothing reconciling them: the P24 import wrote
     * both consistently, the edit modal then let an agent rewrite the structured
     * columns while `address` sat frozen as a hidden passthrough, and the two
     * drifted. On 74 live properties they disagree; on 17 of those the disagreement
     * was bad enough to pitch a seller an address their own agent never typed.
     *
     * The direction — structured → address — is the one every existing convention
     * already points at: PropertyObserver::saving() derives title_type from
     * property_type the same way; P24ListingsCsvParser derives address from the
     * street columns; buildDisplayAddress() treats the structured parts as primary
     * and the legacy `address` as a last-resort fallback; and the Internal Address
     * modal already exposes the structured fields as the editable ones.
     *
     * Scheme identity leads (a sectional unit is "Unit 6, Arista, 40 Bulwer
     * Street"), then the street. Deliberately NO suburb/city — those live in their
     * own columns, `address` has always been the property line alone, and adding
     * them would silently rewrite what 4,679 correct rows say.
     *
     * Returns '' when no structured part is set — the caller keeps the existing
     * value rather than blanking a row we know nothing better about.
     */
    public function composeAddressFromParts(): string
    {
        $unit = trim((string) ($this->unit_number ?? '')) !== ''
            ? 'Unit ' . trim((string) $this->unit_number)
            : (trim((string) ($this->unit_section_block ?? '')) !== ''
                ? trim((string) $this->unit_section_block)
                : null);

        $street = $this->composeStreetLine();

        $parts = array_filter([
            $unit,
            trim((string) ($this->complex_name ?? '')) !== '' ? trim((string) $this->complex_name) : null,
            $street !== '' ? $street : null,
        ]);

        // Collapse adjacent duplicates (a complex named in both the complex column
        // and the street line reads once, not twice).
        $cleaned = [];
        foreach ($parts as $piece) {
            if (!empty($cleaned) && mb_strtolower(end($cleaned)) === mb_strtolower($piece)) {
                continue;
            }
            $cleaned[] = $piece;
        }

        return implode(', ', $cleaned);
    }

    /**
     * AT-266 — the ONE guarded street line, shared by every Property address
     * composer (buildDisplayAddress + composeAddressFromParts, which in turn
     * feeds the derived `address` column via PropertyObserver::saving()).
     *
     * "street_number street_name" — but NEVER prepend the number when the name
     * already opens with it as a whole token. Machine-written parts (P24 import,
     * parsers) sometimes carry the number in BOTH columns; the naive concat then
     * produced "21 21 Crown Road" / "16 16 Lilliecrona Boulevard", and because
     * `address` is derived from this composer that junk reached the seller-outreach
     * merge field. Mirrors OutreachAddress::composeStreetFromColumns() exactly so
     * the two never diverge again. Clean rows are unchanged — the guard only fires
     * when the name already starts with the number.
     */
    public function composeStreetLine(): string
    {
        $number = trim((string) ($this->street_number ?? ''));
        $name   = trim((string) ($this->street_name ?? ''));

        if ($name === '') {
            return $number;
        }
        if ($number === '' || preg_match('/^' . preg_quote($number, '/') . '(?![0-9A-Za-z])/u', $name)) {
            return $name;
        }

        return $number . ' ' . $name;
    }

    // ── Scopes ──

    /**
     * Scope: search across all address-related fields.
     */
    public function scopeSearchAddress($query, string $term)
    {
        // Multi-term AND across all address fields: EACH whitespace-separated token
        // must match SOME field, so "23 sherwood" / "unit 23 sherwood" narrows to
        // the right unit (23 hits unit_number/street_number, sherwood hits
        // complex_name) instead of returning everything matching either word. A
        // single token degrades to the original OR-across-fields behaviour. This is
        // the ONE canonical property search — every picker calls it (fix-the-class).
        $tokens = preg_split('/\s+/', trim($term), -1, PREG_SPLIT_NO_EMPTY);
        if (empty($tokens)) {
            return $query;
        }

        foreach ($tokens as $token) {
            $query->where(function ($q) use ($token) {
                $like = "%{$token}%";
                $q->where('address', 'like', $like)
                  ->orWhere('street_name', 'like', $like)
                  ->orWhere('street_number', 'like', $like)
                  ->orWhere('title', 'like', $like)
                  ->orWhere('suburb', 'like', $like)
                  ->orWhere('city', 'like', $like)
                  ->orWhere('complex_name', 'like', $like)
                  ->orWhere('unit_number', 'like', $like)
                  ->orWhere('unit_section_block', 'like', $like)
                  ->orWhere('property_number', 'like', $like)
                  ->orWhere('p24_ref', 'like', $like);
            });
        }

        return $query;
    }

    /**
     * The listing is CONCLUDED — the deal is done and it must never be advertised
     * as available again. Sale side: sold/transferred. Rental side: rented/let_out
     * (the rental equivalent of "sold", and the pair everyone forgets).
     */
    private const CONCLUDED_STATUSES = ['sold', 'transferred', 'rented', 'let_out'];

    /** Off-market, but not concluded — withdrawn, expired, never published, etc. */
    private const INACTIVE_STATUSES = ['withdrawn', 'cancelled', 'expired', 'unavailable', 'archived', 'draft'];

    /**
     * THE single source of truth for reading `status`. ALWAYS compare against this,
     * never against the raw attribute.
     *
     * `properties.status` is NOT normalised on write and is genuinely mixed-case in
     * production: the wizard writes lowercase ('active', 'withdrawn'), while the P24
     * sync writes capitalised labels ('Active' — 444 rows, 'Sold' — 60, 'Rented').
     * A case-sensitive `in_array($status, ['sold', …], true)` therefore MISSES every
     * 'Sold' row and falls through to the default arm — which is how 60 SOLD
     * properties came to be badged "For Sale" on the pickers and "FOR SALE" on
     * generated ad cards. Same bug-class as [[isRental]] and the same cure: tolerate
     * the vocabulary in one place so no caller has to know it varies.
     */
    public function normalizedStatus(): string
    {
        return strtolower(trim((string) $this->status));
    }

    /** A concluded listing (sold / transferred / rented / let out). */
    public function isConcluded(): bool
    {
        return in_array($this->normalizedStatus(), self::CONCLUDED_STATUSES, true);
    }

    /**
     * Honest, picker-facing status label (For Sale / Sold / Under Offer / To Let /
     * Withdrawn / Expired …). Distinct from the marketing-card badge — pickers want
     * the real lifecycle state so an agent can tell a live listing from a dead one.
     */
    public function statusBadge(): string
    {
        $status = $this->normalizedStatus();

        return match (true) {
            in_array($status, ['sold', 'transferred'], true) => 'Sold',
            $status === 'under_offer'                        => 'Under Offer',
            // A concluded rental reads "Rented" / "Let Out" — never "To Let", which
            // would advertise a tenanted property as available.
            in_array($status, ['rented', 'let_out'], true)   => ucwords(str_replace('_', ' ', $status)),
            in_array($status, self::INACTIVE_STATUSES, true) => ucwords(str_replace('_', ' ', $status)),
            $this->isRental()                                => 'To Let',
            default => 'For Sale',
        };
    }

    /**
     * THE canonical property-picker result row. Every search/typeahead surface maps
     * its results through this so the shape (full address label + listing agent +
     * status) can never drift. $extra merges surface-specific fields (price, ref,
     * seller, fees …) without re-implementing the core. Eager-load `agent` to avoid
     * N+1. Fix-the-class companion to scopeSearchAddress().
     */
    public function toSearchResult(array $extra = []): array
    {
        return array_merge([
            'id'     => $this->id,
            'label'  => $this->buildDisplayAddress(),
            'agent'  => $this->agent?->name,
            'status' => $this->statusBadge(),
        ], $extra);
    }

    /**
     * AT-50 — a property is "transaction-live" (its owner/seller is in an active
     * business relationship that must keep receiving comms) when EITHER:
     *
     *   (b) LIVE MANDATE — expiry_date IS NULL OR expiry_date >= today, AND the
     *       status is not a concluded/dead one. We test expiry_date DIRECTLY
     *       against today rather than trusting status='expired' (the expiry cron
     *       flips status only once a day, so it can be stale). Status comparison
     *       is case-insensitive because the stored values are inconsistent
     *       (e.g. 'Sold' vs 'sold' — see the AT-50 investigation).
     *
     *   (c) CURRENTLY ADVERTISED — any syndication channel is active, including
     *       the agency's OWN website (property_website_syndication) per Johan's
     *       call: P24, Private Property, or own-website all count.
     *
     * Single source of truth for the live-mandate-OR-advertised predicate; the
     * caller is responsible for agency isolation (BelongsToAgency when run as the
     * agency user, or an explicit agency_id filter on public/unauthenticated
     * routes where the global scope no-ops).
     */
    public function scopeTransactionLive($query)
    {
        $dead = ['expired', 'sold', 'withdrawn', 'cancelled'];

        return $query->where(function ($outer) use ($dead) {
            // (b) live mandate
            $outer->where(function ($m) use ($dead) {
                $m->where(function ($e) {
                    $e->whereNull('expiry_date')
                      ->orWhereDate('expiry_date', '>=', now()->toDateString());
                })
                  // whereNotIn() with a DB::raw() first arg binds the expression as
                  // a VALUE, not a column — it never lowercases `status`, so dead
                  // listings (e.g. 'Sold') leaked into transaction-live. Use a
                  // parameterised raw NOT IN so the LOWER(status) is a real column expr.
                  ->whereRaw('LOWER(status) NOT IN (?, ?, ?, ?)', $dead);
            })
            // (c) currently advertised (P24 / PP / own website)
            ->orWhereRaw('LOWER(p24_syndication_status) = ?', ['active'])
            ->orWhereRaw('LOWER(pp_syndication_status) = ?', ['active'])
            ->orWhereExists(function ($sub) {
                $sub->select(\Illuminate\Support\Facades\DB::raw(1))
                    ->from('property_website_syndication as pws')
                    ->whereColumn('pws.property_id', 'properties.id')
                    ->whereRaw('LOWER(pws.status) = ?', ['active']);
            });
        });
    }

    public function scopeVisibleTo($query, \App\Models\User $user)
    {
        $scope = \App\Services\PermissionService::getDataScope($user, 'properties');

        if ($scope === 'all') return $query;
        if ($scope === 'branch') return $query->where('branch_id', $user->effectiveBranchId());
        if ($scope === 'own') return $query->where('agent_id', $user->id);

        return $query->whereRaw('1 = 0');
    }

    public function isPublished(): bool
    {
        return $this->published_at !== null;
    }

    /**
     * Is this listing currently advertised on ANY syndication portal — the
     * agency's own website, Property24, or Private Property?
     *
     * This, not isPublished(), is what "Live" means to an agent. `published_at`
     * is the legacy HFC-Premium publish flag, written only by the publish
     * checkbox and the publish/unpublish action; NO syndication path touches it
     * (verified: `published_at` appears nowhere in the syndication controllers
     * or services). A listing can therefore be live on all three portals with a
     * null `published_at`, and vice versa.
     *
     * Derived from portalLinks() so there is one definition of "live on a
     * portal" and the badge can never disagree with the syndication panel.
     * Free of queries when `websiteSyndication` is eager-loaded.
     */
    public function isLiveOnAnyPortal(): bool
    {
        foreach ($this->portalLinks() as $link) {
            if ($link['status'] === 'live') {
                return true;
            }
        }

        return false;
    }

    /**
     * SQL twin of isLiveOnAnyPortal() — same three portals, same gates, so the
     * "Live" KPI tile and its filter count exactly the cards that wear the
     * badge. Keep in lockstep with portalLinks()/buildP24Url()/buildPpUrl().
     */
    public function scopeLiveOnAnyPortal($query)
    {
        $ppOffMarket = ['deactivated', 'disabled', 'archived', 'removed', 'expired'];

        return $query->where(function ($outer) use ($ppOffMarket) {
            // Own website — the pivot row is enabled for at least one site.
            $outer->whereExists(function ($sub) {
                $sub->select(\Illuminate\Support\Facades\DB::raw(1))
                    ->from('property_website_syndication as pws')
                    ->whereColumn('pws.property_id', 'properties.id')
                    ->whereNull('pws.deleted_at')
                    ->where('pws.enabled', true);
            })
            // Property24 — switched ON, with a reference and an active status.
            // The `enabled` gate is what makes a disabled listing stop counting:
            // its status column keeps its stale 'active' value. See portalLinks().
            ->orWhere(function ($p24) {
                $p24->where('p24_syndication_enabled', true)
                    ->whereNotNull('p24_ref')
                    ->where('p24_ref', '!=', '')
                    ->where('p24_syndication_status', 'active');
            })
            // Private Property — switched ON, with a reference. The ref is the
            // durable live signal; the status flaps on every routine re-push, so
            // only an off-market status kills it.
            ->orWhere(function ($pp) use ($ppOffMarket) {
                $pp->where('pp_syndication_enabled', true)
                   ->whereNotNull('pp_ref')
                   ->where('pp_ref', '!=', '')
                   ->where(function ($s) use ($ppOffMarket) {
                       $s->whereNull('pp_syndication_status')
                         ->orWhereNotIn('pp_syndication_status', $ppOffMarket);
                   });
            });
        });
    }

    /**
     * The portals this listing is live on, by label. Drives the Live badge's
     * tooltip so the agent sees WHERE it is live without opening the panel.
     *
     * @return string[]
     */
    public function livePortalLabels(): array
    {
        return array_values(array_map(
            static fn (array $l) => $l['label'],
            array_filter($this->portalLinks(), static fn (array $l) => $l['status'] === 'live'),
        ));
    }

    /**
     * Cosmetic/SEO slug for the public website — the title run through the
     * exact same transform as Laravel's Str::slug() (lowercase, accents
     * stripped, every run of non-alphanumeric characters collapsed to a
     * single hyphen, leading/trailing hyphens trimmed). Empty string when the
     * property has no title.
     *
     * The slug is purely cosmetic: the website resolves a property by the
     * trailing id in its public URL, so the title may change without breaking
     * any link. See getPublicUrlAttribute().
     */
    public function getSlugAttribute(): string
    {
        return Str::slug((string) ($this->title ?? ''));
    }

    /**
     * Canonical public-website URL for this listing:
     *   {base}/property/{slug}-{id}      (titled listing)
     *   {base}/property/{id}             (no title — bare id fallback)
     *
     * Base URL lives in config('integrations.public_website_url') — never
     * hardcode it. Resolution on the website is by the trailing id, so the
     * slug segment is SEO-only and a changing title never breaks the link.
     */
    public function getPublicUrlAttribute(): string
    {
        $base = rtrim((string) config('integrations.public_website_url'), '/');
        $slug = $this->slug;
        $path = $slug !== '' ? "{$slug}-{$this->id}" : (string) $this->id;

        return "{$base}/property/{$path}";
    }

    /**
     * THE single source of truth for "is this listing a rental?". Every surface
     * that renders, prices, or labels a listing asks this — never `listing_type
     * === 'rental'` inline.
     *
     * It is deliberately case-insensitive and accepts the whole vocabulary,
     * because the column is NOT normalised on write: the P24 CSV importer
     * (P24ListingsCsvParser) stores capitalised 'Rental'/'Sale', the UI form
     * stores lowercase 'sale'/'rental', and the public website API has long
     * accepted 'to_let'/'to-let'/'lease'. Case-sensitive checks against
     * 'rental' therefore MISS importer-created rentals and silently render them
     * as sales — which is exactly how a rental came to be advertised "For Sale"
     * on the live preview page. Tolerate the vocabulary in one place so no
     * caller has to know it exists.
     */
    public function isRental(): bool
    {
        return in_array(
            strtolower(trim((string) $this->listing_type)),
            ['rental', 'to_let', 'to-let', 'lease'],
            true,
        );
    }

    /**
     * The single source of truth for a listing's price across display,
     * syndication payloads, and readiness gates. Rentals carry the amount in
     * `rental_amount` (the sale `price` column is 0/null on a rental); sales use
     * `price`. EVERY price consumer (formattedPrice, the P24 + PP mappers, the
     * readiness checks) reads this so they can never diverge — a rental never
     * needs the sale-price field filled manually.
     */
    public function effectivePrice(): float
    {
        return $this->isRental()
            ? (float) ($this->rental_amount ?? 0)
            : (float) ($this->price ?? 0);
    }

    public function formattedPrice(): string
    {
        return 'R ' . number_format((int) $this->effectivePrice(), 0, '.', ' ');
    }

    /**
     * Normalised rental inspection galleries. The `rental_images_json` column is
     * null until the first save, so this returns the canonical default shape
     * (empty in/out/custom) and back-fills any missing keys/sub-keys on partial
     * data. The controller and the property show view both read through this so
     * they never have to defend against missing keys.
     * Spec: .ai/specs/rental-images.md
     */
    public function rentalImagesStructure(): array
    {
        $raw = $this->rental_images_json;

        if (is_string($raw)) {
            $raw = json_decode($raw, true);
        }
        if (!is_array($raw)) {
            $raw = [];
        }

        $section = function ($value): array {
            $value = is_array($value) ? $value : [];

            return [
                'date'   => $value['date'] ?? null,
                'images' => array_values(array_filter(
                    is_array($value['images'] ?? null) ? $value['images'] : [],
                    'is_string'
                )),
            ];
        };

        $custom = [];
        foreach (is_array($raw['custom'] ?? null) ? $raw['custom'] : [] as $sec) {
            if (!is_array($sec) || !isset($sec['id'])) {
                continue;
            }
            $custom[] = array_merge(
                $section($sec),
                ['id' => (string) $sec['id'], 'name' => (string) ($sec['name'] ?? '')]
            );
        }

        return [
            'in_inspection'  => $section($raw['in_inspection'] ?? null),
            'out_inspection' => $section($raw['out_inspection'] ?? null),
            'custom'         => $custom,
        ];
    }

    /**
     * Whether the rental inspection galleries (in/out/custom) are available for
     * this property. Single source of truth for the mobile `rental_inspections_available`
     * flag (exposed on both the show + overview payloads) AND the server-side gate
     * in MobileRentalImagesController: rental-only AND live-only. The mobile app
     * trusts this flag blindly, so it is computed here and nowhere else.
     * Spec: .ai/specs/rental-images.md
     */
    public function rentalInspectionsAvailable(): bool
    {
        return strtolower((string) $this->listing_type) === 'rental' && $this->isOnMarket();
    }

    /**
     * Phase A.2.1 — public-facing ad URLs across the portals we syndicate to.
     * Returns one slot per portal; null when that portal isn't currently
     * activated or doesn't have a working URL pattern.
     *
     * URL composition lives here (single source of truth) — see the legacy
     * inline Alpine helpers in resources/views/corex/properties/show.blade.php
     * which used to compute these client-side. Map "Open listing →" and any
     * future "View on portal" CTA pull from this accessor.
     *
     * @return array{p24:?string, pp:?string, hfc:?string}
     */
    public function publicListingUrls(): array
    {
        return [
            'p24' => $this->buildP24Url(),
            'pp'  => $this->buildPpUrl(),
            // The company-website URL is the same canonical public_url the
            // "View on website" button uses — single source of truth. The live
            // site resolves a listing by the trailing CoreX id under
            // /property/{slug}-{id}; the old /listing/{ref}/… pattern 404s.
            'hfc' => $this->isOnHfcWebsite() ? $this->public_url : null,
        ];
    }

    /**
     * PLACEHOLDER (A.2.3 Item 4) — until the HFC website integration writes
     * back a per-listing syndication status, assume any active mandate for
     * agency_id=1 is published on hfcoastal.co.za.
     *
     * TODO post-PropCon takeover: replace with an
     * `hfc_website_syndication_status === 'active'` check on the model.
     */
    public function isOnHfcWebsite(): bool
    {
        return $this->status === 'active' && (int) $this->agency_id === 1;
    }

    /**
     * Pick the best public URL for "Open listing" actions. Priority:
     * P24 active > PP active > company website > null.
     */
    public function preferredPublicListingUrl(): ?string
    {
        $urls = $this->publicListingUrls();
        return $urls['p24'] ?? $urls['pp'] ?? $urls['hfc'] ?? null;
    }

    /**
     * P24 slug-composed direct listing URL. Returns null unless we have an
     * activated p24_ref. Sandbox vs production picked from p24_syndication_status
     * to stay consistent with the legacy inline JS — in-flight states (submitted,
     * pending) don't yet point at a live page on P24. 'sold' / 'rented' listings
     * DO have a live page: P24 keeps terminal-but-not-removed stock on the portal.
     */
    private function buildP24Url(): ?string
    {
        $onPortal = array_merge(['active'], self::P24_ON_PORTAL_TERMINAL_STATUSES);

        if (empty($this->p24_ref) || ! in_array((string) $this->p24_syndication_status, $onPortal, true)) {
            return null;
        }
        $slugify = static function (?string $s): string {
            $s = (string) ($s ?? '');
            $s = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $s) ?? '');
            return trim($s, '-') ?: 'property';
        };
        $section = $this->isRental() ? 'to-rent' : 'for-sale';
        $domain  = 'www.property24.com';
        return sprintf(
            'https://%s/%s/%s/%s/%s/%s/%s',
            $domain,
            $section,
            $slugify($this->suburb),
            $slugify($this->city),
            $slugify($this->province),
            // P24 suburb id segment — must be the P24 id, not PP's. (The
            // listing resolves by the trailing p24_ref regardless, but the
            // segment should still be correct.)
            $this->p24_suburb_id ?? '0',
            $this->p24_ref,
        );
    }

    /**
     * Compose the public Private Property listing URL. Pattern (live):
     *   https://www.privateproperty.co.za/{section}/{province}/{city}/{suburb}/{ref}
     *
     * PP doesn't return a listing URL from syndication, but it resolves a
     * listing purely by the trailing reference — the slug segments are
     * decorative SEO and PP redirects to the canonical URL regardless
     * (verified: a deliberately wrong province/city/suburb still served the
     * right listing). The old `/search?q=<ref>` hop now 404s ("This space is
     * no longer occupied"), so we build the SEO path and let the ref resolve.
     * We omit PP's region tier (kzn-south-coast) — we don't store PP's region
     * taxonomy and PP backfills it on redirect.
     *
     * Returns null unless PP has assigned this listing a reference.
     *
     * Gate on pp_ref presence, NOT on pp_syndication_status === 'active': PP
     * only issues a pp_ref once the listing is published, so the ref is the
     * durable "live on PP" signal. The status flag, by contrast, flaps —
     * submitListing() resets it to 'submitted' on every routine re-push, and the
     * activation-sync job only reconciles rows where pp_ref IS NULL, so a
     * re-pushed listing stays stuck at 'submitted' and never returns to
     * 'active'. Tying the public link to that flag made "View on PP" dead (href
     * '#', reopening the CoreX page) for every listing that had ever been
     * re-pushed. We still suppress the link once the listing is explicitly
     * taken off-market (deactivated).
     */
    private function buildPpUrl(): ?string
    {
        $offMarket = ['deactivated', 'disabled', 'archived', 'removed', 'expired'];
        if (empty($this->pp_ref) || in_array($this->pp_syndication_status, $offMarket, true)) {
            return null;
        }
        $slugify = static function (?string $s): string {
            $s = strtolower(preg_replace('/[^a-z0-9]+/i', '-', (string) ($s ?? '')) ?? '');
            return trim($s, '-') ?: 'property';
        };
        $section = $this->isRental() ? 'to-rent' : 'for-sale';
        return sprintf(
            'https://www.privateproperty.co.za/%s/%s/%s/%s/%s',
            $section,
            $slugify($this->province),
            $slugify($this->city ?? $this->town),
            $slugify($this->suburb),
            rawurlencode((string) $this->pp_ref),
        );
    }

    /**
     * Canonical, extensible list of public portal links for this listing.
     *
     * This is the SINGLE source of truth for "where can the public see this
     * listing" — consumed by the web "Open listing" CTAs and by the mobile
     * app's property Overview screen. Each entry is normalised to a fixed
     * shape so any client renders any portal — including future ones —
     * without code changes:
     *
     *   [
     *     'portal' => 'property24',     // stable machine key
     *     'label'  => 'Property24',     // human label
     *     'status' => 'live'|'not_published',
     *     'url'    => 'https://…'|null, // present only when it resolves live
     *     'ref'    => '…'|null,         // the portal's listing reference
     *   ]
     *
     * Adding a portal here makes it appear everywhere (web + mobile) at once —
     * that is the whole point. "Any other portal that comes along" plugs in
     * by adding one block below.
     *
     * @return array<int, array{portal:string,label:string,status:string,url:?string,ref:?string}>
     */
    public function portalLinks(): array
    {
        $links = [];

        // ── Company website ───────────────────────────────────────
        // Live when the listing is enabled on at least one agency website
        // (the property_website_syndication pivot — same check the mobile
        // Overview placement used). The public URL is composed by the
        // config-driven public_url accessor (never hardcoded).
        // Eager-loaded on list screens (many properties per page) so the check
        // costs one query for the page rather than one per property.
        $websiteLive = $this->relationLoaded('websiteSyndication')
            ? $this->websiteSyndication->contains(fn ($row) => (bool) $row->enabled)
            : \App\Models\PropertyWebsiteSyndication::withoutGlobalScope(\App\Models\Scopes\AgencyScope::class)
                ->where('property_id', $this->id)
                ->where('enabled', true)
                ->exists();
        $links[] = [
            'portal' => 'website',
            'label'  => 'Company Website',
            'status' => $websiteLive ? 'live' : 'not_published',
            'url'    => $websiteLive ? $this->public_url : null,
            'ref'    => $this->external_id,
        ];

        // ── Property24 ─────────────────────────────────────────────
        // The `enabled` switch is authoritative, not the status column. Turning
        // a portal off leaves `*_syndication_status` at its last value — the
        // deactivate call updates it only on success, and legacy rows never had
        // it cleared — so a disabled listing routinely still reads 'active'.
        // Trusting the status alone marked sold, fully-unsyndicated listings as
        // live. A portal is live only when the agency has it switched ON *and*
        // the portal has confirmed the listing.
        $p24Url  = $this->buildP24Url();
        $p24Live = $p24Url !== null && (bool) $this->p24_syndication_enabled;
        $links[] = [
            'portal' => 'property24',
            'label'  => 'Property24',
            'status' => $p24Live ? 'live' : 'not_published',
            'url'    => $p24Live ? $p24Url : null,
            'ref'    => $this->p24_ref,
        ];

        // ── Private Property ───────────────────────────────────────
        $ppUrl  = $this->buildPpUrl();
        $ppLive = $ppUrl !== null && (bool) $this->pp_syndication_enabled;
        $links[] = [
            'portal' => 'private_property',
            'label'  => 'Private Property',
            'status' => $ppLive ? 'live' : 'not_published',
            'url'    => $ppLive ? $ppUrl : null,
            'ref'    => $this->pp_ref,
        ];

        return $links;
    }

    /**
     * The list of gallery tags currently available on this property.
     *
     * Tags are derived from the property's `spaces_json` (preferred) or
     * the legacy beds/baths/garages columns. ONLY spaces the user has
     * actually added (count >= 1) produce tags — no hardcoded defaults.
     *
     * Used by:
     *   - Web gallery tagger (resources/views/corex/properties/show.blade.php)
     *   - Mobile API (App\Http\Controllers\Api\MobilePropertyController)
     *
     * @return string[]
     */
    public function getAvailableGalleryTags(): array
    {
        $tags = $this->derivedGalleryTags();

        // Append every tag that exists BEYOND the derived room set, case-
        // insensitively de-duped against what we already have. Two sources:
        //
        //   1. gallery_custom_tags — the explicit custom-tag registry (mobile
        //      add/remove endpoints keep it; the web sorter does NOT write it).
        //   2. category names already in use in gallery_categories_json — tags
        //      the agent created in the web gallery sorter and FILED PHOTOS
        //      under. That save path persists the names ONLY inside
        //      gallery_categories_json, never into gallery_custom_tags, so
        //      before this a custom tag with photos silently vanished from the
        //      tag library on reload (property 6060: "View", "Store room", …
        //      had photos but were gone from the list). A tag that has images
        //      filed under it MUST appear in the list — deriving the list from
        //      in-use categories makes it self-consistent regardless of which
        //      save path wrote them.
        $appendIfNew = function (?string $name) use (&$tags): void {
            if (!is_string($name)) return;
            $name = trim($name);
            if ($name === '') return;
            foreach ($tags as $t) {
                if (strcasecmp($t, $name) === 0) return;
            }
            $tags[] = $name;
        };

        foreach (($this->gallery_custom_tags ?? []) as $custom) {
            $appendIfNew($custom);
        }

        foreach (($this->gallery_categories_json['categories'] ?? []) as $cat) {
            $appendIfNew($cat['name'] ?? null);
        }

        return $tags;
    }

    /**
     * The gallery tags DERIVED from the property's rooms — `spaces_json`
     * (preferred) or the legacy beds/baths/garages columns. ONLY spaces the
     * user has actually added (count >= 1) produce tags. This is the room-based
     * baseline; custom tags are layered on top by getAvailableGalleryTags().
     * Kept separate so the reorder-save path can tell custom tags from derived
     * ones when persisting the registry.
     *
     * @return string[]
     */
    public function derivedGalleryTags(): array
    {
        $allowed = ['Bedroom','Bathroom','Kitchen','Lounge','Dining Room','Study','Patio','Garden','Pool','Flatlet','Garage'];

        // Prefer spaces_json — it's the canonical source after the
        // user has touched the Spaces editor.
        $spacesData = $this->spaces_json ?? [];
        $spacesList = $spacesData['spaces'] ?? [];
        if (empty($spacesList) && !empty($spacesData) && isset($spacesData[0]['type'])) {
            $spacesList = $spacesData; // legacy flat shape
        }

        $tags = [];

        if (!empty($spacesList)) {
            foreach ($spacesList as $sp) {
                $type  = $sp['type'] ?? '';
                $count = (int) ($sp['count'] ?? 0);
                if ($count < 1 || !in_array($type, $allowed, true)) continue;

                if ($count > 1) {
                    for ($i = 1; $i <= $count; $i++) $tags[] = $type . ' ' . $i;
                } else {
                    $tags[] = $type;
                }
            }
        } else {
            // Fallback: derive from legacy columns
            for ($i = 1; $i <= (int) ($this->beds ?? 0); $i++)  $tags[] = 'Bedroom ' . $i;
            for ($i = 1; $i <= (int) ($this->baths ?? 0); $i++) $tags[] = 'Bathroom ' . $i;
            if ((int) ($this->garages ?? 0) > 0) $tags[] = 'Garage';
        }

        return $tags;
    }

    /**
     * All images flattened into one array for convenience.
     *
     * De-duplicated on purpose: gallery_images_json and images_json
     * intentionally hold the SAME ordered set (internal UI reads gallery,
     * the public website / mobile API / readiness read images_json), so a
     * naive merge double-counts every photo. That doubling previously pushed
     * duplicate images into the Property24 payload (buildPhotos slices the
     * first 30 of this list) and inflated every photo count. array_filter
     * drops empty slots; array_unique keeps the first occurrence so order is
     * preserved.
     */
    public function allImages(): array
    {
        return array_values(array_unique(array_filter(array_merge(
            $this->dawn_images_json    ?? [],
            $this->noon_images_json    ?? [],
            $this->dusk_images_json    ?? [],
            $this->gallery_images_json ?? [],
            $this->images_json         ?? [],
        ))));
    }

    /**
     * Map one of this property's full-resolution image URLs to the small web
     * thumbnail used by LIST surfaces (grid/table cards, match tiles, contact
     * property lists). Falls back to the original URL whenever a thumbnail
     * hasn't been generated yet, so nothing breaks before/during a backfill.
     * The property page, brochures and portal feeds keep using the full image.
     *
     * @see \App\Services\Images\PropertyThumbnailService
     */
    public function thumbFor(?string $imageUrl): ?string
    {
        if ($imageUrl === null || $imageUrl === '') {
            return $imageUrl;
        }

        return app(\App\Services\Images\PropertyThumbnailService::class)->displayUrl($imageUrl);
    }

    /**
     * The exact image set the agent sees in the property gallery UI
     * (`gallery_images_json` — the tag-based gallery on the property page).
     * This is the single source of truth for outbound syndication photos:
     * what we send to a portal must equal what the user curated and sees.
     *
     * allImages() is deliberately NOT used here — it also merges images_json
     * (a divergent public/website mirror) and the dawn/noon/dusk variant sets,
     * which over-counts photos the gallery never showed (e.g. property #1322:
     * gallery 45 vs allImages 68). Falls back to allImages() ONLY when the
     * gallery is empty, so a property whose photos live solely in a legacy
     * column never silently syndicates zero images.
     *
     * @return string[]
     */
    public function syndicationImages(): array
    {
        $gallery = array_values(array_unique(array_filter(
            (array) ($this->gallery_images_json ?? [])
        )));

        return !empty($gallery) ? $gallery : $this->allImages();
    }

    /**
     * The syndication gallery minus any CoreX-hosted photo whose file is not on
     * disk. Externally-hosted images (portal mirrors) are kept — we cannot stat
     * another host.
     *
     * PrivateProperty downloads every photo BY URL and rejects the ENTIRE
     * UpdateListing when one 404s (PP120), so a dangling reference silently
     * blocks all further updates of that listing. Publishing only what we can
     * actually serve means a bad reference costs one photo, never the listing.
     *
     * @return string[]
     */
    public function servableSyndicationImages(): array
    {
        return array_values(array_filter(
            $this->syndicationImages(),
            fn ($url) => !\App\Services\Images\PropertyImageGuard::isLocal($url)
                || \App\Services\Images\PropertyImageGuard::existsOnDisk($url)
        ));
    }

    /**
     * True when this property has photos on paper but none we can actually
     * serve. Such a listing must NOT be pushed to a portal: it would submit an
     * empty photo set, which can clear the images on the live portal listing.
     * Refuse and surface it instead.
     */
    public function hasGalleryButNothingServable(): bool
    {
        return !empty($this->syndicationImages()) && empty($this->servableSyndicationImages());
    }

    /**
     * Fingerprint of the gallery AS THE BROWSER LAST SAW IT. Handed to the page
     * at render and echoed back on save, so the server can tell a save built on
     * the current gallery from one built on a stale copy.
     *
     * Why this exists: the gallery save posts the client's ENTIRE image array as
     * the new truth. Two tabs open on the same property means last-write-wins —
     * the older tab silently reverts anything the newer one did. That is how the
     * property 6060 dangling reference was created: a tab loaded before a photo
     * rotation re-posted its pre-rotation array, resurrecting the URL of the file
     * the rotation had already deleted, and PrivateProperty then 404'd on it.
     *
     * Compare with `===` against the value the client sends; a mismatch means
     * "your copy is out of date" and the save must be refused, not merged.
     */
    public function galleryFingerprint(): string
    {
        return sha1(json_encode([
            $this->gallery_images_json ?? [],
            $this->gallery_categories_json ?? [],
        ]));
    }

    /**
     * Cheap fingerprint of the image set that goes to a portal (the ordered
     * syndication gallery + its caption/category map). Path-list based — NO file
     * reads — so it is safe to call on every submit. Changes when an image is
     * added, deleted, reordered, or recaptioned. Compared against the stored
     * `p24_image_signature` so a P24 re-submit only re-uploads photos when the
     * gallery actually changed (otherwise it sends `photos: null` and P24 keeps
     * the existing set — the swagger-recommended path). See AT-P24.
     */
    public function p24ImageSignature(): string
    {
        return md5(json_encode([
            $this->syndicationImages(),
            $this->gallery_categories_json,
        ]));
    }

    /**
     * The variable set the `_ad-templates` Blade partial expects, derived from
     * adData(). Lets any caller (the single-property ad page AND the bulk Ad
     * Manager) server-render a pre-built template for this property from one
     * source of truth.
     *
     * @return array<string,mixed>
     */
    /**
     * One selectable "ad agent" as the client-side selector consumes it.
     * Used by the Ad Manager generator to let the user swap whose details
     * appear on an ad (the listing agent, the co-listing agent, "me", or any
     * agent in the user's data scope) — see ad-manager.md §"Agent identity".
     * Keys mirror the agent_* keys of adData() so the JS swap stays in lock-step.
     */
    public static function agentAdCard(?User $agent): array
    {
        $name = (string) ($agent?->name ?? '');

        return [
            'id'          => (int) ($agent?->id ?? 0),
            'name'        => $name,
            'email'       => (string) ($agent?->email ?? ''),
            // Mobile lives in `cell` (landline `phone` fallback) — same rule as adData().
            'phone'       => (string) ($agent?->cell ?: $agent?->phone ?: ''),
            'designation' => (string) ($agent?->designation ?: 'Property Practitioner'),
            'initial'     => strtoupper(mb_substr($name !== '' ? $name : 'A', 0, 1)),
            // Host-relative so html2canvas can read it same-origin on any of our
            // domains (see adSafeImageUrl) — the agent swap re-points this in the ad.
            'avatar'      => self::adSafeImageUrl($agent?->profilePhotoUrl()),
        ];
    }

    public function adTemplateVars(): array
    {
        $d = $this->adData();

        return [
            'img1'        => $d['image_1'],
            'img2'        => $d['image_2'],
            'img3'        => $d['image_3'],
            'img4'        => $d['image_4'],
            'img5'        => $d['image_5'],
            'price'       => $d['price'],
            'title'       => $d['title'],
            'suburb'      => $d['suburb'],
            'type'        => $d['property_type'],
            'beds'        => $d['beds'],
            'baths'       => $d['baths'],
            'garages'     => $d['garages'],
            'size'        => $d['size_m2'],
            'initial'     => strtoupper(mb_substr((string) ($this->agent?->name ?? 'A'), 0, 1)),
            'agentName'   => $d['agent_name'],
            'agentEmail'  => $d['agent_email'],
            'agentDesig'  => $d['agent_designation'],
            // Agent 2 (co-listing) — empty unless co-listed. Drives the dual-agent split.
            'agent2Name'    => $d['agent_2_name'],
            'agent2Email'   => $d['agent_2_email'],
            'agent2Desig'   => $d['agent_2_designation'],
            'agent2Initial' => $d['agent_2_initial'],
            'agencyName'  => strtoupper((string) $d['agency_name']),
            'website'     => strtoupper((string) $d['website']),
            'logoUrl'     => $d['logo'],
            'statusBadge' => $d['status_badge'],
        ];
    }

    /**
     * Normalise a stored image URL to one that actually loads in the browser
     * (and that Meta can fetch when publishing). Our public storage is always
     * served at `/storage/...`; stored URLs can carry a stale/localhost host or
     * the wrong scheme (from seeding/import), which then fail on staging/prod.
     * So we re-home any of-our-storage URL onto the CURRENT app host, and leave
     * genuinely external URLs untouched.
     */
    public static function publicImageUrl(?string $u): ?string
    {
        if ($u === null) {
            return null;
        }
        $u = trim($u);
        if ($u === '') {
            return null;
        }

        // Host-relative → absolute on the current host.
        if (str_starts_with($u, '/')) {
            return asset(ltrim($u, '/'));
        }

        // CONSERVATIVE: only re-home URLs baked with a local/dev host (common after
        // copying a dev DB to staging/prod). Every other working absolute URL —
        // staging, prod, a CDN, or an external source — is left exactly as stored,
        // so we never rewrite a URL that already loads.
        $host = strtolower((string) parse_url($u, PHP_URL_HOST));
        if (in_array($host, ['localhost', '127.0.0.1', '0.0.0.0', '::1'], true)) {
            $path = parse_url($u, PHP_URL_PATH) ?: '';
            return $path !== '' ? asset(ltrim($path, '/')) : $u;
        }

        return $u;
    }

    /**
     * Image URL safe for the Ad Manager's client-side html2canvas capture.
     *
     * The exported PNG is rasterised from a canvas, and a canvas can only read
     * pixels from SAME-ORIGIN images. Our images live under /storage/, but they
     * are stored (and asset()-generated) as absolute URLs pinned to APP_URL
     * (corexos.co.za). A user who reaches the app on another live host
     * (corex.hfcoastal.co.za, www.corexos.co.za) therefore loads those images
     * cross-origin — they display in the builder but /storage/ sends no CORS
     * headers, so html2canvas silently drops them from the download (property
     * photo missing while text/shapes remain).
     *
     * Emitting a HOST-RELATIVE path makes the browser load the image from the
     * current origin whichever of our domains the user is on → same-origin →
     * html2canvas reads it. Genuinely external images (not under /storage/) are
     * left absolute (nothing we can re-home).
     *
     * BUT re-homing is only safe when THIS host actually serves the file. On a
     * working-copy environment (e.g. Staging referencing images whose files live
     * on the live host) a host-relative "/storage/…" would 404 — the photos
     * vanish from every ad template while the brochure (absolute URL) still
     * loads. So we re-home ONLY when the file physically exists under this host's
     * public/storage; otherwise we keep the absolute URL so the image still
     * displays (accepting that a cross-origin html2canvas export may drop it —
     * showing the photo beats hiding it, and real exports run on the host that
     * owns the files, where re-homing still applies).
     */
    public static function adSafeImageUrl(?string $u): ?string
    {
        $u = self::publicImageUrl($u);
        if ($u === null) {
            return null;
        }

        $path = parse_url($u, PHP_URL_PATH) ?: '';
        $pos  = strpos($path, '/storage/');
        if ($pos !== false) {
            $rel = substr($path, $pos); // "/storage/…"
            // Fast path: the file IS on this host → serve it host-relative
            // (same-origin, direct from the web server, html2canvas-safe).
            if (is_file(public_path(ltrim($rel, '/')))) {
                return $rel;
            }
            // The file lives on ANOTHER of our hosts (e.g. Staging referencing
            // live-hosted images). A host-relative path would 404 and an absolute
            // cross-origin URL exports BLANK from html2canvas. Route it through
            // the same-origin ad-media proxy so it both displays AND captures.
            // `absolute:false` → root-relative, so it's same-origin on any host.
            return route('corex.properties.ad-media', ['u' => $u], false);
        }

        return $u;
    }

    /**
     * All property images normalised for browser display (Photos picker, ad
     * previews, publishing). See publicImageUrl().
     *
     * @return array<int,string>
     */
    public function displayImages(): array
    {
        return array_values(array_filter(array_map(
            static fn ($u) => static::publicImageUrl($u),
            $this->allImages(),
        )));
    }

    /**
     * Single source of truth for the data the Ad Manager injects into a
     * template — used by both the generator (ad.blade.php) and the
     * property-linked builder live preview (ad-builder.blade.php).
     * Spec: ad-manager.md §3, §7. Keys match the builder field catalogue.
     *
     * Image URLs are stripped to a host-relative path then re-`asset()`ed so
     * html2canvas' crossorigin="anonymous" works regardless of which hostname
     * the app is reached on.
     */
    public function adData(): array
    {
        $imgs = $this->allImages();
        // adSafeImageUrl → host-relative so html2canvas can read them same-origin
        // on any of our live domains (see the method's docblock).
        $img  = fn (int $i) => self::adSafeImageUrl($imgs[$i] ?? null);

        $agent   = $this->agent;
        // Co-listing agent (pp_second_agent_id) — drives the dual-agent ad layouts
        // and the builder's Agent 2 fields. Null/empty keys when single-agent.
        $agent2  = ($this->pp_second_agent_id && (int) $this->pp_second_agent_id !== (int) $this->agent_id)
            ? $this->secondAgent
            : null;
        $branch  = $this->branch;
        $agency  = $this->agency;

        $logoPath = $branch?->logo_path ?: $agency?->logo_path;
        $logoUrl  = $logoPath ? self::adSafeImageUrl(asset('storage/' . $logoPath)) : null;

        $beds    = $this->beds;
        $baths   = $this->baths;
        $garages = $this->garages;
        $size    = $this->size_m2 ? number_format($this->size_m2) . ' M²' : null;

        // Status badge — honest label derived from the listing, never fabricated.
        // NOTE: 'pending' is NOT "under offer". Under the two-tier model Pending is
        // a SUB-LABEL on a For-Sale base (For Sale + Pending banner), so a pending
        // listing is still actively FOR SALE on the marketing card. Only a genuine
        // 'under_offer' base status reads "UNDER OFFER".
        // Read through normalizedStatus(): the raw column is mixed-case (P24 writes
        // 'Sold'), and a case-sensitive compare here put "FOR SALE" on the ad card
        // of 60 SOLD properties.
        $adStatus = $this->normalizedStatus();

        $statusBadge = match (true) {
            in_array($adStatus, ['sold', 'transferred'], true) => 'SOLD',
            // The rental equivalent of SOLD. Without this a tenanted property
            // generates an ad advertising it "TO LET".
            in_array($adStatus, ['rented', 'let_out'], true)   => strtoupper(str_replace('_', ' ', $adStatus)),
            $adStatus === 'under_offer'                        => 'UNDER OFFER',
            $this->isRental()                                  => 'TO LET',
            default                                            => 'FOR SALE',
        };

        return [
            'image_1'           => $img(0),
            'image_2'           => $img(1),
            'image_3'           => $img(2),
            'image_4'           => $img(3),
            'image_5'           => $img(4),
            'price'             => $this->formattedPrice(),
            'title'             => strtoupper((string) $this->title),
            'suburb'            => strtoupper((string) $this->suburb) . ($this->city ? ', ' . strtoupper((string) $this->city) : ''),
            'property_type'     => strtoupper(str_replace('_', ' ', (string) $this->property_type)),
            'features'          => trim(($beds ? $beds . ' Bed' : '') . ($baths ? ' · ' . $baths . ' Bath' : '') . ($garages ? ' · ' . $garages . ' Garage' : ''), ' · '),
            // Full amenity list — the Ad Builder "Features" element lets the user
            // pick which of these to display. Deduped, blanks dropped.
            'features_list'     => array_values(array_unique(array_filter(array_map(
                fn ($f) => trim((string) $f),
                (array) ($this->features_json ?? []),
            )))),
            'beds'              => (string) ($beds ?? ''),
            'baths'             => (string) ($baths ?? ''),
            'garages'           => (string) ($garages ?? ''),
            'size_m2'           => $size,
            'reference'         => $this->external_id ?: ('REF ' . $this->id),
            'address'           => $this->address ?: null,
            'status_badge'      => $statusBadge,
            'agent_name'        => strtoupper((string) ($agent?->name ?? '')),
            'agent_email'       => $agent?->email ?? '',
            // User has no `mobile` column — the mobile number lives in `cell`,
            // with `phone` as the landline fallback. (Was `$agent?->mobile` which
            // was always null, so the cell number never reached the ad.)
            'agent_phone'       => $agent?->cell ?: $agent?->phone ?: '',
            'agent_designation' => $agent?->designation ?? 'Property Practitioner',
            // User has no `avatar_url` column — the photo URL comes from
            // profilePhotoUrl() (user_documents → legacy agent_photo_path).
            'agent_avatar'      => self::adSafeImageUrl($agent?->profilePhotoUrl()),

            // Agent 2 — the co-listing agent (empty when the listing is single-agent).
            // Powers the dual-agent prebuilt layouts + the builder's Agent 2 fields.
            'agent_2_name'        => strtoupper((string) ($agent2?->name ?? '')),
            'agent_2_email'       => $agent2?->email ?? '',
            'agent_2_phone'       => $agent2 ? ($agent2->cell ?: $agent2->phone ?: '') : '',
            'agent_2_designation' => $agent2 ? ($agent2->designation ?: 'Property Practitioner') : '',
            'agent_2_avatar'      => self::adSafeImageUrl($agent2?->profilePhotoUrl()),
            'agent_2_initial'     => $agent2 ? strtoupper(mb_substr((string) $agent2->name, 0, 1)) : '',

            'agency_name'       => $agency?->name ?? '',
            'website'           => $agency?->website_url ?: '',
            'logo'              => $logoUrl,
            'watermark'         => strtoupper((string) ($agency?->name ?? '')),
        ];
    }

    // ── Whistleblower complaints ──

    public function whistleblowComplaints(): HasMany
    {
        return $this->hasMany(\App\Models\Compliance\WhistleblowComplaint::class);
    }

    // ── Calendar event links (M2.2) ──

    public function calendarEventLinks(): MorphMany
    {
        return $this->morphMany(CalendarEventLink::class, 'linkable');
    }

    public function calendarEvents()
    {
        return $this->morphToMany(CalendarEvent::class, 'linkable', 'calendar_event_links', null, 'calendar_event_id');
    }

    // ── Communication links (AT-158 DR2 · WS5, §10) ──
    // A property is a first-class pillar on the communication archive: DR2
    // document distributions link the outbound Communication to the deal's
    // property (alongside the deal + recipient contact). This is the read seam
    // the property "Document distributions" surface queries.

    public function communicationLinks(): MorphMany
    {
        return $this->morphMany(\App\Models\Communications\CommunicationLink::class, 'linkable');
    }

    public function communications()
    {
        return $this->morphToMany(
            \App\Models\Communications\Communication::class,
            'linkable',
            'communication_links',
            null,
            'communication_id'
        );
    }
}
