<?php

namespace App\Services\Syndication\Property24;

use App\Exceptions\Property24ConfigurationException;
use App\Models\Agency;
use App\Models\P24City;
use App\Models\P24Province;
use App\Models\P24Suburb;
use App\Models\Property;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class Property24ListingMapper
{
    /**
     * Map a CoreX Property to a P24 Listing payload matching the v53 API schema.
     *
     * @throws Property24ConfigurationException when the property's branch/agency
     *         has no P24 agency ID configured.
     */
    public function map(Property $property, bool $includePhotos = true): array
    {
        $agencyId       = $this->resolveP24AgencyId($property);
        $suburbId       = $this->resolveSuburbId($property);
        $propertyTypeId = $this->resolvePropertyTypeId($property->property_type);

        $listing = [
            'agencyId'          => $agencyId,
            'contactAgentIds'   => $this->resolveContactAgentIds($property, $agencyId),
            'listingType'       => $this->mapListingType($property->listing_type ?? $property->mandate_type),
            'status'            => $this->mapPropertyStatus($property),
            // P24 carries the monthly rent in `price` for rentals; effectivePrice()
            // returns rental_amount for rental stock, price for sales — one source.
            'price'             => $property->effectivePrice(),
            'isPOA'             => (bool) $property->price_on_application,
            'listingVisibility' => 'Public',
            'expiryDate'        => $property->expiry_date?->format('Y-m-d\TH:i:s')
                                   ?? now()->addYear()->format('Y-m-d\TH:i:s'),
            'description'       => $property->description ?? '',
            'descriptionHeader' => $property->headline ?? $property->title ?? '',
            'propertyInfo'      => $this->buildPropertyInfo($property, $suburbId, $propertyTypeId),
            'propertyFeatures'  => $this->buildPropertyFeatures($property),
            'youTubeVideoId'    => $this->extractYouTubeId($property->youtube_video_id),
            'matterportSpaceId' => $property->matterport_id ?: null,
        ];

        // Top-level P24 `tags[]` — GLOBAL features that map to a Tag enum member
        // AND have NO PropertyFeatures field (security/connectivity/descriptive:
        // alarm, burglar bars, electric fence/gate, 24hr, CCTV, TV Port-global,
        // sea view, ports, air-con, …). Amenities WITH a PropertyFeatures field are
        // routed there (above) — never duplicated as a loose tag.
        $tags = $this->buildTags($property);
        if (!empty($tags)) {
            $listing['tags'] = $tags;
        }

        // AT-102/AT-103 — per-room named rooms with their feature chips ONLY. The
        // room label is generated by P24 from featureType; it is never put in
        // description/tags. featureType "Other" is never sent. Global amenities live
        // in PropertyFeatures (above) or tags[] — not here.
        $featureTags = $this->buildFeatureTags($property);
        if (!empty($featureTags)) {
            $listing['featureTags'] = $featureTags;
        }

        // AT-P24 remediation (#6): a coordinate stored as the string
        // "0.00000000" is truthy in PHP, so the old `$lat && $lng` guard let 0,0
        // through and P24 rejected it ("Latitude and Longitude can not both be
        // 0."). Compare numerically so any zero/blank coordinate is skipped.
        if ((float) $property->latitude != 0.0 && (float) $property->longitude != 0.0) {
            $listing['propertyInfo']['geographicLocation'] = [
                'latitude'  => (float) $property->latitude,
                'longitude' => (float) $property->longitude,
            ];
        }

        if ($property->p24_ref) {
            $listing['listingNumber'] = (int) $property->p24_ref;
            // Only override to Active if property is still on market
            if ($listing['status'] === 'NewListing') {
                $listing['status'] = 'Active';
            }
        }

        // Complex info — always sent (P24 needs the full address regardless of
        // the public-display flag).
        if ($property->complex_name || $property->unit_number) {
            $listing['complexInfo'] = [
                'complexName' => $property->complex_name ?? null,
                'unitNumber'  => $property->unit_number ?? null,
            ];
        }

        // Rental info
        if ($this->mapListingType($property->listing_type ?? $property->mandate_type) === 'Rental') {
            $rentalInfo = ['leasePeriod' => $property->lease_period ?? '12 Months'];
            if ($property->deposit_amount) {
                $rentalInfo['depositRequirementsComments'] = 'Deposit: R ' . number_format((float) $property->deposit_amount, 0, '.', ' ');
            }
            $listing['rentalInfo'] = $rentalInfo;
        }

        // Commercial info — match on substring so the canonical CoreX labels
        // ("Commercial Property", "Industrial Property") fire, not just the bare
        // words. The old exact in_array() gate missed every live commercial
        // listing (all typed "Commercial Property"/"Industrial Property"), so
        // commercialInfo never emitted. Aligned with resolvePropertyTypeId().
        $ptLower = strtolower($property->property_type ?? '');
        if (str_contains($ptLower, 'commercial') || str_contains($ptLower, 'industrial')
            || str_contains($ptLower, 'office') || str_contains($ptLower, 'retail')) {
            $commercial = [];
            if ($property->gross_price) $commercial['grossPrice'] = (float) $property->gross_price;
            if ($property->net_price) $commercial['netPrice'] = (float) $property->net_price;
            if ($property->lease_start_date) $commercial['availabilityDate'] = $property->lease_start_date->format('Y-m-d');

            // AT-P24 remediation (#9) — previously-UNROUTED commercial amenities
            // with a VERBATIM PropertyFeatures/CommercialInfo home in the v53
            // schema (CommercialInfo.greenBuilding / multiTenanted /
            // hasNaturalLight). Sourced from the property-screen global features.
            $gf  = array_map('strtolower', $this->globalFeatures($property));
            $has = fn (string $n) => in_array(strtolower($n), $gf, true);
            if ($has('Green Building')) $commercial['greenBuilding'] = true;
            if ($has('Multi Tenanted')) $commercial['multiTenanted'] = true;
            if ($has('Natural Light')) $commercial['hasNaturalLight'] = true;

            if (!empty($commercial)) $listing['commercialInfo'] = $commercial;
        }

        // Occupation date
        if ($property->lease_start_date) {
            $listing['occupationDate'] = $property->lease_start_date->format('Y-m-d\TH:i:s');
        }

        // Showdays
        $showdays = $this->buildShowdays($property);
        if (!empty($showdays)) {
            $listing['showDays'] = $showdays;
        }

        if ($includePhotos) {
            $photos = $this->buildPhotos($property);
            if (!empty($photos)) {
                $listing['photos'] = $photos;
            }
        }

        return $listing;
    }

    private function buildPropertyInfo(Property $property, ?int $suburbId, ?int $propertyTypeId): array
    {
        // P24 "hide address" affects ONLY public display, never the data we send.
        // P24's verification team REQUIRES the full address always (to vet
        // legitimacy, link/group properties, confirm the address is real), so the
        // street number/name, stand number, complex/unit and GPS are ALWAYS sent.
        // p24_hide_address=1 merely sets showLocation=false so P24 does not show
        // the address publicly. Independent of the PP pp_hide_* flags.
        $info = [
            'suburbId'        => $suburbId,
            'propertyTypeId'  => $propertyTypeId,
            'streetNumber'    => $property->street_number ?? '',
            'streetName'      => $property->street_name ?? $this->parseStreetName($property->address),
            'sourceReference' => 'CoreX-' . $property->id,
            'showLocation'    => $property->p24_hide_address
                ? false
                : (bool) ($property->latitude && $property->longitude),
        ];

        if ($property->stand_number) $info['standNumber'] = $property->stand_number;
        if ($property->erf_size_m2) $info['erf'] = ['areaUnit' => 'SquareMetres', 'size' => (float) $property->erf_size_m2];
        if ($property->size_m2) $info['floorArea'] = ['areaUnit' => 'SquareMetres', 'size' => (float) $property->size_m2];
        if ($property->floor_number) $info['floorNumber'] = (int) $property->floor_number;
        if ($property->rates_taxes) $info['municipalRatesAndTaxes'] = ['amount' => (float) $property->rates_taxes, 'unit' => 'TotalPrice'];
        if ($property->levy) $info['monthlyLevy'] = ['amount' => (float) $property->levy, 'unit' => 'TotalPrice'];
        if ($property->special_levy) $info['specialLevy'] = (float) $property->special_levy;

        return $info;
    }

    private function buildPropertyFeatures(Property $property): array
    {
        // AT-103/AT-102 — property-level booleans (hasFeature) must source from
        // GLOBAL-ONLY features (the property feature screen = spaces_json['features']),
        // NOT the flat features_json which also carries per-room unit features. A
        // feature that exists only on a room must not flip a property-level boolean.
        $feats = $this->globalFeatures($property);
        $spacesData = $property->spaces_json ?? [];
        $spacesList = $spacesData['spaces'] ?? (isset($spacesData[0]) ? $spacesData : []);
        $hasFeature = fn(string ...$names) => !empty(array_intersect(array_map('strtolower', $feats), array_map('strtolower', $names)));
        $countSpaces = fn(string $type) => collect($spacesList)->where('type', $type)->sum(fn($s) => (float) ($s['count'] ?? 1));

        $features = [
            'garages'         => (float) ($property->garages ?? 0),
            'garden'          => $hasFeature('Garden', 'Landscaped', 'Garden Services') || $countSpaces('Garden') > 0,
            'pool'            => $hasFeature('Pool', 'Communal Pool', 'Indoor Pool', 'Splash Pool') || $countSpaces('Pool') > 0,
            'flatlet'         => $hasFeature('Flatlet') || $countSpaces('Flatlet') > 0,
            'petsAllowed'     => $hasFeature('Pet Friendly', 'Pets Allowed') ? 'Yes' : ($hasFeature('Pets Not Allowed') ? 'No' : 'DontKnow'),
            'furnishedStatus' => $hasFeature('Furnished') ? 'Yes' : ($hasFeature('Unfurnished') ? 'No' : 'No'),
        ];

        if ($property->beds) $features['bedrooms'] = (float) $property->beds;
        if ($property->baths) $features['bathrooms'] = ['bathrooms' => (float) $property->baths];

        // Parking details from spaces/features
        $parkingSpaces = $countSpaces('Parking');
        if ($parkingSpaces > 0 || $hasFeature('Carport', 'Secure Parking', 'Street Parking', 'Underground Parking', 'Visitors Parking')) {
            $features['parking'] = [
                'parkingSpaces'        => $parkingSpaces > 0 ? (int) $parkingSpaces : null,
                'carport'              => $hasFeature('Carport'),
                'secureParking'        => $hasFeature('Secure Parking'),
                'onStreetParking'      => $hasFeature('Street Parking'),
                'undergroundParking'   => $hasFeature('Underground Parking'),
                'visitorsParking'      => $hasFeature('Visitors Parking'),
                'shadeNetCoveredParking' => $hasFeature('Shade Net Covered Parking'),
                'doubleParking'        => $hasFeature('Double Parking'),
                'singleParking'        => $hasFeature('Single Parking'),
                'tandemParking'        => $hasFeature('Tandem Parking'),
                'tripleParking'        => $hasFeature('Triple Parking'),
            ];
        }

        // Studies / offices
        $studies = $countSpaces('Study') + $countSpaces('Office');
        if ($studies > 0) $features['studies'] = (int) $studies;

        // Reception rooms (lounge + dining)
        $reception = $countSpaces('Lounge') + $countSpaces('Dining Room') + $countSpaces('TV Room');
        if ($reception > 0) $features['receptionRooms'] = (int) $reception;

        // Domestic rooms
        $domestic = $countSpaces('Domestic Room');
        if ($domestic > 0) $features['domesticRooms'] = (int) $domestic;

        // Domestic bathrooms
        $domesticBaths = $countSpaces('Domestic Bathroom');
        if ($domesticBaths > 0) $features['domesticBathrooms'] = (float) $domesticBaths;

        // Outside toilets
        $outsideToilets = $countSpaces('Outside Toilet');
        if ($outsideToilets > 0) $features['outsideToilets'] = (int) $outsideToilets;

        // Second house / outbuildings
        $features['secondHouse'] = $countSpaces('Flatlet') > 0 || $countSpaces('Wendy House') > 0;

        // Standalone building
        if ($hasFeature('Standalone')) $features['hasStandaloneBuilding'] = true;

        // Wheelchair accessible
        if ($hasFeature('Wheelchair Friendly')) $features['isWheelchairAccessible'] = true;

        // Generator
        if ($hasFeature('Generator')) $features['hasGenerator'] = true;

        // Backup water
        if ($hasFeature('Backup Water', 'Water Tank', 'Borehole')) $features['hasBackupWater'] = true;

        // Internet access — ALWAYS sent so P24 reflects CoreX as the source of
        // truth. Only CoreX features with a true P24 InternetAccessInfo
        // equivalent are mapped; "Fast Internet" and "Wi-Fi" are generic flags
        // with NO P24 technology field, so they never set fibre/adsl/satellite
        // (inferring fibre from Fast Internet made listings show "Fibre
        // internet" on P24). The block is emitted unconditionally — including
        // all-false — so that a re-push deterministically CLEARS a stale
        // fibre/adsl/satellite a previous push set; omitting it lets P24 retain
        // the old value (P24 does not clear fields absent from the payload).
        $features['internetAccess'] = [
            'adsl'      => $hasFeature('ADSL'),
            'fibre'     => $hasFeature('Fibre'),
            'satellite' => $hasFeature('Satellite Internet', 'Satellite Dish'),
        ];

        // Sustainability
        if ($hasFeature('Solar Panel', 'Solar Geyser', 'Gas Geyser', 'Water Tank', 'Borehole', 'Backup Battery', 'Inverter')) {
            $features['sustainabilityInfo'] = [
                'solarPanels'             => $hasFeature('Solar Panel', 'Solar Heating'),
                'solarGeyser'             => $hasFeature('Solar Geyser'),
                'gasGeyser'               => $hasFeature('Gas Geyser'),
                'waterTank'               => $hasFeature('Water Tank'),
                'borehole'                => $hasFeature('Borehole'),
                'backupBatteryOrInverter' => $hasFeature('Backup Battery', 'Inverter'),
            ];
        }

        // Kitchens — emit when there's a counted Kitchen space OR a global kitchen
        // amenity that has a KitchensInfo field (so Coffee Machine / Sink /
        // Dishwasher route to PropertyFeatures, not loose tags).
        $kitchens = $countSpaces('Kitchen');
        if ($kitchens > 0 || $hasFeature('Dishwasher', 'Coffee Machine', 'Sink')) {
            $features['kitchens'] = [
                'kitchens'      => $kitchens > 0 ? (int) $kitchens : null,
                'dishwasher'    => $hasFeature('Dishwasher'),
                'coffeeMachine' => $hasFeature('Coffee Machine'),
                'sink'          => $hasFeature('Sink'),
            ];
        }

        // Outside areas (balcony, courtyard, patio, veranda, etc.)
        $patios = $countSpaces('Patio') + $countSpaces('Veranda') + $countSpaces('Lapa') + $countSpaces('Courtyard');
        if ($patios > 0 || $hasFeature('Balcony', 'Courtyard')) {
            $features['outsideArea'] = [
                'outsideAreas' => (int) max($patios, 1),
                'balcony'      => $hasFeature('Balcony'),
                'courtyard'    => $hasFeature('Courtyard') || $countSpaces('Courtyard') > 0,
                'roofArea'     => false,
            ];
        }

        // Number of floors
        if ($hasFeature('Single Storey')) $features['numberOfFloors'] = 1;

        // Public transport
        if ($hasFeature('Near Bus Service', 'Near Train Service')) {
            $features['publicTransport'] = [
                'nearbyBusService'         => $hasFeature('Near Bus Service'),
                'nearbyMinibusTaxiService' => false,
                'nearbyTrainService'       => $hasFeature('Near Train Service'),
            ];
        }

        return $features;
    }

    /**
     * CoreX feature label → P24 `Tag` enum value.
     *
     * Only amenities that have NO dedicated propertyFeatures field live here —
     * everything else is already covered by buildPropertyFeatures(). Every value
     * on the right is a verified member of the P24 v53 `Tag` enum
     * (storage/p24_swagger.json); an unrecognised value would be rejected by the
     * portal, so do NOT add a mapping without confirming the enum string first.
     */
    private const FEATURE_TAG_MAP = [
        // Views / setting
        'Sea View'               => 'Sea',
        'Communal Braai Area'    => 'Communalbraaiarea',
        // Storey / floor position
        'Single Storey'          => 'SingleStorey',
        'Ground Floor Unit'      => 'GroundFloor',
        'Second Floor and Above' => 'Secondfloorandabove',
        'Top Floor'              => 'TopFloor',
        // Security
        'Alarm System'           => 'AlarmSystem',
        'Electric Gate'          => 'ElectricGate',
        'Electric Fence'         => 'Electricfencing',
        'Security Gate'          => 'SecurityGate',
        'Burglar Bars'           => 'BurglarBars',
        'CCTV'                   => 'ClosedCircuitTV',
        'Intercom'               => 'Intercom',
        '24 Hour Access'         => 'TwentyFourHourAccess',
        '24 Hour Guard'          => 'Guard',
        'Guard House'            => 'GuardHouse',
        'Boomed Area'            => 'BoomedArea',
        'Indoor Beams'           => 'IndoorBeams',
        'Outdoor Beams'          => 'OutdoorBeams',
        'Partially Fenced'       => 'PartiallyFenced',
        'Totally Fenced'         => 'TotallyFenced',
        'Totally Walled'         => 'TotallyWalled',
        'Perimeter Wall'         => 'PerimeterWall',
        'Gated Community'        => 'GatedCommunity',
        'Security Complex'       => 'SecurityComplex',
        'Security Estate'        => 'SecurityEstate',
        // Connectivity
        'Internet Port'          => 'InternetPort',
        'Telephone Port'         => 'TelephonePort',
        'TV Port'                => 'TVPort',
        'Satellite Dish'         => 'SatelliteDish',
        // Sustainability
        'Solar Heating'          => 'SolarHeating',
        'Septic Tank'            => 'SepticTank',

        // AT-P24 remediation (#9) — previously-UNROUTED features that have a
        // VERBATIM P24 Tag enum member (storage/p24_swagger.json Tag.enum).
        // Confirmed exact spelling before wiring; no semantic guesses.
        'Armed Response'         => 'TwentyFourHourResponse', // global security amenity
        'Irrigation'             => 'Irrigationsystem',       // Garden room feature
        'Sprinklers'             => 'SprinklerSystem',        // Garden room feature

        // AT-102/AT-103 coverage audit — clean 1:1 CoreX feature ↔ P24 Tag enum pairings
        // that previously never syndicated (verified exact members of
        // storage/p24_swagger.json components.schemas.Tag.enum). Room-detail / kitchen /
        // bathroom / pool / floor / outdoor features. Excludes any feature already carried
        // by a dedicated propertyFeatures field (Carport/Secure/Underground/Visitors
        // Parking → parking{}, Landscaped/Garden Services → garden) per the rule above.
        // Ambiguous pairings (Fibre, ADSL, Cable TV, Wi-Fi, Air Conditioned, Armed
        // Response, Solar Panel, Inverter, …) are held for Johan — not guessed here.
        'Auto Cleaning Equipment' => 'AutoCleaningEquipment',
        'Basin' => 'Basin',
        'Bath' => 'Bath',
        'Bidet' => 'Bidet',
        'Breakfast Nook' => 'BreakfastNook',
        'Built-In Braai' => 'Built_inBraai',
        'Built-in Cupboards' => 'Built_inCupboards',
        'Chlorinator' => 'Chlorinator',
        'Communal' => 'Communal',
        'Covered' => 'Covered',
        'Dishwasher Connection' => 'DishwasherConnection',
        'Double Basin' => 'DoubleBasin',
        'En-suite' => 'EnSuite',
        'Extractor Fan' => 'ExtractorFan',
        'Eye Level Oven' => 'EyeLevelOven',
        'Fan' => 'Fan',
        'Fenced' => 'Fenced',
        'Fridge' => 'Fridge',
        'Garbage Disposal' => 'GarbageDisposal',
        'Garden Terrace' => 'GardenTerrace',
        'Gas Hob' => 'GasHob',
        'Gas Oven' => 'GasOven',
        'Granite Tops' => 'GraniteTops',
        'Grill' => 'Grill',
        'Guest Toilet' => 'GuestToilet',
        'Half Bathroom' => 'HalfBathroom',
        'Heated' => 'Heated',
        'Hob' => 'Hob',
        'Icemaker' => 'Icemaker',
        'Jacuzzi Bath' => 'JacuzziBath',
        'Laminated Floors' => 'LaminatedFloors',
        'Lighting' => 'Lighting',
        'Main en-suite' => 'MainenSuite',
        'Oven and Hob' => 'OvenAndHob',
        'Pantry' => 'Pantry',
        'Parquet Floors' => 'ParquetFloors',
        'Pizza Oven' => 'PizzaOven',
        'Safe' => 'Safe',
        'Safety Net' => 'SafetyNet',
        'Separate Toilet' => 'SeparateToilet',
        'Shower' => 'Shower',
        'Tiled Floors' => 'TiledFloors',
        'Toilet' => 'Toilet',
        'Tumble Dryer' => 'TumbleDryer',
        'Under Counter Oven' => 'UnderCounterOven',
        'Underfloor Heating' => 'UnderfloorHeating',
        'Urinal' => 'Urinal',
        'Vinyl Floors' => 'VinylFloors',
        'Walk in Closet' => 'Walk_in_closet',
        'Washing Machine Connection' => 'WashingMachineConnection',
        'Water Cooler' => 'WaterCooler',
        'Water Feature' => 'WaterFeature',
        'Wooden Floors' => 'WoodenFloors',
        'Zen Garden' => 'ZenGarden',
        'Zinc' => 'Zinc',
        'Air Conditioned' => 'AirConditioningUnit',
    ];

    /**
     * CoreX GLOBAL feature labels that have a dedicated PropertyFeatures field
     * (see buildPropertyFeatures()). Per the P24 contract
     * (.ai/specs/p24-featuretags-contract.md), these populate the structured
     * External Features / Building / Other Features sections via PropertyFeatures
     * — so they MUST NOT also be emitted as a loose top-level tag[]. The
     * top-level tags[] array carries ONLY mapped global features that have NO
     * PropertyFeatures home (security/connectivity amenities, descriptive tags).
     *
     * Lower-cased. Keep in sync with the hasFeature() routes in
     * buildPropertyFeatures(). This is the class-level routing boundary — no
     * per-feature special-casing in buildTags().
     */
    private const PROPERTY_FEATURE_LABELS = [
        'adsl', 'backup battery', 'backup water', 'balcony', 'borehole',
        'carport', 'coffee machine', 'communal pool', 'courtyard', 'dishwasher',
        'double parking', 'fibre', 'flatlet', 'furnished', 'garden',
        'garden services', 'gas geyser', 'generator', 'indoor pool', 'inverter',
        'landscaped', 'near bus service', 'near train service', 'pet friendly',
        'pets allowed', 'pets not allowed', 'pool', 'satellite dish',
        'satellite internet', 'secure parking', 'shade net covered parking',
        'single parking', 'single storey', 'sink', 'solar geyser',
        'solar heating', 'solar panel', 'splash pool', 'standalone',
        'street parking', 'tandem parking', 'triple parking',
        'underground parking', 'unfurnished', 'visitors parking', 'water tank',
        'wheelchair friendly',
    ];

    /**
     * AT-102/AT-103 — CoreX space type → P24 FeatureType enum (storage/p24_swagger.json).
     * Drives featureTags[] so each room shows as a separate NAMED room on P24. Only
     * confident, direct equivalents are mapped; CoreX space types with no clean P24
     * FeatureType (Patio, Courtyard, Veranda, Lapa, Domestic Room/Bathroom, Outside
     * Toilet, Flatlet, Wendy House, …) are skipped and logged — never guessed.
     */
    private const SPACE_TYPE_TO_P24_FEATURETYPE = [
        'Bedroom'       => 'Bedroom',
        'Bathroom'      => 'Bathroom',
        'Garage'        => 'Garage',
        'Parking'       => 'Parking',
        'Kitchen'       => 'Kitchen',
        'Garden'        => 'Garden',
        'Pool'          => 'Pool',
        'Lounge'        => 'Lounge',
        'Dining Room'   => 'DiningRoom',
        'TV Room'       => 'FamilyTVRoom',
        'Entrance Hall' => 'EntranceHall',
        'Study'         => 'Office',
        'Office'        => 'Office',
        'Bar'           => 'Bar',
        'Braai Room'    => 'BraaiRoom',
        'Loft'          => 'Loft',
        'Closet'        => 'Closet',
        'Outbuilding'   => 'Outbuilding',
    ];

    /**
     * Top-level P24 `tags[]` per the contract (.ai/specs/p24-featuretags-contract.md):
     * GLOBAL features that map to a P24 Tag enum member AND have NO
     * PropertyFeatures field. Amenities WITH a PropertyFeatures field are routed
     * there by buildPropertyFeatures() (External/Building/Other Features) and are
     * excluded here so they never appear as a loose tag. Per-room features are NOT
     * here either — they ride their room's featureTags[] entry. Case-insensitive
     * match against FEATURE_TAG_MAP; deduped; valid Tag enum members only.
     */
    private function buildTags(Property $property): array
    {
        $feats = $this->globalFeatures($property);
        if (empty($feats)) {
            return [];
        }

        // Lower-cased lookup so a stored 'sea view' still resolves to 'Sea View'.
        $lookup = [];
        foreach (self::FEATURE_TAG_MAP as $label => $tag) {
            $lookup[strtolower($label)] = $tag;
        }
        $propertyFeatureLabels = array_flip(self::PROPERTY_FEATURE_LABELS);

        $tags = [];
        foreach ($feats as $feat) {
            $key = strtolower(trim((string) $feat));
            // Amenities with a PropertyFeatures field are routed there, not here.
            if (isset($propertyFeatureLabels[$key])) {
                continue;
            }
            if (isset($lookup[$key])) {
                $tags[] = $lookup[$key];
            }
        }

        return array_values(array_unique($tags));
    }

    /**
     * AT-103 — the GLOBAL-ONLY feature set for tags[] + property-level booleans.
     *
     * global = features_json MINUS room-ONLY features, where a room-ONLY feature is one
     * that appears on a room (spaces['spaces'][].units[].features or a space's
     * featuresAll) AND is NOT in the explicit property feature-screen selection
     * (spaces['features']). A feature set BOTH globally and on a room STAYS global
     * (decision A — it also appears in featureTags[]).
     *
     * NB we do NOT use spaces['features'] as the sole source: it is empty/partial for
     * a large share of properties (imports + legacy edits store global features only in
     * the flat features_json with no per-room provenance). Subtracting only the
     * room-attributable features keeps those genuinely-global features intact (no
     * tags[] regression) while still stripping per-room-only leaks.
     *
     * @return string[]
     */
    private function globalFeatures(Property $property): array
    {
        $flat = array_values(array_unique(array_filter(
            array_map('strval', (array) ($property->features_json ?? [])),
            fn ($v) => trim($v) !== ''
        )));

        $sj = $property->spaces_json;
        $spaces = is_array($sj) ? ($sj['spaces'] ?? (isset($sj[0]) ? $sj : [])) : [];
        if (empty($spaces)) {
            return $flat; // legacy / no structured rooms — features_json is the global set
        }

        // Explicit property-screen global selection (may be empty for imports/legacy).
        $explicitGlobal = [];
        foreach (($sj['features'] ?? []) as $catArr) {
            $vals = is_array($catArr) ? $catArr : [$catArr];
            foreach ($vals as $f) {
                if (filled($f)) $explicitGlobal[strtolower(trim((string) $f))] = true;
            }
        }

        // Features attributable to a room (per-unit + space-level).
        $roomFeatures = [];
        foreach ($spaces as $sp) {
            foreach (($sp['featuresAll'] ?? []) as $f) {
                if (filled($f)) $roomFeatures[strtolower(trim((string) $f))] = true;
            }
            foreach (($sp['units'] ?? []) as $u) {
                foreach (($u['features'] ?? []) as $f) {
                    if (filled($f)) $roomFeatures[strtolower(trim((string) $f))] = true;
                }
            }
        }

        return array_values(array_filter($flat, function ($f) use ($roomFeatures, $explicitGlobal) {
            $k = strtolower(trim((string) $f));
            $roomOnly = isset($roomFeatures[$k]) && !isset($explicitGlobal[$k]);
            return !$roomOnly; // keep global + both-set; drop room-only
        }));
    }

    /**
     * AT-102/AT-103 — build P24 featureTags[] so each room shows as a separate NAMED
     * room with its per-room features attached (the display agents expect). One entry
     * per unit (Bedroom 1/2/3…) carrying that unit's features mapped via FEATURE_TAG_MAP;
     * for room-type spaces without per-unit detail, one entry carrying the space-level
     * featuresAll. Unmapped feature labels and unmapped CoreX space types are skipped
     * and logged — never guessed. receptionRooms count is left untouched (no regression).
     *
     * @return array<int, array<string, mixed>>
     */
    private function buildFeatureTags(Property $property): array
    {
        $sj = $property->spaces_json;
        $spaces = is_array($sj) ? ($sj['spaces'] ?? (isset($sj[0]) ? $sj : [])) : [];

        $tagLookup = [];
        foreach (self::FEATURE_TAG_MAP as $label => $tag) {
            $tagLookup[strtolower($label)] = $tag;
        }

        $skippedTags = [];
        $mapRoomFeatures = function (array $features) use ($tagLookup, &$skippedTags): array {
            $tags = [];
            foreach ($features as $f) {
                $key = strtolower(trim((string) $f));
                if ($key === '') continue;
                if (isset($tagLookup[$key])) {
                    $tags[] = $tagLookup[$key];
                } else {
                    $skippedTags[] = (string) $f;
                }
            }
            return array_values(array_unique($tags));
        };

        $featureTags = [];
        $skippedSpaceTypes = [];

        foreach ($spaces as $sp) {
            $type = $sp['type'] ?? null;
            if (!$type) {
                continue;
            }
            $featureType = self::SPACE_TYPE_TO_P24_FEATURETYPE[$type] ?? null;
            if ($featureType === null) {
                $skippedSpaceTypes[] = (string) $type;
                continue;
            }

            $units = $sp['units'] ?? [];
            if (!empty($units)) {
                // One named room per individual unit, with its own features.
                foreach ($units as $u) {
                    $tags = $mapRoomFeatures($u['features'] ?? []);
                    // A room with no mapped features is pure noise on P24
                    // ("Bedroom 1 → Bedroom 1"). Emit an entry ONLY when the room
                    // actually carries >=1 feature. The room count itself is already
                    // conveyed via propertyInfo (bedrooms/bathrooms/etc.).
                    if (empty($tags)) {
                        continue;
                    }
                    // P24 labels the row from featureType ("Bedroom"). The unit
                    // label ("Bedroom 1") is the ROOM NAME — putting it in
                    // description duplicates the row label. Per the contract
                    // description is feature-prose only, and units carry no prose
                    // field, so description is omitted here.
                    $featureTags[] = ['featureType' => $featureType, 'tags' => $tags];
                }
            } else {
                // Named room without per-unit detail (e.g. Lounge, Dining Room).
                $tags = $mapRoomFeatures($sp['featuresAll'] ?? []);
                if (empty($tags)) {
                    continue; // no features = no row
                }
                $entry = ['featureType' => $featureType, 'tags' => $tags];
                // description = genuine free-text/condition prose ONLY (never the
                // room name). descriptionAll is the space-level prose field.
                $desc = trim((string) ($sp['descriptionAll'] ?? ''));
                if ($desc !== '') {
                    $entry['description'] = $desc;
                }
                $featureTags[] = $entry;
            }
        }

        // NOTE: global amenities are NOT emitted as featureTags here. Those with a
        // PropertyFeatures field go to buildPropertyFeatures() (External/Building/
        // Other Features); those without go to top-level tags[] via buildTags().
        // featureType "Other" is never sent — P24 renders it as a junk room row.

        if (!empty($skippedTags) || !empty($skippedSpaceTypes)) {
            // Logging is best-effort — it must never break the mapping (and the logger
            // isn't booted in pure unit contexts).
            try {
                \Illuminate\Support\Facades\Log::channel('property24')->info(
                    'P24 featureTags — skipped unmapped items',
                    [
                        'property_id'         => $property->id,
                        'skipped_tags'        => array_values(array_unique($skippedTags)),
                        'skipped_space_types' => array_values(array_unique($skippedSpaceTypes)),
                    ]
                );
            } catch (\Throwable $e) {
                // no-op — never block syndication on a log write
            }
        }

        return $featureTags;
    }

    public function validate(array $payload): array
    {
        $errors = [];
        if (empty($payload['agencyId'])) $errors[] = 'No Property24 agency ID resolved — set it on the agency or branch.';
        // AT-P24 remediation (#3): P24 rejects a listing with no agents
        // ("A listing must have one or more agents"). Fail locally with an
        // actionable reason instead of letting the empty array reach P24. An
        // empty contactAgentIds means the listing agent has no P24 profile under
        // this agency yet (or the /agents lookup timed out) — register/sync the
        // agent to P24, then re-syndicate.
        if (empty($payload['contactAgentIds'])) {
            $errors[] = 'No Property24 agent linked — the listing agent is not registered on Property24 under this agency (or the agent lookup failed). Sync the agent to P24, then re-syndicate.';
        }
        if (empty($payload['description'])) $errors[] = 'Description is required';
        if (empty($payload['propertyInfo']['suburbId'])) $errors[] = 'Suburb unmapped — manual P24 suburb mapping required. Pick a Property24-recognised suburb on the property (Province → City → Suburb), then re-syndicate.';
        if (empty($payload['propertyInfo']['propertyTypeId'])) $errors[] = 'Property type could not be mapped to a P24 type ID';
        return $errors;
    }

    public function checkReadiness(Property $property): array
    {
        $missing = [];
        if (empty($property->description)) $missing[] = ['field' => 'description', 'label' => 'Description'];
        if (empty($property->suburb)) {
            $missing[] = ['field' => 'suburb', 'label' => 'Suburb'];
        } else {
            if (!$this->resolveSuburbId($property)) {
                $missing[] = ['field' => 'suburb_id', 'label' => 'Suburb not mapped to P24 ID (set in P24 Suburb Settings)'];
            }
        }
        if (empty($property->property_type)) $missing[] = ['field' => 'property_type', 'label' => 'Property Type'];
        if ($property->effectivePrice() <= 0 && !$property->price_on_application) $missing[] = ['field' => 'price', 'label' => 'Price (or enable Price On Application)'];
        if (empty($property->allImages())) $missing[] = ['field' => 'images', 'label' => 'At least one photo'];
        if (empty($property->listing_type) && empty($property->mandate_type)) $missing[] = ['field' => 'listing_type', 'label' => 'Listing Type (Sale/Rental)'];
        if (empty($property->resolveP24AgencyId())) {
            $missing[] = [
                'field' => 'p24_agency_id',
                'label' => 'Property24 agency ID not configured on branch or agency',
            ];
        }
        return $missing;
    }

    /**
     * Resolve the P24 agency ID for a property. Branch override > agency default.
     * Throws when neither is set so submission fails loudly rather than
     * silently routing to the wrong profile (or the wrong tenant).
     */
    private function resolveP24AgencyId(Property $property): int
    {
        $resolved = $property->resolveP24AgencyId();
        if ($resolved === null || $resolved === '') {
            $branchName = $property->branch?->name ?? '(no branch)';
            $agencyName = $property->agency?->name ?? $property->branch?->agency?->name ?? '(no agency)';
            throw new Property24ConfigurationException(
                "Property #{$property->id} cannot be syndicated: no Property24 agency ID on "
                . "branch '{$branchName}' or agency '{$agencyName}'."
            );
        }
        return (int) $resolved;
    }

    private function buildPhotos(Property $property): array
    {
        $photos = [];
        $catData = $property->gallery_categories_json;

        // Build a map of image URL → category name for captions
        $captionMap = [];
        if ($catData && isset($catData['categories'])) {
            foreach ($catData['categories'] as $cat) {
                foreach ($cat['images'] ?? [] as $img) {
                    $captionMap[$img] = $cat['name'];
                }
            }
        }

        // AT-101: per-agency photo cap. Source = syndicationImages() (the exact
        // gallery the agent curates and sees, gallery_images_json), NOT allImages()
        // — allImages() additionally merges images_json (a divergent public mirror)
        // and the dawn/noon/dusk sets, over-counting photos the user never put in
        // the gallery (e.g. property #1322: gallery 45 vs allImages 68). What goes
        // to P24 must equal the CoreX gallery.
        $maxPhotos = $property->agency?->p24MaxPhotos() ?? Agency::P24_DEFAULT_MAX_PHOTOS;
        $allImages = $property->syndicationImages();

        // AT-P24 remediation (#7): never silently truncate. If the curated
        // gallery exceeds the agency photo cap, log a warning naming the
        // dropped count so an over-cap listing is visible (e.g. property 3361:
        // 160 → 150, 10 dropped) rather than quietly losing photos.
        if (count($allImages) > $maxPhotos) {
            try {
                Log::channel('property24')->warning(
                    'P24 photo cap exceeded — photos dropped from submission',
                    [
                        'property_id' => $property->id,
                        'gallery'     => count($allImages),
                        'cap'         => $maxPhotos,
                        'dropped'     => count($allImages) - $maxPhotos,
                    ]
                );
            } catch (\Throwable $e) {
                // never block syndication on a log write
            }
        }

        $images = array_slice($allImages, 0, $maxPhotos);

        foreach ($images as $imagePath) {
            if (empty($imagePath)) continue;

            $diskPath = $this->urlToDiskPath($imagePath);

            if ($diskPath && Storage::disk('public')->exists($diskPath)) {
                $bytes = Storage::disk('public')->get($diskPath);
                if (empty($bytes)) continue;

                $photos[] = [
                    'bytes'           => base64_encode($bytes),
                    'mimeContentType' => Storage::disk('public')->mimeType($diskPath) ?: 'image/jpeg',
                    'caption'         => $captionMap[$imagePath] ?? null,
                    'isFloorPlan'     => false,
                ];
            }
        }

        return $photos;
    }

    /**
     * Convert a Storage::url() path back to a disk-relative path.
     * e.g. "/storage/properties/16/file.jpg" => "properties/16/file.jpg"
     * or "https://domain.com/storage/properties/16/file.jpg" => "properties/16/file.jpg"
     */
    private function urlToDiskPath(string $url): ?string
    {
        // Strip domain if full URL
        if (str_starts_with($url, 'http://') || str_starts_with($url, 'https://')) {
            $parsed = parse_url($url);
            $url = $parsed['path'] ?? $url;
        }

        // Strip the /storage/ prefix that Storage::url() adds
        if (str_contains($url, '/storage/')) {
            return substr($url, strpos($url, '/storage/') + 9); // 9 = strlen('/storage/')
        }

        // If it's already a relative path like "properties/16/file.jpg"
        if (str_starts_with($url, 'properties/')) {
            return $url;
        }

        return null;
    }

    /**
     * Resolve the P24 numeric suburb ID (p24_suburbs.p24_id) to send in the
     * payload. Order: trust the stored, chain-verified FK; then a name match
     * that is DISAMBIGUATED BY CITY/PROVINCE and only ever accepted when it
     * resolves to exactly ONE suburb. We never guess between same-named
     * suburbs in different cities — returning null makes the caller skip
     * syndication and flag the property for manual mapping (AT-104).
     *
     * Background (AT-104): "Glenmore" exists in P24 in both Durban (id 10787)
     * and Port Edward / South Coast (id 10790). The previous resolver checked
     * `pp_suburb_id` (a Private Property column that is NULL on every CoreX
     * property, so the branch never fired) and then fell through to a bare
     * `P24Suburb::lookup()->first()` with no city filter — sending the Durban
     * Glenmore for every South Coast Glenmore. This rewrite kills that class
     * of bug for all 30+ multi-city collision suburb names, not just Glenmore.
     */
    private function resolveSuburbId(Property $property): ?int
    {
        // TIER 1 — trust the stored, chain-verified P24 suburb FK. The property
        // create/edit form and the wizard write `p24_suburb_id` only after
        // AppliesP24Location has verified the suburb→city→province chain against
        // P24's own hierarchy, so it is the authoritative mapping. NEVER fall
        // through to name guessing when it is set — that is the bug we are fixing.
        //
        // AT-P24 remediation (#2): the p24_id is only returned when its
        // p24_suburbs row is P24-VERIFIED (p24_verified_at set by the daily
        // p24:sync-locations stamp-and-sweep). An unverified row carries a
        // p24_id that P24's listing API may reject ("Value [N] for property
        // listing.SuburbId is invalid" — e.g. Addington 5997), so we never send
        // it. Soft-deleted rows are already excluded by the SoftDeletes scope.
        if ($property->p24_suburb_id) {
            $suburb = P24Suburb::find($property->p24_suburb_id);
            if ($suburb && $suburb->p24_id && $suburb->p24_verified_at !== null) {
                return (int) $suburb->p24_id;
            }
        }

        if (!$property->suburb) return null;

        // TIER 2 — exact name match, disambiguated by city/province, unique-only.
        $exact = $this->resolveUniqueLocalSuburb($property, false);
        if ($exact && $exact->p24_id) return (int) $exact->p24_id;

        // TIER 3 — fuzzy name match (handles trailing "Beach", punctuation, extra
        //          whitespace, …), same city/province constraint, same unique rule.
        $fuzzy = $this->resolveUniqueLocalSuburb($property, true);
        if ($fuzzy && $fuzzy->p24_id) return (int) $fuzzy->p24_id;

        // TIER 4 — no unique, city-qualified match. Do NOT guess and do NOT fall
        // back to a name-only API lookup (it would re-introduce the wrong-city
        // bug). Return null so submitListing()'s validate() flags the property
        // ("Suburb unmapped — manual P24 suburb mapping required") and skips it.
        return null;
    }

    /**
     * Resolve the property's suburb to exactly ONE P24Suburb row, disambiguated
     * by city/province. Returns null when zero — or MORE THAN ONE — candidate
     * survives, so we never guess between same-named suburbs in different
     * cities. $fuzzy widens the name match from exact to LIKE.
     */
    private function resolveUniqueLocalSuburb(Property $property, bool $fuzzy): ?P24Suburb
    {
        $candidates = $this->suburbNameCandidates((string) $property->suburb, $fuzzy);
        if ($candidates->isEmpty()) return null;
        if ($candidates->count() === 1) return $candidates->first();

        // Multiple same-named suburbs across cities — keep only those in a city
        // this property could legitimately belong to.
        $cityIds = $this->candidateCityIds($property);
        if (empty($cityIds)) return null; // no city signal → cannot disambiguate

        $filtered = $candidates->whereIn('p24_city_id', $cityIds)->values();
        return $filtered->count() === 1 ? $filtered->first() : null;
    }

    /**
     * Candidate P24Suburb rows whose name matches the given suburb name.
     * Exact mode matches slug or case-insensitive name equality; fuzzy mode
     * widens to a normalised LIKE both ways.
     *
     * @return \Illuminate\Support\Collection<int, P24Suburb>
     */
    private function suburbNameCandidates(string $suburbName, bool $fuzzy): \Illuminate\Support\Collection
    {
        $key = strtolower(trim($suburbName));
        if ($key === '') return collect();

        // AT-P24 remediation (#2): only P24-VERIFIED rows are eligible candidates.
        // An unverified row must never be returned (its p24_id may be rejected by
        // P24) nor count toward the uniqueness test that disambiguates collisions.
        if (!$fuzzy) {
            $slug = str_replace(' ', '-', $key);
            return P24Suburb::whereNotNull('p24_verified_at')
                ->where(function ($q) use ($slug, $key) {
                    $q->where('slug', $slug)->orWhereRaw('LOWER(name) = ?', [$key]);
                })
                ->get();
        }

        $normalised = strtolower(preg_replace('/[^a-z0-9 ]+/i', '', trim($suburbName)));
        if ($normalised === '') return collect();

        return P24Suburb::whereNotNull('p24_verified_at')
            ->where(function ($q) use ($normalised) {
                $q->whereRaw('LOWER(name) LIKE ?', ['%' . $normalised . '%'])
                  ->orWhereRaw('? LIKE CONCAT(\'%\', LOWER(name), \'%\')', [$normalised]);
            })
            ->get();
    }

    /**
     * The set of P24 city IDs (p24_cities.id) this property could legitimately
     * sit in, used to disambiguate collision suburb names. Trust order: the
     * stored p24_city_id FK first, else the city/town text (province-constrained
     * when the province is known). Empty array = no usable city signal.
     *
     * @return int[]
     */
    private function candidateCityIds(Property $property): array
    {
        if ($property->p24_city_id) {
            return [(int) $property->p24_city_id];
        }

        $cityNames = array_values(array_unique(array_filter([
            strtolower(trim((string) $property->city)),
            strtolower(trim((string) $property->town)),
        ], fn ($v) => $v !== '')));
        if (empty($cityNames)) return [];

        $query = P24City::query()->where(function ($q) use ($cityNames) {
            foreach ($cityNames as $n) {
                $q->orWhereRaw('LOWER(name) = ?', [$n]);
            }
        });

        // Province narrows same-named cities to the right one when we know it.
        $provinceId = $this->resolveProvinceId($property);
        if ($provinceId) {
            $query->where('p24_province_id', $provinceId);
        }

        return $query->pluck('id')->map(fn ($id) => (int) $id)->all();
    }

    /**
     * Resolve the property's province to a p24_provinces.id. Trust the stored
     * FK first; else match the province text after normalising both sides
     * (P24 stores "KwaZulu Natal", CoreX often holds "KwaZulu-Natal"/"KZN").
     */
    private function resolveProvinceId(Property $property): ?int
    {
        if ($property->p24_province_id) return (int) $property->p24_province_id;

        $name = $this->normaliseProvince($property->province);
        if ($name === '') return null;

        $key = preg_replace('/[^a-z0-9]+/i', '', strtolower($name));
        foreach (P24Province::all() as $province) {
            if (preg_replace('/[^a-z0-9]+/i', '', strtolower((string) $province->name)) === $key) {
                return (int) $province->id;
            }
        }
        return null;
    }

    private function normaliseProvince(?string $province): string
    {
        $p = strtolower(trim((string) $province));
        if ($p === '') return '';
        return match (true) {
            str_contains($p, 'kwazulu') || $p === 'kzn'   => 'KwaZulu-Natal',
            str_contains($p, 'western')                   => 'Western Cape',
            str_contains($p, 'eastern')                   => 'Eastern Cape',
            str_contains($p, 'northern')                  => 'Northern Cape',
            str_contains($p, 'north west')                => 'North West',
            str_contains($p, 'gauteng') || $p === 'gp'    => 'Gauteng',
            str_contains($p, 'mpumalanga')                => 'Mpumalanga',
            str_contains($p, 'limpopo')                   => 'Limpopo',
            str_contains($p, 'free state')                => 'Free State',
            default                                        => ucwords($p),
        };
    }

    /**
     * Map CoreX property type to P24 propertyTypeId.
     * IDs sourced from GET /listing/v53/property-types on ExDev:
     *   4 = House, 5 = Apartment/Flat, 6 = Townhouse,
     *   8 = Vacant Land/Plot, 10 = Farm, 11 = Commercial, 12 = Industrial
     */
    private function resolvePropertyTypeId(?string $type): ?int
    {
        if (empty($type)) return null;

        // Normalise: lowercase, replace any non-alphanum with single space, collapse, trim.
        // Lets us match "Apartment / Flat", "Apartment/Flat", "apartment-flat", etc.
        $norm = trim(preg_replace('/\s+/', ' ', preg_replace('/[^a-z0-9]+/i', ' ', strtolower($type))));

        $padded = " {$norm} ";
        $contains = function (string ...$needles) use ($padded): bool {
            foreach ($needles as $n) {
                if (str_contains($padded, " {$n} ")) return true;
            }
            return false;
        };

        if ($contains('industrial')) return 12;
        if ($contains('commercial', 'office', 'retail', 'hospitality')) return 11;
        if ($contains('farm', 'smallholding', 'small holding', 'agricultural')) return 10;
        if ($contains('vacant land', 'land', 'plot', 'stand', 'erf')) return 8;
        if ($contains('townhouse', 'duplex', 'simplex', 'cluster')) return 6;
        if ($contains('apartment', 'flat', 'penthouse')) return 5;
        if ($contains('house', 'freestanding', 'free standing', 'cottage', 'garden cottage')) return 4;

        return 4; // default: House
    }

    private function resolveContactAgentIds(Property $property, int $agencyId): array
    {
        // Build an agency-scoped client so credentials come from the property's
        // agency row (not the now-empty .env). Without this the client falls
        // back to env creds, authenticates as nobody, and returns zero agents
        // — which P24 then rejects as "must have one or more agents".
        $agency = $property->agency ?? \App\Models\Agency::find($property->agency_id);
        $client = new Property24ApiClient($agency);
        // Scope the lookup to the property's resolved agency — otherwise a
        // property under agency B would pull agents from agency A's feed.
        $result = $client->getAgents((string) $agencyId);

        if (!$result['success']) return [];

        $agents = $result['data'] ?? [];
        $ids = [];

        // Agents who opted out of P24 must never be attached to a syndicated
        // listing, even if a stale P24 record still carries their sourceReference.
        $excludedUserIds = \App\Models\User::withTrashed()
            ->whereIn('id', array_filter([$property->agent_id, $property->pp_second_agent_id]))
            ->where('exclude_from_p24', true)
            ->pluck('id')
            ->all();

        // Primary agent
        if ($property->agent_id && !in_array((int) $property->agent_id, $excludedUserIds, true)) {
            $sourceRef = 'CoreX-Agent-' . $property->agent_id;
            foreach ($agents as $agent) {
                if (($agent['sourceReference'] ?? '') === $sourceRef) {
                    $ids[] = (int) $agent['id'];
                    break;
                }
            }
        }

        // Second agent
        if ($property->pp_second_agent_id && !in_array((int) $property->pp_second_agent_id, $excludedUserIds, true)) {
            $sourceRef = 'CoreX-Agent-' . $property->pp_second_agent_id;
            foreach ($agents as $agent) {
                if (($agent['sourceReference'] ?? '') === $sourceRef) {
                    $ids[] = (int) $agent['id'];
                    break;
                }
            }
        }

        return $ids;
    }

    private function buildShowdays(Property $property): array
    {
        $showdays = [];
        $active = $property->activeShowdays ?? $property->showdays()->where('active', true)->where('end_date', '>=', now())->get();

        foreach ($active as $s) {
            $showdays[] = [
                'startDate' => $s->start_date->format('Y-m-d\TH:i:s'),
                'endDate'   => $s->end_date->format('Y-m-d\TH:i:s'),
            ];
        }

        return $showdays;
    }

    /**
     * Map CoreX property status to P24 ListingStatus enum.
     * P24 statuses: NewListing, Active, Rented, Withdrawn, BackOnMarket,
     *               Expired, Extended, RaisedPrice, ReducedPrice,
     *               Cancelled, Pending, Sold, CancelledSale
     */
    private function mapPropertyStatus(Property $property): string
    {
        return self::getP24Status($property->status, $property->p24_ref, $property->status_label);
    }

    /**
     * Static helper: convert a CoreX two-tier status (base status + optional
     * sub-label banner) to a P24 ListingStatus. Used by both the mapper and the
     * observer.
     *
     * Two-tier model (mirrors P24/Propcon): a listing has a BASE status and an
     * optional SUB-LABEL on an on-market base — e.g. For Sale + "Reduced Price",
     * For Sale + "Pending", For Sale + "Back on Market". The sub-label IS the
     * authoritative P24 lifecycle signal when present, so it is resolved FIRST;
     * a For-Sale base with no label falls through to the base-status logic.
     *
     * Back-compat: $statusLabel is optional and defaults to null. With a null
     * label this returns exactly what the prior flat-status version returned for
     * every base status — proven by the AT-P24 before/after round-trip table —
     * with one intentional fix: a let-out rental now maps to 'Rented' instead of
     * silently falling through to 'NewListing'.
     */
    public static function getP24Status(?string $corexStatus, ?string $p24Ref = null, ?string $statusLabel = null): string
    {
        $normalise = static function (?string $v): string {
            $v = strtolower(str_replace(['•', '_'], ['', ' '], trim($v ?? '')));
            return preg_replace('/\s+/', ' ', $v); // collapse multiple spaces
        };

        // 1) Sub-label (banner) takes precedence — it is the P24 lifecycle state.
        $label = $normalise($statusLabel);
        if ($label !== '') {
            $fromLabel = match (true) {
                str_contains($label, 'reduced')        => 'ReducedPrice',
                str_contains($label, 'raised')         => 'RaisedPrice',
                str_contains($label, 'back on market') => 'BackOnMarket',
                str_contains($label, 'under offer')
                    || str_contains($label, 'pending') => 'Pending',
                default                                => null,
            };
            if ($fromLabel !== null) {
                return $fromLabel;
            }
        }

        // 2) Base status.
        $status = $normalise($corexStatus);

        return match (true) {
            str_contains($status, 'sold')              => 'Sold',
            str_contains($status, 'rented')
                || str_contains($status, 'let out')     => 'Rented',
            str_contains($status, 'withdrawn')
                || str_contains($status, 'unavailable') => 'Withdrawn',
            str_contains($status, 'under offer')
                || str_contains($status, 'pending')     => 'Pending',
            str_contains($status, 'back on market')     => 'BackOnMarket',
            str_contains($status, 'reduced')            => 'ReducedPrice',
            str_contains($status, 'raised')             => 'RaisedPrice',
            str_contains($status, 'expired')            => 'Expired',
            str_contains($status, 'cancelled')
                || str_contains($status, 'archived')    => 'Cancelled',
            str_contains($status, 'draft')              => 'Withdrawn',
            str_contains($status, 'auction')            => 'Active',
            $p24Ref !== null                            => 'Active',
            default                                     => 'NewListing',
        };
    }

    /**
     * Check if a P24 status is a terminal/off-market status.
     */
    public static function isTerminalStatus(string $p24Status): bool
    {
        return in_array($p24Status, ['Sold', 'Rented', 'Withdrawn', 'Expired', 'Cancelled']);
    }

    private function mapListingType(?string $type): string
    {
        if (empty($type)) return 'Sale';
        return match (strtolower($type)) {
            'sale', 'for sale', 'sell' => 'Sale',
            'rental', 'rent', 'to let' => 'Rental',
            default => 'Sale',
        };
    }

    private function parseStreetName(?string $address): string
    {
        if (empty($address)) return '';
        $parts = explode(',', $address);
        return preg_replace('/^\d+\s+/', '', trim($parts[0] ?? ''));
    }

    private function extractYouTubeId(?string $input): ?string
    {
        if (!$input) return null;
        $input = trim($input);
        if (preg_match('/^[a-zA-Z0-9_-]{11}$/', $input)) return $input;
        if (preg_match('/(?:youtube\.com\/(?:watch\?\S*?v=|embed\/|shorts\/|live\/|v\/)|youtu\.be\/|v=)([a-zA-Z0-9_-]{11})/', $input, $m)) {
            return $m[1];
        }
        return null;
    }
}
