<?php

namespace App\Services\Syndication\Property24;

use App\Exceptions\Property24ConfigurationException;
use App\Models\Agency;
use App\Models\P24City;
use App\Models\P24Province;
use App\Models\P24Suburb;
use App\Models\Property;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class Property24ListingMapper
{
    /**
     * P24 rejects a single submit whose images together exceed 60MB of data.
     * We pack to a budget below that hard cap, measured on the base64-encoded
     * size (the bytes actually transmitted) so the request stays under the cap
     * regardless of whether P24 counts raw or encoded bytes — with headroom for
     * the rest of the JSON payload. Only large galleries ever hit this; a set
     * that already fits is sent untouched at full quality.
     */
    private const P24_MAX_IMAGE_PAYLOAD_BYTES     = 60 * 1024 * 1024;
    private const P24_IMAGE_PAYLOAD_BUDGET_BYTES   = 57 * 1024 * 1024;

    /**
     * Map a CoreX Property to a P24 Listing payload matching the v53 API schema.
     *
     * @throws Property24ConfigurationException when the property's branch/agency
     *         has no P24 agency ID configured.
     */
    public function map(Property $property, bool $includePhotos = true): array
    {
        $agencyId       = $this->resolveP24AgencyId($property);
        $suburbId       = $this->resolveSuburbId($property);
        $propertyTypeId = $this->resolvePropertyTypeId($property->property_type);

        $listing = [
            'agencyId'          => $agencyId,
            'contactAgentIds'   => $this->resolveContactAgentIds($property, $agencyId),
            'listingType'       => $this->mapListingType($property->listing_type ?? $property->mandate_type),
            'status'            => $this->mapPropertyStatus($property),
            // P24 carries the monthly rent in `price` for rentals; effectivePrice()
            // returns rental_amount for rental stock, price for sales — one source.
            'price'             => $property->effectivePrice(),
            'isPOA'             => (bool) $property->price_on_application,
            'listingVisibility' => 'Public',
            'expiryDate'        => $property->expiry_date?->format('Y-m-d\TH:i:s')
                                   ?? now()->addYear()->format('Y-m-d\TH:i:s'),
            'description'       => $property->description ?? '',
            'descriptionHeader' => $property->headline ?? $property->title ?? '',
            'propertyInfo'      => $this->buildPropertyInfo($property, $suburbId, $propertyTypeId),
            'propertyFeatures'  => $this->buildPropertyFeatures($property),
            'youTubeVideoId'    => $this->extractYouTubeId($property->youtube_video_id),
            'matterportSpaceId' => $property->matterport_id ?: null,
        ];

        // Top-level P24 `tags[]` — GLOBAL features that map to a Tag enum member
        // AND have NO PropertyFeatures field (security/connectivity/descriptive:
        // alarm, burglar bars, electric fence/gate, 24hr, CCTV, TV Port-global,
        // sea view, ports, air-con, …). Amenities WITH a PropertyFeatures field are
        // routed there (above) — never duplicated as a loose tag.
        $tags = $this->buildTags($property);
        if (!empty($tags)) {
            $listing['tags'] = $tags;
        }

        // AT-102/AT-103 — per-room named rooms with their feature chips ONLY. The
        // room label is generated by P24 from featureType; it is never put in
        // description/tags. featureType "Other" is never sent. Global amenities live
        // in PropertyFeatures (above) or tags[] — not here.
        $featureTags = $this->buildFeatureTags($property);
        if (!empty($featureTags)) {
            $listing['featureTags'] = $featureTags;
        }

        // AT-P24 remediation (#6): a coordinate stored as the string
        // "0.00000000" is truthy in PHP, so the old `$lat && $lng` guard let 0,0
        // through and P24 rejected it ("Latitude and Longitude can not both be
        // 0."). Compare numerically so any zero/blank coordinate is skipped.
        if ((float) $property->latitude != 0.0 && (float) $property->longitude != 0.0) {
            $listing['propertyInfo']['geographicLocation'] = [
                'latitude'  => (float) $property->latitude,
                'longitude' => (float) $property->longitude,
            ];
        }

        if ($property->p24_ref) {
            $listing['listingNumber'] = (int) $property->p24_ref;
            // Only override to Active if property is still on market
            if ($listing['status'] === 'NewListing') {
                $listing['status'] = 'Active';
            }
        }

        // Complex info — always sent (P24 needs the full address regardless of
        // the public-display flag).
        if ($property->complex_name || $property->unit_number) {
            $listing['complexInfo'] = [
                'complexName' => $property->complex_name ?? null,
                'unitNumber'  => $property->unit_number ?? null,
            ];
        }

        // Rental info
        if ($this->mapListingType($property->listing_type ?? $property->mandate_type) === 'Rental') {
            $rentalInfo = ['leasePeriod' => $property->lease_period ?? '12 Months'];
            // Rate cadence — CoreX stores rental_price_type ("per week"/"per
            // day"/…). Without emitting it, every weekly/daily/short-term rental
            // publishes at P24's default monthly cadence. Enum: Month/Week/Day/
            // Year/SquareMetre.
            if ($rentalRate = $this->mapRentalRate($property->rental_price_type ?? null)) {
                $rentalInfo['rentalRate'] = $rentalRate;
            }
            if ($property->deposit_amount) {
                $rentalInfo['depositRequirementsComments'] = 'Deposit: R ' . number_format((float) $property->deposit_amount, 0, '.', ' ');
            }
            $listing['rentalInfo'] = $rentalInfo;
        }

        // Commercial info — match on substring so the canonical CoreX labels
        // ("Commercial Property", "Industrial Property") fire, not just the bare
        // words. The old exact in_array() gate missed every live commercial
        // listing (all typed "Commercial Property"/"Industrial Property"), so
        // commercialInfo never emitted. Aligned with resolvePropertyTypeId().
        $ptLower = strtolower($property->property_type ?? '');
        if (str_contains($ptLower, 'commercial') || str_contains($ptLower, 'industrial')
            || str_contains($ptLower, 'office') || str_contains($ptLower, 'retail')) {
            $commercial = [];
            if ($property->gross_price) $commercial['grossPrice'] = (float) $property->gross_price;
            if ($property->net_price) $commercial['netPrice'] = (float) $property->net_price;
            if ($property->lease_start_date) $commercial['availabilityDate'] = $property->lease_start_date->format('Y-m-d');

            // AT-P24 remediation (#9) — previously-UNROUTED commercial amenities
            // with a VERBATIM PropertyFeatures/CommercialInfo home in the v53
            // schema (CommercialInfo.greenBuilding / multiTenanted /
            // hasNaturalLight). Sourced from the property-screen global features.
            $gf  = array_map('strtolower', $this->globalFeatures($property));
            $has = fn (string $n) => in_array(strtolower($n), $gf, true);
            if ($has('Green Building')) $commercial['greenBuilding'] = true;
            if ($has('Multi Tenanted')) $commercial['multiTenanted'] = true;
            if ($has('Natural Light')) $commercial['hasNaturalLight'] = true;

            if (!empty($commercial)) $listing['commercialInfo'] = $commercial;
        }

        // Occupation date
        if ($property->lease_start_date) {
            $listing['occupationDate'] = $property->lease_start_date->format('Y-m-d\TH:i:s');
        }

        // Showdays
        $showdays = $this->buildShowdays($property);
        if (!empty($showdays)) {
            $listing['showDays'] = $showdays;
        }

        if ($includePhotos) {
            // AT-P24: only (re)upload photos when the gallery actually changed
            // since the last successful sync. P24 keeps the existing photos when
            // `photos` is null (swagger: "set photos to null" when unchanged),
            // so a routine refresh skips the heavy base64 upload. A NEW listing
            // (no p24_ref) or one with no recorded signature always sends its
            // photos.
            $imagesChanged = empty($property->p24_ref)
                || $property->p24_image_signature === null
                || $property->p24_image_signature !== $property->p24ImageSignature();

            if ($imagesChanged) {
                $photos = $this->buildPhotos($property);
                if (!empty($photos)) {
                    $listing['photos'] = $photos;
                }
            } else {
                // Unchanged → tell P24 explicitly to keep the existing photos.
                $listing['photos'] = null;
            }
        }

        return $listing;
    }

    /**
     * Map CoreX rental_price_type ("per month"/"per week"/…) to P24's RentalRate
     * enum (Month/Week/Day/Year/SquareMetre). Returns null for an unknown/blank
     * cadence so P24 applies its own default (Month) rather than us asserting one.
     */
    private function mapRentalRate(?string $rentalPriceType): ?string
    {
        return match (strtolower(trim((string) $rentalPriceType))) {
            'per month', 'per_month', 'monthly'                          => 'Month',
            'per week', 'per_week', 'weekly'                             => 'Week',
            'per day', 'per_day', 'daily'                                => 'Day',
            'per year', 'per_year', 'yearly', 'annually'                 => 'Year',
            'per sqm', 'per_sqm', 'persqm', 'per m2', 'per_m2',
            'persquaremetre', 'per square metre', 'per square meter'     => 'SquareMetre',
            default                                                      => null,
        };
    }

    private function buildPropertyInfo(Property $property, ?int $suburbId, ?int $propertyTypeId): array
    {
        // P24 "hide address" affects ONLY public display, never the data we send.
        // P24's verification team REQUIRES the full address always (to vet
        // legitimacy, link/group properties, confirm the address is real), so the
        // street number/name, stand number, complex/unit and GPS are ALWAYS sent.
        // p24_hide_address=1 merely sets showLocation=false so P24 does not show
        // the address publicly. Independent of the PP pp_hide_* flags.
        $info = [
            'suburbId'        => $suburbId,
            'propertyTypeId'  => $propertyTypeId,
            'streetNumber'    => $property->street_number ?? '',
            'streetName'      => $property->street_name ?? $this->parseStreetName($property->address),
            'sourceReference' => 'CoreX-' . $property->id,
            // latitude/longitude are decimal:7 casts → Laravel returns them as
            // strings ("0.0000000"), which are truthy, so the old `$lat && $lng`
            // guard emitted showLocation=true for never-geocoded listings (P24
            // could then surface the street address the agent never published).
            // Compare numerically — same fix already applied to the
            // geographicLocation guard above.
            'showLocation'    => $property->p24_hide_address
                ? false
                : ((float) $property->latitude != 0.0 && (float) $property->longitude != 0.0),
        ];

        if ($property->stand_number) $info['standNumber'] = $property->stand_number;
        if ($property->erf_size_m2) $info['erf'] = ['areaUnit' => 'SquareMetres', 'size' => (float) $property->erf_size_m2];
        if ($property->size_m2) $info['floorArea'] = ['areaUnit' => 'SquareMetres', 'size' => (float) $property->size_m2];
        if ($property->floor_number) $info['floorNumber'] = (int) $property->floor_number;
        if ($property->rates_taxes) $info['municipalRatesAndTaxes'] = ['amount' => (float) $property->rates_taxes, 'unit' => 'TotalPrice'];
        if ($property->levy) $info['monthlyLevy'] = ['amount' => (float) $property->levy, 'unit' => 'TotalPrice'];
        if ($property->special_levy) $info['specialLevy'] = (float) $property->special_levy;

        return $info;
    }

    private function buildPropertyFeatures(Property $property): array
    {
        // AT-103/AT-102 — most property-level booleans (hasFeature) source from
        // GLOBAL-ONLY features (the property feature screen = spaces_json['features']),
        // NOT the flat features_json which also carries per-room unit features. A
        // feature that exists only on a room must not flip a property-level boolean.
        $feats = $this->globalFeatures($property);
        $spacesData = $property->spaces_json ?? [];
        $spacesList = $spacesData['spaces'] ?? (isset($spacesData[0]) ? $spacesData : []);
        $hasFeature = fn(string ...$names) => !empty(array_intersect(array_map('strtolower', $feats), array_map('strtolower', $names)));
        $countSpaces = fn(string $type) => collect($spacesList)->where('type', $type)->sum(fn($s) => (float) ($s['count'] ?? 1));

        // AT-146 (property 6049) — DEDICATED-SPACE amenities (parking, kitchen
        // fittings, outside areas) are entered on their own space, never on the
        // global feature screen (parking/kitchen are not one of the 4 global
        // categories), so globalFeatures() ALWAYS strips them and their structured
        // PropertyFeatures booleans (parking.visitorsParking, kitchens.dishwasher,
        // outsideArea.balcony, …) could never be true for any property with
        // structured spaces. These booleans answer "does the property have X
        // anywhere", so they source from the FULL feature set (flat features_json
        // ∪ every space/unit). globalFeatures() is unchanged for tags[] (phantom-
        // room-sensitive) and for the genuinely-global booleans above.
        $allFeats = $this->allFeatures($property);
        $hasAny = fn(string ...$names) => !empty(array_intersect(array_map('strtolower', $allFeats), array_map('strtolower', $names)));

        $features = [
            'garages'         => (float) ($property->garages ?? 0),
            'garden'          => $hasFeature('Garden', 'Landscaped', 'Garden Services') || $countSpaces('Garden') > 0,
            'pool'            => $hasFeature('Pool', 'Communal Pool', 'Indoor Pool', 'Splash Pool') || $countSpaces('Pool') > 0,
            'flatlet'         => $hasFeature('Flatlet') || $countSpaces('Flatlet') > 0,
            'petsAllowed'     => $hasFeature('Pet Friendly', 'Pets Allowed') ? 'Yes' : ($hasFeature('Pets Not Allowed') ? 'No' : 'DontKnow'),
            'furnishedStatus' => $hasFeature('Furnished') ? 'Yes' : ($hasFeature('Unfurnished') ? 'No' : 'No'),
        ];

        if ($property->beds) $features['bedrooms'] = (float) $property->beds;

        // Bathrooms. P24 has no separate half-bath field — BathroomsInfo.bathrooms
        // is a single float, and a half bathroom (guest toilet / cloakroom) is
        // represented as 0.5 of a bathroom. CoreX stores full baths (`baths`) and
        // half baths (`half_baths`, wizard scalar) as distinct additive counts and
        // renders the total everywhere as `baths + ½`, so the faithful P24 value is
        // baths + 0.5 per half bath (e.g. 2 full + 1 half → 2.5). Emit when EITHER
        // is set so a half-bath-only property still sends a bathroom count.
        $totalBaths = (float) ($property->baths ?? 0) + 0.5 * (int) ($property->half_baths ?? 0);
        if ($totalBaths > 0) $features['bathrooms'] = ['bathrooms' => $totalBaths];

        // Parking details from spaces/features. Amenity booleans use $hasAny —
        // parking amenities are entered on the Parking/Garage space, which
        // globalFeatures() strips (AT-146: property 6049 "Visitors Parking").
        $parkingSpaces = $countSpaces('Parking');
        if ($parkingSpaces > 0 || $hasAny('Carport', 'Secure Parking', 'Street Parking', 'Underground Parking', 'Visitors Parking', 'Shade Net Covered Parking', 'Double Parking', 'Single Parking', 'Tandem Parking', 'Triple Parking')) {
            $features['parking'] = [
                'parkingSpaces'        => $parkingSpaces > 0 ? (int) $parkingSpaces : null,
                'carport'              => $hasAny('Carport'),
                'secureParking'        => $hasAny('Secure Parking'),
                'onStreetParking'      => $hasAny('Street Parking'),
                'undergroundParking'   => $hasAny('Underground Parking'),
                'visitorsParking'      => $hasAny('Visitors Parking'),
                'shadeNetCoveredParking' => $hasAny('Shade Net Covered Parking'),
                'doubleParking'        => $hasAny('Double Parking'),
                'singleParking'        => $hasAny('Single Parking'),
                'tandemParking'        => $hasAny('Tandem Parking'),
                'tripleParking'        => $hasAny('Triple Parking'),
            ];
        }

        // Studies / offices
        $studies = $countSpaces('Study') + $countSpaces('Office');
        if ($studies > 0) $features['studies'] = (int) $studies;

        // Reception rooms — ONLY explicit "Reception Room" spaces. Lounge,
        // Dining Room and TV Room are deliberately NOT aggregated here: each
        // already surfaces as its own NAMED room via featureTags (Lounge /
        // DiningRoom / FamilyTVRoom), so also counting them as "reception rooms"
        // double-represented them and produced a "Reception Rooms N" the agent
        // never entered (property 6049: Lounge×1 + Dining×1 → phantom "Reception
        // Rooms 2"). Emitted UNCONDITIONALLY (incl. 0) so a re-push CLEARS a
        // stale count left by the old lounge+dining aggregation — P24 retains any
        // field absent from the payload (same reason internetAccess is always sent).
        $features['receptionRooms'] = (int) $countSpaces('Reception Room');

        // Domestic rooms
        $domestic = $countSpaces('Domestic Room');
        if ($domestic > 0) $features['domesticRooms'] = (int) $domestic;

        // Domestic bathrooms
        $domesticBaths = $countSpaces('Domestic Bathroom');
        if ($domesticBaths > 0) $features['domesticBathrooms'] = (float) $domesticBaths;

        // Outside toilets
        $outsideToilets = $countSpaces('Outside Toilet');
        if ($outsideToilets > 0) $features['outsideToilets'] = (int) $outsideToilets;

        // Second house / outbuildings
        $features['secondHouse'] = $countSpaces('Flatlet') > 0 || $countSpaces('Wendy House') > 0;

        // Standalone building
        if ($hasFeature('Standalone')) $features['hasStandaloneBuilding'] = true;

        // Wheelchair accessible
        if ($hasFeature('Wheelchair Friendly')) $features['isWheelchairAccessible'] = true;

        // Generator
        if ($hasFeature('Generator')) $features['hasGenerator'] = true;

        // Backup water
        if ($hasFeature('Backup Water', 'Water Tank', 'Borehole')) $features['hasBackupWater'] = true;

        // Internet access — ALWAYS sent so P24 reflects CoreX as the source of
        // truth. Only CoreX features with a true P24 InternetAccessInfo
        // equivalent are mapped; "Fast Internet" and "Wi-Fi" are generic flags
        // with NO P24 technology field, so they never set fibre/adsl/satellite
        // (inferring fibre from Fast Internet made listings show "Fibre
        // internet" on P24). The block is emitted unconditionally — including
        // all-false — so that a re-push deterministically CLEARS a stale
        // fibre/adsl/satellite a previous push set; omitting it lets P24 retain
        // the old value (P24 does not clear fields absent from the payload).
        $features['internetAccess'] = [
            'adsl'      => $hasFeature('ADSL'),
            'fibre'     => $hasFeature('Fibre'),
            'satellite' => $hasFeature('Satellite Internet', 'Satellite Dish'),
        ];

        // Sustainability
        if ($hasFeature('Solar Panel', 'Solar Geyser', 'Gas Geyser', 'Water Tank', 'Borehole', 'Backup Battery', 'Inverter')) {
            $features['sustainabilityInfo'] = [
                'solarPanels'             => $hasFeature('Solar Panel', 'Solar Heating'),
                'solarGeyser'             => $hasFeature('Solar Geyser'),
                'gasGeyser'               => $hasFeature('Gas Geyser'),
                'waterTank'               => $hasFeature('Water Tank'),
                'borehole'                => $hasFeature('Borehole'),
                'backupBatteryOrInverter' => $hasFeature('Backup Battery', 'Inverter'),
            ];
        }

        // Kitchens — emit when there's a counted Kitchen space OR a global kitchen
        // amenity that has a KitchensInfo field (so Coffee Machine / Sink /
        // Dishwasher route to PropertyFeatures, not loose tags).
        // Kitchen fittings live on the Kitchen space → $hasAny (globalFeatures strips them).
        $kitchens = $countSpaces('Kitchen');
        if ($kitchens > 0 || $hasAny('Dishwasher', 'Coffee Machine', 'Sink')) {
            $features['kitchens'] = [
                'kitchens'      => $kitchens > 0 ? (int) $kitchens : null,
                'dishwasher'    => $hasAny('Dishwasher'),
                'coffeeMachine' => $hasAny('Coffee Machine'),
                'sink'          => $hasAny('Sink'),
            ];
        }

        // Outside areas (balcony, courtyard, patio, veranda, etc.) — entered on
        // their space or a room → $hasAny (globalFeatures strips space/room copies).
        $patios = $countSpaces('Patio') + $countSpaces('Veranda') + $countSpaces('Lapa') + $countSpaces('Courtyard');
        if ($patios > 0 || $hasAny('Balcony', 'Courtyard')) {
            $features['outsideArea'] = [
                'outsideAreas' => (int) max($patios, 1),
                'balcony'      => $hasAny('Balcony'),
                'courtyard'    => $hasAny('Courtyard') || $countSpaces('Courtyard') > 0,
                'roofArea'     => false,
            ];
        }

        // Number of floors
        if ($hasFeature('Single Storey')) $features['numberOfFloors'] = 1;

        // Public transport
        if ($hasFeature('Near Bus Service', 'Near Train Service')) {
            $features['publicTransport'] = [
                'nearbyBusService'         => $hasFeature('Near Bus Service'),
                'nearbyMinibusTaxiService' => false,
                'nearbyTrainService'       => $hasFeature('Near Train Service'),
            ];
        }

        return $features;
    }

    /**
     * CoreX feature label → P24 `Tag` enum value.
     *
     * Only amenities that have NO dedicated propertyFeatures field live here —
     * everything else is already covered by buildPropertyFeatures(). Every value
     * on the right is a verified member of the P24 v53 `Tag` enum
     * (storage/p24_swagger.json); an unrecognised value would be rejected by the
     * portal, so do NOT add a mapping without confirming the enum string first.
     */
    private const FEATURE_TAG_MAP = [
        // Views / setting
        'Sea View'               => 'Sea',
        'Communal Braai Area'    => 'Communalbraaiarea',
        // Storey / floor position
        'Single Storey'          => 'SingleStorey',
        'Ground Floor Unit'      => 'GroundFloor',
        'Second Floor and Above' => 'Secondfloorandabove',
        'Top Floor'              => 'TopFloor',
        // Security
        'Alarm System'           => 'AlarmSystem',
        'Electric Gate'          => 'ElectricGate',
        'Electric Fence'         => 'Electricfencing',
        'Security Gate'          => 'SecurityGate',
        'Burglar Bars'           => 'BurglarBars',
        'CCTV'                   => 'ClosedCircuitTV',
        'Intercom'               => 'Intercom',
        '24 Hour Access'         => 'TwentyFourHourAccess',
        '24 Hour Guard'          => 'Guard',
        'Guard House'            => 'GuardHouse',
        'Boomed Area'            => 'BoomedArea',
        'Indoor Beams'           => 'IndoorBeams',
        'Outdoor Beams'          => 'OutdoorBeams',
        'Partially Fenced'       => 'PartiallyFenced',
        'Totally Fenced'         => 'TotallyFenced',
        'Totally Walled'         => 'TotallyWalled',
        'Perimeter Wall'         => 'PerimeterWall',
        'Gated Community'        => 'GatedCommunity',
        'Security Complex'       => 'SecurityComplex',
        'Security Estate'        => 'SecurityEstate',
        // Connectivity
        'Internet Port'          => 'InternetPort',
        'Telephone Port'         => 'TelephonePort',
        'TV Port'                => 'TVPort',
        'Satellite Dish'         => 'SatelliteDish',
        // Sustainability
        'Solar Heating'          => 'SolarHeating',
        'Septic Tank'            => 'SepticTank',

        // AT-P24 remediation (#9) — previously-UNROUTED features that have a
        // VERBATIM P24 Tag enum member (storage/p24_swagger.json Tag.enum).
        // Confirmed exact spelling before wiring; no semantic guesses.
        'Armed Response'         => 'TwentyFourHourResponse', // global security amenity
        'Irrigation'             => 'Irrigationsystem',       // Garden room feature
        'Sprinklers'             => 'SprinklerSystem',        // Garden room feature

        // AT-102/AT-103 coverage audit — clean 1:1 CoreX feature ↔ P24 Tag enum pairings
        // that previously never syndicated (verified exact members of
        // storage/p24_swagger.json components.schemas.Tag.enum). Room-detail / kitchen /
        // bathroom / pool / floor / outdoor features. Excludes any feature already carried
        // by a dedicated propertyFeatures field (Carport/Secure/Underground/Visitors
        // Parking → parking{}, Landscaped/Garden Services → garden) per the rule above.
        // As of AT-146 (2026-07-02) the ONLY CoreX feature labels still unmapped
        // are those with NO P24 Tag enum member at all: Cable TV, Wi-Fi, Washing
        // Machine, and tenure/marketing labels (Freehold, Leasehold, Sectional
        // Title, Investment, Serviced, Executive, In Unit, Unisex, Cleaning
        // Service, Renovation Fixer-Upper, In Security). There is nothing to send
        // for these — P24 has no field or tag for them.
        //
        // AT-103 follow-up — P24 Tag member verified verbatim in Tag.enum AND the
        // CoreX feature string confirmed in config/property-spaces.php: "Air
        // Conditioned" is the real label (General + theProperty groups).
        'Air Conditioned' => 'AirConditioningUnit',
        'Auto Cleaning Equipment' => 'AutoCleaningEquipment',
        'Basin' => 'Basin',
        'Bath' => 'Bath',
        'Bidet' => 'Bidet',
        'Breakfast Nook' => 'BreakfastNook',
        'Built-In Braai' => 'Built_inBraai',
        'Built-in Cupboards' => 'Built_inCupboards',
        'Chlorinator' => 'Chlorinator',
        'Communal' => 'Communal',
        'Covered' => 'Covered',
        'Dishwasher Connection' => 'DishwasherConnection',
        'Double Basin' => 'DoubleBasin',
        'En-suite' => 'EnSuite',
        'Extractor Fan' => 'ExtractorFan',
        'Eye Level Oven' => 'EyeLevelOven',
        'Fan' => 'Fan',
        'Fenced' => 'Fenced',
        'Fridge' => 'Fridge',
        'Garbage Disposal' => 'GarbageDisposal',
        'Garden Terrace' => 'GardenTerrace',
        'Gas Hob' => 'GasHob',
        'Gas Oven' => 'GasOven',
        'Granite Tops' => 'GraniteTops',
        'Grill' => 'Grill',
        'Guest Toilet' => 'GuestToilet',
        'Half Bathroom' => 'HalfBathroom',
        'Heated' => 'Heated',
        'Hob' => 'Hob',
        'Icemaker' => 'Icemaker',
        'Jacuzzi Bath' => 'JacuzziBath',
        'Laminated Floors' => 'LaminatedFloors',
        'Lighting' => 'Lighting',
        'Main en-suite' => 'MainenSuite',
        'Oven and Hob' => 'OvenAndHob',
        'Pantry' => 'Pantry',
        'Parquet Floors' => 'ParquetFloors',
        'Pizza Oven' => 'PizzaOven',
        'Safe' => 'Safe',
        'Safety Net' => 'SafetyNet',
        'Separate Toilet' => 'SeparateToilet',
        'Shower' => 'Shower',
        'Tiled Floors' => 'TiledFloors',
        'Toilet' => 'Toilet',
        'Tumble Dryer' => 'TumbleDryer',
        'Under Counter Oven' => 'UnderCounterOven',
        'Underfloor Heating' => 'UnderfloorHeating',
        'Urinal' => 'Urinal',
        'Vinyl Floors' => 'VinylFloors',
        'Walk in Closet' => 'Walk_in_closet',
        'Washing Machine Connection' => 'WashingMachineConnection',
        'Water Cooler' => 'WaterCooler',
        'Water Feature' => 'WaterFeature',
        'Wooden Floors' => 'WoodenFloors',
        'Zen Garden' => 'ZenGarden',
        'Zinc' => 'Zinc',

        // ── AT-146 (Johan 2026-07-02) — full CoreX ↔ P24 feature coverage ─────
        // Every remaining CoreX feature label from config/property-spaces.php
        // that has a VERBATIM P24 Tag enum member (storage/p24_swagger.json,
        // components.schemas.Tag.enum — each string confirmed present before
        // wiring). These are room-fabric / room-fitting descriptors: they ride a
        // room's featureTags[] via buildFeatureTags(), and ROOM_DETAIL_ONLY_TAGS
        // keeps every one of them OUT of the top-level tags[] array, so a legacy
        // global copy in features_json can never render as a phantom room (the
        // #1322 TVPort class of bug). The ONLY exception below is ElectricGarage:
        // "Automated Garage Doors" is a global Security-category feature in CoreX,
        // so it stays top-level-eligible (it needs a listing-level home when it is
        // not attached to a Garage space).
        // Floors
        'Carpet'                => 'Carpets',
        // Walls
        'Brick Wall'            => 'Brick',
        'Concrete Wall'         => 'ConcreteWallOptions',
        'Plaster Wall'          => 'Plaster',
        'Wood Wall'             => 'WoodWallOptions',
        'Stone Wall'            => 'Stone',
        'Glass Wall'            => 'Glass',
        // Windows & doors
        'Aluminium Windows'     => 'AluminiumWindowOptions',
        'Bay Windows'           => 'Bay',
        'Blinds'                => 'Blinds',
        'Cottage Windows'       => 'CottageWindowOptions',
        'Curtain Rails'         => 'CurtainRails',
        'Double Glazed Windows' => 'DoubleGlazed',
        'Lead Windows'          => 'Lead',
        'Picture Windows'       => 'Picture',
        'Sash Windows'          => 'Sash',
        'Skylight Window'       => 'SkylightWindowOptions',
        'Stained Windows'       => 'Stained',
        'Steel Windows'         => 'Steel',
        'Wood Windows'          => 'WoodWindowOptions',
        'Sliding Doors'         => 'SlidingDoors',
        'Rollup Door'           => 'Rollup',
        'Tipup Door'            => 'Tipup',
        // Beds
        'Double Bed'            => 'DoubleBed',
        'King Bed'              => 'KingBed',
        'Queen Bed'            => 'QueenBed',
        'Single Bed'            => 'SingleBed',
        'Twin Bed'              => 'TwinBed',
        // Pool types (Communal Pool / Splash Pool also set pool=true via the
        // PropertyFeatures route; here they enrich the Pool room's featureTags).
        'Fibreglass in Ground'  => 'FibreglassinGround',
        'Portapool'             => 'Portapool',
        'Rock Pool'             => 'RockPool',
        'Communal Pool'         => 'CommunalPool',
        'Splash Pool'           => 'SplashPool',
        // Bathroom
        'Full Bathroom'         => 'Full',
        // Room-context pairings — Johan-approved best-judgment enum member
        // (2026-07-02): the room-scoped variant, not the Style/EntranceHall/
        // TemperatureControl homonyms.
        'Fireplace'             => 'FireplaceRoomOptions',
        'Open Plan'             => 'OpenPlanRoomOptions',
        // Garage size / doors — Johan-approved (2026-07-02).
        'Double Garage'         => 'Double',
        'Single Garage'         => 'Single',
        'Tandem Garage'         => 'Tandem',
        'Automated Garage Doors'=> 'ElectricGarage',
    ];

    /**
     * CoreX GLOBAL feature labels that have a dedicated PropertyFeatures field
     * (see buildPropertyFeatures()). Per the P24 contract
     * (.ai/specs/p24-featuretags-contract.md), these populate the structured
     * External Features / Building / Other Features sections via PropertyFeatures
     * — so they MUST NOT also be emitted as a loose top-level tag[]. The
     * top-level tags[] array carries ONLY mapped global features that have NO
     * PropertyFeatures home (security/connectivity amenities, descriptive tags).
     *
     * Lower-cased. Keep in sync with the hasFeature() routes in
     * buildPropertyFeatures(). This is the class-level routing boundary — no
     * per-feature special-casing in buildTags().
     */
    private const PROPERTY_FEATURE_LABELS = [
        'adsl', 'backup battery', 'backup water', 'balcony', 'borehole',
        'carport', 'coffee machine', 'communal pool', 'courtyard', 'dishwasher',
        'double parking', 'fibre', 'flatlet', 'furnished', 'garden',
        'garden services', 'gas geyser', 'generator', 'indoor pool', 'inverter',
        'landscaped', 'near bus service', 'near train service', 'pet friendly',
        'pets allowed', 'pets not allowed', 'pool', 'satellite dish',
        'satellite internet', 'secure parking', 'shade net covered parking',
        'single parking', 'single storey', 'sink', 'solar geyser',
        'solar heating', 'solar panel', 'splash pool', 'standalone',
        'street parking', 'tandem parking', 'triple parking',
        'underground parking', 'unfurnished', 'visitors parking', 'water tank',
        'wheelchair friendly',
    ];

    /**
     * P24 `Tag` enum members that are ROOM-DETAIL descriptors only — they describe
     * a connectivity point INSIDE a specific room and have NO valid listing-level
     * meaning. In the swagger Tag enum they sit in the room-options neighbourhood
     * (alongside BalconyRoomOptions / FireplaceRoomOptions / OpenPlanRoomOptions —
     * storage/p24_swagger.json). Emitted as a loose top-level `tags[]` entry, P24
     * renders each as a standalone feature ROW that reads as a phantom room (a
     * global "TV Port" shows up as a "TV Port" room — the AT-P24 bug on listing
     * #1322). They are valid ONLY inside a room's `featureTags[].tags`, where
     * buildFeatureTags() already places them when the feature is attached to a
     * space. So buildTags() filters them out of the top-level array. They are
     * deliberately KEPT in FEATURE_TAG_MAP — the per-room path still needs them.
     *
     * Resolves the §4b.2 [OPEN] in .ai/specs/p24-featuretags-contract.md for the
     * connectivity-port family: top-level tags[] is the WRONG home (Option A is
     * rejected for these); room featureTags[] is the only correct one.
     */
    private const ROOM_DETAIL_ONLY_TAGS = [
        // Connectivity ports (original #1322 fix).
        'InternetPort', 'TelephonePort', 'TVPort',

        // AT-146 (Johan 2026-07-02) — room-fabric / room-fitting descriptors.
        // Each is a valid Tag enum member that describes a feature INSIDE a room
        // (a floor, wall, window, door, bed, pool type, bathroom grade, fireplace,
        // layout, garage size). They belong in a room's featureTags[].tags, where
        // buildFeatureTags() places them; at listing level P24 renders each as a
        // phantom room. They are KEPT in FEATURE_TAG_MAP (the per-room path needs
        // them) and filtered out of the top-level tags[] array here.
        // Floors
        'Carpets',
        // Walls
        'Brick', 'ConcreteWallOptions', 'Plaster', 'WoodWallOptions', 'Stone', 'Glass',
        // Windows & doors
        'AluminiumWindowOptions', 'Bay', 'Blinds', 'CottageWindowOptions', 'CurtainRails',
        'DoubleGlazed', 'Lead', 'Picture', 'Sash', 'SkylightWindowOptions', 'Stained',
        'Steel', 'WoodWindowOptions', 'SlidingDoors', 'Rollup', 'Tipup',
        // Beds
        'DoubleBed', 'KingBed', 'QueenBed', 'SingleBed', 'TwinBed',
        // Pool types (not otherwise routed via PropertyFeatures)
        'FibreglassinGround', 'Portapool', 'RockPool',
        // Bathroom grade
        'Full',
        // Room-context homonyms + garage size
        'FireplaceRoomOptions', 'OpenPlanRoomOptions', 'Double', 'Single', 'Tandem',
        // Garden room fittings (were mapped but leaking to top-level pre-AT-146).
        'Irrigationsystem', 'SprinklerSystem',
    ];

    /**
     * AT-102/AT-103 — CoreX space type → P24 FeatureType enum (storage/p24_swagger.json).
     * Drives featureTags[] so each room shows as a separate NAMED room on P24. Only
     * confident, direct equivalents are mapped; CoreX space types with no clean P24
     * FeatureType (Patio, Courtyard, Veranda, Lapa, Domestic Room/Bathroom, Outside
     * Toilet, Flatlet, Wendy House, …) are skipped and logged — never guessed.
     */
    private const SPACE_TYPE_TO_P24_FEATURETYPE = [
        'Bedroom'       => 'Bedroom',
        'Bathroom'      => 'Bathroom',
        'Garage'        => 'Garage',
        'Parking'       => 'Parking',
        'Kitchen'       => 'Kitchen',
        'Garden'        => 'Garden',
        'Pool'          => 'Pool',
        'Lounge'        => 'Lounge',
        'Dining Room'   => 'DiningRoom',
        'TV Room'       => 'FamilyTVRoom',
        'Entrance Hall' => 'EntranceHall',
        'Study'         => 'Office',
        'Office'        => 'Office',
        'Bar'           => 'Bar',
        'Braai Room'    => 'BraaiRoom',
        'Loft'          => 'Loft',
        'Closet'        => 'Closet',
        'Outbuilding'   => 'Outbuilding',
    ];

    /**
     * Top-level P24 `tags[]` per the contract (.ai/specs/p24-featuretags-contract.md):
     * GLOBAL features that map to a P24 Tag enum member AND have NO
     * PropertyFeatures field. Amenities WITH a PropertyFeatures field are routed
     * there by buildPropertyFeatures() (External/Building/Other Features) and are
     * excluded here so they never appear as a loose tag. Per-room features are NOT
     * here either — they ride their room's featureTags[] entry. Case-insensitive
     * match against FEATURE_TAG_MAP; deduped; valid Tag enum members only.
     */
    private function buildTags(Property $property): array
    {
        $feats = $this->globalFeatures($property);
        if (empty($feats)) {
            return [];
        }

        // Lower-cased lookup so a stored 'sea view' still resolves to 'Sea View'.
        $lookup = [];
        foreach (self::FEATURE_TAG_MAP as $label => $tag) {
            $lookup[strtolower($label)] = $tag;
        }
        $propertyFeatureLabels = array_flip(self::PROPERTY_FEATURE_LABELS);
        $roomDetailOnly = array_flip(self::ROOM_DETAIL_ONLY_TAGS);

        $tags = [];
        foreach ($feats as $feat) {
            $key = strtolower(trim((string) $feat));
            // Amenities with a PropertyFeatures field are routed there, not here.
            if (isset($propertyFeatureLabels[$key])) {
                continue;
            }
            if (isset($lookup[$key])) {
                $tag = $lookup[$key];
                // Room-detail connectivity ports (TVPort/InternetPort/TelephonePort)
                // have NO valid listing-level home — at top level P24 renders them
                // as phantom rooms. They ride a room's featureTags[].tags only.
                if (isset($roomDetailOnly[$tag])) {
                    continue;
                }
                $tags[] = $tag;
            }
        }

        return array_values(array_unique($tags));
    }

    /**
     * AT-103 — the GLOBAL-ONLY feature set for tags[] + property-level booleans.
     *
     * global = features_json MINUS room-ONLY features, where a room-ONLY feature is one
     * that appears on a room (spaces['spaces'][].units[].features or a space's
     * featuresAll) AND is NOT in the explicit property feature-screen selection
     * (spaces['features']). A feature set BOTH globally and on a room STAYS global
     * (decision A — it also appears in featureTags[]).
     *
     * NB we do NOT use spaces['features'] as the sole source: it is empty/partial for
     * a large share of properties (imports + legacy edits store global features only in
     * the flat features_json with no per-room provenance). Subtracting only the
     * room-attributable features keeps those genuinely-global features intact (no
     * tags[] regression) while still stripping per-room-only leaks.
     *
     * @return string[]
     */
    private function globalFeatures(Property $property): array
    {
        $flat = array_values(array_unique(array_filter(
            array_map('strval', (array) ($property->features_json ?? [])),
            fn ($v) => trim($v) !== ''
        )));

        $sj = $property->spaces_json;
        $spaces = is_array($sj) ? ($sj['spaces'] ?? (isset($sj[0]) ? $sj : [])) : [];
        if (empty($spaces)) {
            return $flat; // legacy / no structured rooms — features_json is the global set
        }

        // Explicit property-screen global selection (may be empty for imports/legacy).
        $explicitGlobal = [];
        foreach (($sj['features'] ?? []) as $catArr) {
            $vals = is_array($catArr) ? $catArr : [$catArr];
            foreach ($vals as $f) {
                if (filled($f)) $explicitGlobal[strtolower(trim((string) $f))] = true;
            }
        }

        // Features attributable to a room (per-unit + space-level).
        $roomFeatures = [];
        foreach ($spaces as $sp) {
            foreach (($sp['featuresAll'] ?? []) as $f) {
                if (filled($f)) $roomFeatures[strtolower(trim((string) $f))] = true;
            }
            foreach (($sp['units'] ?? []) as $u) {
                foreach (($u['features'] ?? []) as $f) {
                    if (filled($f)) $roomFeatures[strtolower(trim((string) $f))] = true;
                }
            }
        }

        return array_values(array_filter($flat, function ($f) use ($roomFeatures, $explicitGlobal) {
            $k = strtolower(trim((string) $f));
            $roomOnly = isset($roomFeatures[$k]) && !isset($explicitGlobal[$k]);
            return !$roomOnly; // keep global + both-set; drop room-only
        }));
    }

    /**
     * AT-146 — the COMPLETE feature set a property carries: the flat features_json
     * UNION every space-level featuresAll and every per-unit feature. Unlike
     * globalFeatures() this does NOT strip room/space-attributable features, so it
     * is the correct source for "does the property have amenity X anywhere"
     * PropertyFeatures booleans (parking / kitchen fittings / outside areas) that
     * are entered on a dedicated space and would otherwise be invisible. Never
     * used for top-level tags[] (that stays globalFeatures() to avoid phantom rooms).
     *
     * @return string[]
     */
    private function allFeatures(Property $property): array
    {
        $all = array_map('strval', (array) ($property->features_json ?? []));

        $sj = $property->spaces_json;
        $spaces = is_array($sj) ? ($sj['spaces'] ?? (isset($sj[0]) ? $sj : [])) : [];
        foreach ($spaces as $sp) {
            foreach (($sp['featuresAll'] ?? []) as $f) {
                $all[] = (string) $f;
            }
            foreach (($sp['units'] ?? []) as $u) {
                foreach (($u['features'] ?? []) as $f) {
                    $all[] = (string) $f;
                }
            }
        }

        return array_values(array_unique(array_filter($all, fn ($v) => trim($v) !== '')));
    }

    /**
     * AT-102/AT-103 — build P24 featureTags[] so each room shows as a separate NAMED
     * room with its per-room features attached (the display agents expect). When a space
     * carries per-unit features, one entry per unit (Bedroom 1/2/3…) is emitted, each
     * carrying that unit's own features UNION the space-level featuresAll; when it does
     * not, one entry carries the space-level featuresAll. Both feature sources are mapped
     * via FEATURE_TAG_MAP. Unmapped feature labels and unmapped CoreX space types are
     * skipped and logged — never guessed. receptionRooms count is left untouched.
     *
     * @return array<int, array<string, mixed>>
     */
    private function buildFeatureTags(Property $property): array
    {
        $sj = $property->spaces_json;
        $spaces = is_array($sj) ? ($sj['spaces'] ?? (isset($sj[0]) ? $sj : [])) : [];

        $tagLookup = [];
        foreach (self::FEATURE_TAG_MAP as $label => $tag) {
            $tagLookup[strtolower($label)] = $tag;
        }

        $skippedTags = [];
        $mapRoomFeatures = function (array $features) use ($tagLookup, &$skippedTags): array {
            $tags = [];
            foreach ($features as $f) {
                $key = strtolower(trim((string) $f));
                if ($key === '') continue;
                if (isset($tagLookup[$key])) {
                    $tags[] = $tagLookup[$key];
                } else {
                    $skippedTags[] = (string) $f;
                }
            }
            return array_values(array_unique($tags));
        };

        $featureTags = [];
        $skippedSpaceTypes = [];

        foreach ($spaces as $sp) {
            $type = $sp['type'] ?? null;
            if (!$type) {
                continue;
            }
            $featureType = self::SPACE_TYPE_TO_P24_FEATURETYPE[$type] ?? null;
            if ($featureType === null) {
                $skippedSpaceTypes[] = (string) $type;
                continue;
            }

            // A space carries features in two places: space-level `featuresAll`
            // (apply to the whole space / every unit) and per-unit `features`
            // (specific to one unit). The room's feature set is the UNION.
            $spaceFeatures = $sp['featuresAll'] ?? [];
            $units         = $sp['units'] ?? [];
            $anyUnitFeatures = false;
            foreach ($units as $u) {
                if (!empty($u['features'] ?? [])) { $anyUnitFeatures = true; break; }
            }

            if ($anyUnitFeatures) {
                // Per-unit detail present → one named room per unit, each carrying
                // its OWN features PLUS the space-level featuresAll.
                foreach ($units as $u) {
                    $tags = $mapRoomFeatures(array_merge($spaceFeatures, $u['features'] ?? []));
                    // A room with no mapped features is pure noise on P24
                    // ("Bedroom 1 → Bedroom 1"). Emit an entry ONLY when the room
                    // actually carries >=1 feature. The room count itself is already
                    // conveyed via propertyInfo (bedrooms/bathrooms/etc.).
                    if (empty($tags)) {
                        continue;
                    }
                    // P24 labels the row from featureType ("Bedroom"). The unit
                    // label ("Bedroom 1") is the ROOM NAME — putting it in
                    // description duplicates the row label. Per the contract
                    // description is feature-prose only, and units carry no prose
                    // field, so description is omitted here.
                    $featureTags[] = ['featureType' => $featureType, 'tags' => $tags];
                }
            } else {
                // No per-unit detail anywhere — either the space has no units, or
                // every unit is empty and the agent entered the features at the
                // SPACE level (featuresAll). Emit ONE room from featuresAll.
                //
                // AT-146 (property 6049): this branch previously ran ONLY when a
                // space had literally zero units, so a space with an auto-created
                // empty unit (Kitchen/Lounge/Garage/Parking) silently DROPPED its
                // entire featuresAll set — the agent's Kitchen (Oven & Hob, Pantry,
                // Extractor Fan, …), Lounge and Garage features never reached P24.
                $tags = $mapRoomFeatures($spaceFeatures);
                if (empty($tags)) {
                    continue; // no features = no row
                }
                $entry = ['featureType' => $featureType, 'tags' => $tags];
                // description = genuine free-text/condition prose ONLY (never the
                // room name). descriptionAll is the space-level prose field.
                $desc = trim((string) ($sp['descriptionAll'] ?? ''));
                if ($desc !== '') {
                    $entry['description'] = $desc;
                }
                $featureTags[] = $entry;
            }
        }

        // NOTE: global amenities are NOT emitted as featureTags here. Those with a
        // PropertyFeatures field go to buildPropertyFeatures() (External/Building/
        // Other Features); those without go to top-level tags[] via buildTags().
        // featureType "Other" is never sent — P24 renders it as a junk room row.

        if (!empty($skippedTags) || !empty($skippedSpaceTypes)) {
            // Logging is best-effort — it must never break the mapping (and the logger
            // isn't booted in pure unit contexts).
            try {
                \Illuminate\Support\Facades\Log::channel('property24')->info(
                    'P24 featureTags — skipped unmapped items',
                    [
                        'property_id'         => $property->id,
                        'skipped_tags'        => array_values(array_unique($skippedTags)),
                        'skipped_space_types' => array_values(array_unique($skippedSpaceTypes)),
                    ]
                );
            } catch (\Throwable $e) {
                // no-op — never block syndication on a log write
            }
        }

        return $featureTags;
    }

    public function validate(array $payload): array
    {
        $errors = [];
        if (empty($payload['agencyId'])) $errors[] = 'No Property24 agency ID resolved — set it on the agency or branch.';
        // AT-P24 remediation (#3): P24 rejects a listing with no agents
        // ("A listing must have one or more agents"). Fail locally with an
        // actionable reason instead of letting the empty array reach P24. An
        // empty contactAgentIds means the listing agent has no P24 profile under
        // this agency yet (or the /agents lookup timed out) — register/sync the
        // agent to P24, then re-syndicate.
        if (empty($payload['contactAgentIds'])) {
            $errors[] = 'No Property24 agent linked — the listing agent is not registered on Property24 under this agency (or the agent lookup failed). Sync the agent to P24, then re-syndicate.';
        }
        if (empty($payload['description'])) $errors[] = 'Description is required';
        if (empty($payload['propertyInfo']['suburbId'])) $errors[] = 'Suburb unmapped — manual P24 suburb mapping required. Pick a Property24-recognised suburb on the property (Province → City → Suburb), then re-syndicate.';
        if (empty($payload['propertyInfo']['propertyTypeId'])) $errors[] = 'Property type could not be mapped to a P24 type ID';
        return $errors;
    }

    public function checkReadiness(Property $property): array
    {
        $missing = [];
        if (empty($property->description)) $missing[] = ['field' => 'description', 'label' => 'Description'];
        if (empty($property->suburb)) {
            $missing[] = ['field' => 'suburb', 'label' => 'Suburb'];
        } else {
            if (!$this->resolveSuburbId($property)) {
                $missing[] = ['field' => 'suburb_id', 'label' => 'Suburb not mapped to P24 ID (set in P24 Suburb Settings)'];
            }
        }
        if (empty($property->property_type)) $missing[] = ['field' => 'property_type', 'label' => 'Property Type'];
        if ($property->effectivePrice() <= 0 && !$property->price_on_application) $missing[] = ['field' => 'price', 'label' => 'Price (or enable Price On Application)'];
        if (empty($property->allImages())) $missing[] = ['field' => 'images', 'label' => 'At least one photo'];
        if (empty($property->listing_type) && empty($property->mandate_type)) $missing[] = ['field' => 'listing_type', 'label' => 'Listing Type (Sale/Rental)'];
        if (empty($property->resolveP24AgencyId())) {
            $missing[] = [
                'field' => 'p24_agency_id',
                'label' => 'Property24 agency ID not configured on branch or agency',
            ];
        }
        return $missing;
    }

    /**
     * Resolve the P24 agency ID for a property. Branch override > agency default.
     * Throws when neither is set so submission fails loudly rather than
     * silently routing to the wrong profile (or the wrong tenant).
     */
    private function resolveP24AgencyId(Property $property): int
    {
        $resolved = $property->resolveP24AgencyId();
        if ($resolved === null || $resolved === '') {
            $branchName = $property->branch?->name ?? '(no branch)';
            $agencyName = $property->agency?->name ?? $property->branch?->agency?->name ?? '(no agency)';
            throw new Property24ConfigurationException(
                "Property #{$property->id} cannot be syndicated: no Property24 agency ID on "
                . "branch '{$branchName}' or agency '{$agencyName}'."
            );
        }
        return (int) $resolved;
    }

    private function buildPhotos(Property $property): array
    {
        $photos = [];
        $catData = $property->gallery_categories_json;

        // Build a map of image URL → category name for captions
        $captionMap = [];
        if ($catData && isset($catData['categories'])) {
            foreach ($catData['categories'] as $cat) {
                foreach ($cat['images'] ?? [] as $img) {
                    $captionMap[$img] = $cat['name'];
                }
            }
        }

        // AT-101: per-agency photo cap. Source = syndicationImages() (the exact
        // gallery the agent curates and sees, gallery_images_json), NOT allImages()
        // — allImages() additionally merges images_json (a divergent public mirror)
        // and the dawn/noon/dusk sets, over-counting photos the user never put in
        // the gallery (e.g. property #1322: gallery 45 vs allImages 68). What goes
        // to P24 must equal the CoreX gallery.
        $maxPhotos = $property->agency?->p24MaxPhotos() ?? Agency::P24_DEFAULT_MAX_PHOTOS;
        $allImages = $property->syndicationImages();

        // AT-P24 remediation (#7): never silently truncate. If the curated
        // gallery exceeds the agency photo cap, log a warning naming the
        // dropped count so an over-cap listing is visible (e.g. property 3361:
        // 160 → 150, 10 dropped) rather than quietly losing photos.
        if (count($allImages) > $maxPhotos) {
            try {
                Log::channel('property24')->warning(
                    'P24 photo cap exceeded — photos dropped from submission',
                    [
                        'property_id' => $property->id,
                        'gallery'     => count($allImages),
                        'cap'         => $maxPhotos,
                        'dropped'     => count($allImages) - $maxPhotos,
                    ]
                );
            } catch (\Throwable $e) {
                // never block syndication on a log write
            }
        }

        $images = array_slice($allImages, 0, $maxPhotos);

        // Read the raw bytes for every resolvable image first (one disk read
        // each) so the payload can be size-checked before base64 encoding.
        $raw = [];
        foreach ($images as $imagePath) {
            if (empty($imagePath)) continue;

            $diskPath = $this->urlToDiskPath($imagePath);

            if ($diskPath && Storage::disk('public')->exists($diskPath)) {
                $bytes = Storage::disk('public')->get($diskPath);
                if (empty($bytes)) continue;

                $raw[] = [
                    'bytes'   => $bytes,
                    'mime'    => Storage::disk('public')->mimeType($diskPath) ?: 'image/jpeg',
                    'caption' => $captionMap[$imagePath] ?? null,
                ];
            }
        }

        // P24 hard-caps a submit at 60MB of image data. If the set overflows
        // the budget, downscale the oversized images to their fair share so the
        // whole gallery fits — never drop a photo, never fail the submit.
        $raw = $this->fitPhotosToPayloadBudget($raw, $property);

        foreach ($raw as $entry) {
            $photos[] = [
                'bytes'           => base64_encode($entry['bytes']),
                'mimeContentType' => $entry['mime'],
                'caption'         => $entry['caption'],
                'isFloorPlan'     => false,
            ];
        }

        return $photos;
    }

    /**
     * Keep a property's combined photo payload under the P24 60MB cap. Budgets
     * on the base64-encoded size (what is actually transmitted); when the set
     * already fits, returns it untouched (the common case — no re-encoding, full
     * quality). When it overflows, gives every photo an equal share of the
     * budget and re-encodes only those over their share, so all photos survive.
     *
     * @param array<int,array{bytes:string,mime:string,caption:?string}> $raw
     * @return array<int,array{bytes:string,mime:string,caption:?string}>
     */
    private function fitPhotosToPayloadBudget(array $raw, Property $property): array
    {
        if (empty($raw)) {
            return $raw;
        }

        // Exact standard-base64 encoded length of a raw byte string.
        $b64Len = static fn(string $b): int => intdiv(strlen($b) + 2, 3) * 4;

        $total = array_sum(array_map(fn($e) => $b64Len($e['bytes']), $raw));
        if ($total <= self::P24_IMAGE_PAYLOAD_BUDGET_BYTES) {
            return $raw;
        }

        // Fair per-image share of the budget (in base64 bytes), converted to a
        // raw-byte target the GD encoder packs to.
        $perImageB64 = intdiv(self::P24_IMAGE_PAYLOAD_BUDGET_BYTES, count($raw));
        $rawTarget   = intdiv($perImageB64 * 3, 4);
        $compressed  = 0;

        foreach ($raw as $i => $entry) {
            if ($b64Len($entry['bytes']) <= $perImageB64) {
                continue; // already within its share — leave at full quality
            }

            $shrunk = $this->compressImageToBytes($entry['bytes'], $rawTarget);
            if ($shrunk !== null) {
                $raw[$i]['bytes'] = $shrunk;
                $raw[$i]['mime']  = 'image/jpeg';
                $compressed++;
            }
        }

        $after = array_sum(array_map(fn($e) => $b64Len($e['bytes']), $raw));

        try {
            Log::channel('property24')->warning(
                'P24 image payload exceeded 60MB cap — photos downscaled to fit',
                [
                    'property_id'      => $property->id,
                    'photos'           => count($raw),
                    'compressed'       => $compressed,
                    'before_b64_bytes' => $total,
                    'after_b64_bytes'  => $after,
                    'budget_bytes'     => self::P24_IMAGE_PAYLOAD_BUDGET_BYTES,
                ]
            );
        } catch (\Throwable $e) {
            // never block syndication on a log write
        }

        return $raw;
    }

    /**
     * Re-encode an image via GD to at most $maxBytes (raw JPEG). Steps quality
     * down at full resolution first, then progressively downscales, until it
     * fits. Returns the smallest result achieved (guaranteed under budget for
     * any real photo); returns null only when GD cannot decode the source, in
     * which case the caller keeps the original bytes.
     */
    private function compressImageToBytes(string $bytes, int $maxBytes): ?string
    {
        if ($maxBytes < 1 || ! function_exists('imagecreatefromstring')) {
            return null;
        }

        $src = @imagecreatefromstring($bytes);
        if (! $src instanceof \GdImage) {
            return null;
        }

        $w = imagesx($src);
        $h = imagesy($src);
        $best = null;

        foreach ([1.0, 0.8, 0.6, 0.45, 0.33, 0.25] as $scale) {
            $tw = max(1, (int) round($w * $scale));
            $th = max(1, (int) round($h * $scale));

            $dst = ($scale === 1.0) ? $src : imagecreatetruecolor($tw, $th);
            if ($dst !== $src) {
                imagecopyresampled($dst, $src, 0, 0, 0, 0, $tw, $th, $w, $h);
            }

            for ($q = 80; $q >= 40; $q -= 10) {
                ob_start();
                imagejpeg($dst, null, $q);
                $out = (string) ob_get_clean();
                $best = $out; // each step is smaller than the last

                if (strlen($out) <= $maxBytes) {
                    if ($dst !== $src) imagedestroy($dst);
                    imagedestroy($src);
                    return $out;
                }
            }

            if ($dst !== $src) imagedestroy($dst);
        }

        imagedestroy($src);
        return $best; // smallest achievable — still far below the original
    }

    /**
     * Convert a Storage::url() path back to a disk-relative path.
     * e.g. "/storage/properties/16/file.jpg" => "properties/16/file.jpg"
     * or "https://domain.com/storage/properties/16/file.jpg" => "properties/16/file.jpg"
     */
    private function urlToDiskPath(string $url): ?string
    {
        // Strip domain if full URL
        if (str_starts_with($url, 'http://') || str_starts_with($url, 'https://')) {
            $parsed = parse_url($url);
            $url = $parsed['path'] ?? $url;
        }

        // Strip the /storage/ prefix that Storage::url() adds
        if (str_contains($url, '/storage/')) {
            return substr($url, strpos($url, '/storage/') + 9); // 9 = strlen('/storage/')
        }

        // If it's already a relative path like "properties/16/file.jpg"
        if (str_starts_with($url, 'properties/')) {
            return $url;
        }

        return null;
    }

    /**
     * Resolve the P24 numeric suburb ID (p24_suburbs.p24_id) to send in the
     * payload. Order: trust the stored, chain-verified FK; then a name match
     * that is DISAMBIGUATED BY CITY/PROVINCE and only ever accepted when it
     * resolves to exactly ONE suburb. We never guess between same-named
     * suburbs in different cities — returning null makes the caller skip
     * syndication and flag the property for manual mapping (AT-104).
     *
     * Background (AT-104): "Glenmore" exists in P24 in both Durban (id 10787)
     * and Port Edward / South Coast (id 10790). The previous resolver checked
     * `pp_suburb_id` (a Private Property column that is NULL on every CoreX
     * property, so the branch never fired) and then fell through to a bare
     * `P24Suburb::lookup()->first()` with no city filter — sending the Durban
     * Glenmore for every South Coast Glenmore. This rewrite kills that class
     * of bug for all 30+ multi-city collision suburb names, not just Glenmore.
     */
    private function resolveSuburbId(Property $property): ?int
    {
        // TIER 1 — trust the stored, chain-verified P24 suburb FK. The property
        // create/edit form and the wizard write `p24_suburb_id` only after
        // AppliesP24Location has verified the suburb→city→province chain against
        // P24's own hierarchy, so it is the authoritative mapping. NEVER fall
        // through to name guessing when it is set — that is the bug we are fixing.
        //
        // AT-P24 remediation (#2): the p24_id is only returned when its
        // p24_suburbs row is P24-VERIFIED (p24_verified_at set by the daily
        // p24:sync-locations stamp-and-sweep). An unverified row carries a
        // p24_id that P24's listing API may reject ("Value [N] for property
        // listing.SuburbId is invalid" — e.g. Addington 5997), so we never send
        // it. Soft-deleted rows are already excluded by the SoftDeletes scope.
        if ($property->p24_suburb_id) {
            $suburb = P24Suburb::find($property->p24_suburb_id);
            if ($suburb && $suburb->p24_id && $suburb->p24_verified_at !== null) {
                return (int) $suburb->p24_id;
            }
        }

        if (!$property->suburb) return null;

        // TIER 2 — exact name match, disambiguated by city/province, unique-only.
        $exact = $this->resolveUniqueLocalSuburb($property, false);
        if ($exact && $exact->p24_id) return (int) $exact->p24_id;

        // TIER 3 — fuzzy name match (handles trailing "Beach", punctuation, extra
        //          whitespace, …), same city/province constraint, same unique rule.
        $fuzzy = $this->resolveUniqueLocalSuburb($property, true);
        if ($fuzzy && $fuzzy->p24_id) return (int) $fuzzy->p24_id;

        // TIER 4 — no unique, city-qualified match. Do NOT guess and do NOT fall
        // back to a name-only API lookup (it would re-introduce the wrong-city
        // bug). Return null so submitListing()'s validate() flags the property
        // ("Suburb unmapped — manual P24 suburb mapping required") and skips it.
        return null;
    }

    /**
     * Resolve the property's suburb to exactly ONE P24Suburb row, disambiguated
     * by city/province. Returns null when zero — or MORE THAN ONE — candidate
     * survives, so we never guess between same-named suburbs in different
     * cities. $fuzzy widens the name match from exact to LIKE.
     */
    private function resolveUniqueLocalSuburb(Property $property, bool $fuzzy): ?P24Suburb
    {
        $candidates = $this->suburbNameCandidates((string) $property->suburb, $fuzzy);
        if ($candidates->isEmpty()) return null;
        if ($candidates->count() === 1) return $candidates->first();

        // Multiple same-named suburbs across cities — keep only those in a city
        // this property could legitimately belong to.
        $cityIds = $this->candidateCityIds($property);
        if (empty($cityIds)) return null; // no city signal → cannot disambiguate

        $filtered = $candidates->whereIn('p24_city_id', $cityIds)->values();
        return $filtered->count() === 1 ? $filtered->first() : null;
    }

    /**
     * Candidate P24Suburb rows whose name matches the given suburb name.
     * Exact mode matches slug or case-insensitive name equality; fuzzy mode
     * widens to a normalised LIKE both ways.
     *
     * @return \Illuminate\Support\Collection<int, P24Suburb>
     */
    private function suburbNameCandidates(string $suburbName, bool $fuzzy): \Illuminate\Support\Collection
    {
        $key = strtolower(trim($suburbName));
        if ($key === '') return collect();

        // AT-P24 remediation (#2): only P24-VERIFIED rows are eligible candidates.
        // An unverified row must never be returned (its p24_id may be rejected by
        // P24) nor count toward the uniqueness test that disambiguates collisions.
        if (!$fuzzy) {
            $slug = str_replace(' ', '-', $key);
            return P24Suburb::whereNotNull('p24_verified_at')
                ->where(function ($q) use ($slug, $key) {
                    $q->where('slug', $slug)->orWhereRaw('LOWER(name) = ?', [$key]);
                })
                ->get();
        }

        $normalised = strtolower(preg_replace('/[^a-z0-9 ]+/i', '', trim($suburbName)));
        if ($normalised === '') return collect();

        return P24Suburb::whereNotNull('p24_verified_at')
            ->where(function ($q) use ($normalised) {
                $q->whereRaw('LOWER(name) LIKE ?', ['%' . $normalised . '%'])
                  ->orWhereRaw('? LIKE CONCAT(\'%\', LOWER(name), \'%\')', [$normalised]);
            })
            ->get();
    }

    /**
     * The set of P24 city IDs (p24_cities.id) this property could legitimately
     * sit in, used to disambiguate collision suburb names. Trust order: the
     * stored p24_city_id FK first, else the city/town text (province-constrained
     * when the province is known). Empty array = no usable city signal.
     *
     * @return int[]
     */
    private function candidateCityIds(Property $property): array
    {
        if ($property->p24_city_id) {
            return [(int) $property->p24_city_id];
        }

        $cityNames = array_values(array_unique(array_filter([
            strtolower(trim((string) $property->city)),
            strtolower(trim((string) $property->town)),
        ], fn ($v) => $v !== '')));
        if (empty($cityNames)) return [];

        $query = P24City::query()->where(function ($q) use ($cityNames) {
            foreach ($cityNames as $n) {
                $q->orWhereRaw('LOWER(name) = ?', [$n]);
            }
        });

        // Province narrows same-named cities to the right one when we know it.
        $provinceId = $this->resolveProvinceId($property);
        if ($provinceId) {
            $query->where('p24_province_id', $provinceId);
        }

        return $query->pluck('id')->map(fn ($id) => (int) $id)->all();
    }

    /**
     * Resolve the property's province to a p24_provinces.id. Trust the stored
     * FK first; else match the province text after normalising both sides
     * (P24 stores "KwaZulu Natal", CoreX often holds "KwaZulu-Natal"/"KZN").
     */
    private function resolveProvinceId(Property $property): ?int
    {
        if ($property->p24_province_id) return (int) $property->p24_province_id;

        $name = $this->normaliseProvince($property->province);
        if ($name === '') return null;

        $key = preg_replace('/[^a-z0-9]+/i', '', strtolower($name));
        foreach (P24Province::all() as $province) {
            if (preg_replace('/[^a-z0-9]+/i', '', strtolower((string) $province->name)) === $key) {
                return (int) $province->id;
            }
        }
        return null;
    }

    private function normaliseProvince(?string $province): string
    {
        $p = strtolower(trim((string) $province));
        if ($p === '') return '';
        return match (true) {
            str_contains($p, 'kwazulu') || $p === 'kzn'   => 'KwaZulu-Natal',
            str_contains($p, 'western')                   => 'Western Cape',
            str_contains($p, 'eastern')                   => 'Eastern Cape',
            str_contains($p, 'northern')                  => 'Northern Cape',
            str_contains($p, 'north west')                => 'North West',
            str_contains($p, 'gauteng') || $p === 'gp'    => 'Gauteng',
            str_contains($p, 'mpumalanga')                => 'Mpumalanga',
            str_contains($p, 'limpopo')                   => 'Limpopo',
            str_contains($p, 'free state')                => 'Free State',
            default                                        => ucwords($p),
        };
    }

    /**
     * Map CoreX property type to P24 propertyTypeId.
     * IDs sourced from GET /listing/v53/property-types on ExDev:
     *   4 = House, 5 = Apartment/Flat, 6 = Townhouse,
     *   8 = Vacant Land/Plot, 10 = Farm, 11 = Commercial, 12 = Industrial
     */
    private function resolvePropertyTypeId(?string $type): ?int
    {
        if (empty($type)) return null;

        // Normalise: lowercase, replace any non-alphanum with single space, collapse, trim.
        // Lets us match "Apartment / Flat", "Apartment/Flat", "apartment-flat", etc.
        $norm = trim(preg_replace('/\s+/', ' ', preg_replace('/[^a-z0-9]+/i', ' ', strtolower($type))));

        $padded = " {$norm} ";
        $contains = function (string ...$needles) use ($padded): bool {
            foreach ($needles as $n) {
                if (str_contains($padded, " {$n} ")) return true;
            }
            return false;
        };

        if ($contains('industrial')) return 12;
        if ($contains('commercial', 'office', 'retail', 'hospitality')) return 11;
        if ($contains('farm', 'smallholding', 'small holding', 'agricultural')) return 10;
        if ($contains('vacant land', 'land', 'plot', 'stand', 'erf')) return 8;
        if ($contains('townhouse', 'duplex', 'simplex', 'cluster')) return 6;
        if ($contains('apartment', 'flat', 'penthouse')) return 5;
        if ($contains('house', 'freestanding', 'free standing', 'cottage', 'garden cottage')) return 4;

        return 4; // default: House
    }

    private function resolveContactAgentIds(Property $property, int $agencyId): array
    {
        // Build an agency-scoped client so credentials come from the property's
        // agency row (not the now-empty .env). Without this the client falls
        // back to env creds, authenticates as nobody, and returns zero agents
        // — which P24 then rejects as "must have one or more agents".
        $agency = $property->agency ?? \App\Models\Agency::find($property->agency_id);
        $client = new Property24ApiClient($agency);
        // Scope the lookup to the property's resolved agency — otherwise a
        // property under agency B would pull agents from agency A's feed.
        $result = $client->getAgents((string) $agencyId);

        if (!$result['success']) return [];

        $agents = $result['data'] ?? [];
        $ids = [];

        // Agents who opted out of P24 must never be attached to a syndicated
        // listing, even if a stale P24 record still carries their sourceReference.
        $excludedUserIds = \App\Models\User::withTrashed()
            ->whereIn('id', array_filter([$property->agent_id, $property->pp_second_agent_id]))
            ->where('exclude_from_p24', true)
            ->pluck('id')
            ->all();

        // Primary agent
        if ($property->agent_id && !in_array((int) $property->agent_id, $excludedUserIds, true)) {
            $sourceRef = 'CoreX-Agent-' . $property->agent_id;
            foreach ($agents as $agent) {
                if (($agent['sourceReference'] ?? '') === $sourceRef) {
                    $ids[] = (int) $agent['id'];
                    break;
                }
            }
        }

        // Second agent
        if ($property->pp_second_agent_id && !in_array((int) $property->pp_second_agent_id, $excludedUserIds, true)) {
            $sourceRef = 'CoreX-Agent-' . $property->pp_second_agent_id;
            foreach ($agents as $agent) {
                if (($agent['sourceReference'] ?? '') === $sourceRef) {
                    $ids[] = (int) $agent['id'];
                    break;
                }
            }
        }

        return $ids;
    }

    private function buildShowdays(Property $property): array
    {
        $showdays = [];
        $active = $property->activeShowdays ?? $property->showdays()->where('active', true)->where('end_date', '>=', now())->get();

        foreach ($active as $s) {
            $showdays[] = [
                'startDate' => $s->start_date->format('Y-m-d\TH:i:s'),
                'endDate'   => $s->end_date->format('Y-m-d\TH:i:s'),
            ];
        }

        return $showdays;
    }

    /**
     * Map CoreX property status to P24 ListingStatus enum.
     * P24 statuses: NewListing, Active, Rented, Withdrawn, BackOnMarket,
     *               Expired, Extended, RaisedPrice, ReducedPrice,
     *               Cancelled, Pending, Sold, CancelledSale
     */
    private function mapPropertyStatus(Property $property): string
    {
        return self::getP24Status($property->status, $property->p24_ref, $property->status_label);
    }

    /**
     * Static helper: convert a CoreX two-tier status (base status + optional
     * sub-label banner) to a P24 ListingStatus. Used by both the mapper and the
     * observer.
     *
     * Two-tier model (mirrors P24/Propcon): a listing has a BASE status and an
     * optional SUB-LABEL on an on-market base — e.g. For Sale + "Reduced Price",
     * For Sale + "Pending", For Sale + "Back on Market". Every sub-label banner
     * is an ON-MARKET refinement, so it may only refine an on-market base: a
     * TERMINAL / off-market base status (sold, withdrawn, expired, cancelled,
     * let-out, draft, …) is resolved FIRST and is absolute — it can never be
     * overridden by a banner. Only once the base is on-market does the sub-label
     * take precedence; an on-market base with no label falls through to the
     * base-status logic.
     *
     * WHY the terminal base wins (the bug this ordering fixes): a listing is
     * routinely Active + a sticky banner (e.g. "Reduced Price"). When it is
     * later withdrawn/sold, the banner is not always cleared alongside the base
     * status (the web edit form clears it; other ingress paths historically did
     * not). If the banner were still resolved first, getP24Status() would return
     * 'ReducedPrice' — an on-market state — and the observer would leave the
     * listing LIVE on the portal even though CoreX shows it Withdrawn. A stale
     * on-market banner must never resurrect an off-market listing.
     *
     * Back-compat: $statusLabel is optional and defaults to null. With a null
     * label this returns exactly what the prior flat-status version returned for
     * every base status — proven by the AT-P24 before/after round-trip table —
     * with one intentional fix: a let-out rental now maps to 'Rented' instead of
     * silently falling through to 'NewListing'. The only other behaviour change
     * is the intended one above: a terminal base + on-market banner now resolves
     * to the terminal status instead of the banner.
     */
    public static function getP24Status(?string $corexStatus, ?string $p24Ref = null, ?string $statusLabel = null): string
    {
        $normalise = static function (?string $v): string {
            $v = strtolower(str_replace(['•', '_'], ['', ' '], trim($v ?? '')));
            return preg_replace('/\s+/', ' ', $v); // collapse multiple spaces
        };

        $status = $normalise($corexStatus);

        // 1) A terminal / off-market BASE status is absolute. It is resolved
        //    before the sub-label so a stale on-market banner (Reduced Price,
        //    Back on Market, …) can never keep a withdrawn/sold/expired listing
        //    live on the portal. See the WHY note in the docblock.
        $terminal = match (true) {
            str_contains($status, 'sold')              => 'Sold',
            str_contains($status, 'rented')
                || str_contains($status, 'let out')     => 'Rented',
            str_contains($status, 'withdrawn')
                || str_contains($status, 'unavailable') => 'Withdrawn',
            str_contains($status, 'expired')            => 'Expired',
            str_contains($status, 'cancelled')
                || str_contains($status, 'archived')    => 'Cancelled',
            str_contains($status, 'draft')              => 'Withdrawn',
            default                                     => null,
        };
        if ($terminal !== null) {
            return $terminal;
        }

        // 2) On-market base: the sub-label (banner) takes precedence — it is the
        //    authoritative P24 lifecycle refinement on top of an Active listing.
        $label = $normalise($statusLabel);
        if ($label !== '') {
            $fromLabel = match (true) {
                str_contains($label, 'reduced')        => 'ReducedPrice',
                str_contains($label, 'raised')         => 'RaisedPrice',
                str_contains($label, 'back on market') => 'BackOnMarket',
                str_contains($label, 'under offer')
                    || str_contains($label, 'pending') => 'Pending',
                default                                => null,
            };
            if ($fromLabel !== null) {
                return $fromLabel;
            }
        }

        // 3) On-market base status (no resolving label).
        return match (true) {
            str_contains($status, 'under offer')
                || str_contains($status, 'pending')     => 'Pending',
            str_contains($status, 'back on market')     => 'BackOnMarket',
            str_contains($status, 'reduced')            => 'ReducedPrice',
            str_contains($status, 'raised')             => 'RaisedPrice',
            str_contains($status, 'auction')            => 'Active',
            $p24Ref !== null                            => 'Active',
            default                                     => 'NewListing',
        };
    }

    /**
     * Check if a P24 status is a terminal/off-market status.
     */
    public static function isTerminalStatus(string $p24Status): bool
    {
        return in_array($p24Status, ['Sold', 'Rented', 'Withdrawn', 'Expired', 'Cancelled']);
    }

    /**
     * Does pushing this P24 status take the listing OFF the portal?
     *
     * Terminal is NOT the same as removed. 'Sold' and 'Rented' are terminal
     * market states that P24 keeps on the portal (it shows them as sold/rented
     * stock); only 'Withdrawn', 'Expired' and 'Cancelled' actually remove the
     * listing. Conflating the two stranded live listings: a Sold push wrote
     * p24_syndication_status='deactivated', and every delist path downstream
     * then skipped the property as "already off the portal" while P24's own
     * is-on-portal still answered true.
     *
     * Audit: .ai/audits/p24-sold-not-delisted-2026-07-10.md (property #2142)
     */
    public static function removesFromPortal(string $p24Status): bool
    {
        return in_array($p24Status, ['Withdrawn', 'Expired', 'Cancelled'], true);
    }

    private function mapListingType(?string $type): string
    {
        if (empty($type)) return 'Sale';
        return match (strtolower($type)) {
            'sale', 'for sale', 'sell' => 'Sale',
            'rental', 'rent', 'to let' => 'Rental',
            default => 'Sale',
        };
    }

    private function parseStreetName(?string $address): string
    {
        if (empty($address)) return '';
        $parts = explode(',', $address);
        return preg_replace('/^\d+\s+/', '', trim($parts[0] ?? ''));
    }

    private function extractYouTubeId(?string $input): ?string
    {
        if (!$input) return null;
        $input = trim($input);
        if (preg_match('/^[a-zA-Z0-9_-]{11}$/', $input)) return $input;
        if (preg_match('/(?:youtube\.com\/(?:watch\?\S*?v=|embed\/|shorts\/|live\/|v\/)|youtu\.be\/|v=)([a-zA-Z0-9_-]{11})/', $input, $m)) {
            return $m[1];
        }
        return null;
    }
}
